Added variable background colors to platform bg and navbar
ToolJet/ToolJet pull request #10072
Opened 2024-06-13 06:12 UTC by rudeUltra

Fixes #9933

2024-06-13 10:12 UTC, akshaysasidrn commented
/review

2024-06-16 20:00 UTC, stepinfwd requested changes

2024-06-16 20:04 UTC, stepinfwd commented
*marketplace page bg is not changed
*Upon refresh i am able to see old base color

2024-06-18 07:11 UTC, stepinfwd submitted a review, later dismissed

2024-06-18 09:27 UTC, gsmithun4 approved these changes

2024-06-18 09:27 UTC, merged