platform release 18 bug fixes
ToolJet/ToolJet pull request #10156
Opened 2024-06-24 12:00 UTC by rudeUltra

2024-06-25 11:41 UTC, rudeUltra commented
CSS Issues Fixed:
1). Datasource page bg colour fix
![image](https://github.com/ToolJet/ToolJet/assets/98055396/180e5626-1e2f-474b-bd70-b5196da4fe78)


2) Pagination alignment
![image](https://github.com/ToolJet/ToolJet/assets/98055396/64bd340e-9e97-4785-afaa-e9f9d2d699ad)

3) Notification box getting cropped
![image](https://github.com/ToolJet/ToolJet/assets/98055396/8bba431e-1bd9-4630-b12c-7a70ae598dda)


4)Create/Edit folder button alignment
![image](https://github.com/ToolJet/ToolJet/assets/98055396/36181aed-9da7-4d1a-be6d-a558889561d4)

2024-06-26 05:37 UTC, stepinfwd requested changes

2024-06-26 05:37 UTC, stepinfwd commented on frontend/src/GlobalDatasources/List/index.jsx
> +          {filteredData.length === 0 && dataSources.length !== 0 ? 'No results found' : 'No datasources added'}
add null check here

2024-06-26 05:37 UTC, stepinfwd commented on frontend/src/_styles/global-datasources.scss
>      // background: var(--slate2);
remove commented line

2024-06-26 05:37 UTC, stepinfwd commented on frontend/src/_styles/tabler.scss
> +    z-index: 9999;
is this change required

2024-06-26 05:37 UTC, stepinfwd commented on frontend/src/_styles/theme.scss
> +    min-height: 100px;
this is a common change make sure it doesn't affect other places

2024-06-26 05:37 UTC, stepinfwd commented on frontend/src/_styles/theme.scss
> +    white-space: nowrap;
form control is a common class this might affect other places where it is used

2024-06-26 05:37 UTC, stepinfwd commented on frontend/src/_ui/Pagination/index.jsx
> +          className="form-control-pagination"
check here

2024-06-26 05:37 UTC, stepinfwd commented on frontend/src/_styles/theme.scss
> +      }
i can see slate1 slate12 etc used just confirm once as these are older border colors , if its given in figma then leave it.

2024-06-26 05:45 UTC, stepinfwd commented on frontend/src/_ui/Pagination/index.jsx
> +          className="form-control-pagination"
you can add it as separate classes to extend css

2024-06-26 06:11 UTC, stepinfwd approved these changes

2024-06-26 06:14 UTC, merged