Group revamp fix krit
ToolJet/ToolJet pull request #10215
Opened 2024-06-28 08:20 UTC by kriks7iitk

1. Added fix for user group revamp

2024-06-28 08:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10215) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10215) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: kriks7iitk<br/>:white_check_mark: vjaris42<br/>:x: kriks7raptor<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=10215) it.</sub>

2024-07-25 11:11 UTC, shah21 requested changes
I have added some observations, please take a look @kriks7iitk

2024-07-25 11:11 UTC, shah21 commented on frontend/src/ManageGroupPermissionsV2/ResourceChip.jsx
> +            {/* orderedArray.slice(0, 2).map((group, index) => {
Please remove these lines if it is no longer needed.

2024-07-25 11:11 UTC, shah21 commented on frontend/src/_ui/AppButton/AppButton.scss
> +    // box-sizing: border-box;
Please make sure that this change doesn't affect any other components that use this class.

2024-09-25 05:20 UTC, merged