Add missing Spanish translations
ToolJet/ToolJet pull request #10254
Opened 2024-07-02 21:47 UTC by ShyanRoyChoudhury

This PR adds missing spanish translations for the entire app.

refactor: #9611

2024-08-14 05:22 UTC, johnsoncherian requested changes

2024-08-14 05:22 UTC, johnsoncherian commented on frontend/package-lock.json
> +=======
Conflicts need to be resolved properly.
Also do we need package.json changes?

2024-08-21 10:24 UTC, PriteshKiri commented
@ShyanRoyChoudhury can you please look into the comments?

2024-09-16 05:23 UTC, PriteshKiri commented
Closing this PR due to lack of progress

2024-09-16 05:23 UTC, closed without merging