feature: change colors for invite users drawer
ToolJet/ToolJet pull request #10750
Opened 2024-09-12 08:54 UTC by maxdiplogit

Closes: #10700

This PR changes the dark mode colors for the Invite users drawer. Colors have been picked up as described in the issue description. The changes reflected will be as follows:

![Screenshot from 2024-09-12 14-19-45](https://github.com/user-attachments/assets/ee236327-fa04-4e09-bd81-a01fb7f0bfec)

Would be happy to make any changes if required :smile:

2024-10-16 05:42 UTC, shah21 requested changes
I have added a minor comment. Could you please take a look.

2024-10-16 05:42 UTC, shah21 commented on frontend/src/ManageOrgUsers/InviteUsersForm.jsx
> +                  ? t('header.organization.menus.manageUsers.inviteNewUsers', 'Add new user')
Could you please revert this change? The related GitHub issue doesn't have this change requested.

2024-11-20 07:28 UTC, PriteshKiri commented
Hey @maxdiplogit,

Are you still working on the issue?

2024-11-27 05:54 UTC, PriteshKiri commented
Closing due to lack of progress

2024-11-27 05:54 UTC, closed without merging