Updated the documentation for the Timeline Component
ToolJet/ToolJet pull request #10860
Opened 2024-10-01 12:27 UTC by Asymtode712

# Description

Closes #10847 

This PR updates the documentation for the Timeline component in both the main and LTS versions of the ToolJet documentation.

## Changes Made

1. **Improved Introduction**
   - Added a more descriptive introduction to better explain the Timeline component's purpose and use cases.

2. **Updated Formatting**
   - Applied the latest style guide recommendations to improve readability and consistency.

3. **Layout Updates**
   - Renamed "Layout" section to "Devices" for clarity.
   - Updated the description and expected values in the Devices table.

4. **Styles Table Enhancements**
   - Restructured the Styles table with new headers: Property, Description, and Configuration Options.
   - Added "Box Shadow" property to the Styles table.

5. **Removed Redundant Padding**
   - Eliminated 24px padding-bottom from h2 headers and their sections to improve layout consistency.

6. **General Cleanup**
   - Made minor adjustments to improve overall document structure and clarity.

## Files Modified

- `docs/docs/widgets/timeline.md`
- `docs/versioned_docs/version-2.50.0-LTS/widgets/timeline.md`

2024-10-01 12:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10860) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10860) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=10860) it.</sub>

2024-10-03 11:33 UTC, RudraPratik30 requested changes
Please make the mentioned changes in both the versions.

2024-10-03 11:33 UTC, RudraPratik30 commented on docs/docs/widgets/timeline.md
>  ### Timeline data
Please make sure all the headings are in title case only. Please refer the [style guide](https://docs.tooljet.com/docs/contributing-guide/documentation-guidelines/style-guide/#2-headings). Apply this to all headings in the document.

2024-10-03 11:33 UTC, RudraPratik30 commented on docs/docs/widgets/timeline.md
> +| Show on desktop | Controls the component's desktop visibility | Set to `{{true}}` to show on desktop, `{{false}}` to hide |
For the expected value column, please use the same content provided in the [reference](https://docs.tooljet.com/docs/widgets/text-input/#devices). Edit this in both the rows.

2024-10-03 11:33 UTC, RudraPratik30 commented on docs/versioned_docs/version-2.50.0-LTS/widgets/timeline.md
> +Any property with an `Fx` button next to it can be **programmatically configured**.
The fx should be bold and not enclosed in single ticks. Please refer to the [style guide](https://docs.tooljet.com/docs/contributing-guide/documentation-guidelines/style-guide/#1-text-formatting-guidelines) for details.

2024-10-03 11:33 UTC, RudraPratik30 commented on docs/docs/widgets/timeline.md
> +**Data requirements:** The data should be an array of objects. Each object must have `title`, `subTitle`, `iconBackgroundColor`, and `date` keys. The `iconBackgroundColor` can be a hex color code or
Please make sure the keys are in bold and not enclosed in single ticks.

2024-10-03 11:33 UTC, RudraPratik30 commented on docs/docs/widgets/timeline.md
> +Any property with an `Fx` button next to it can be **programmatically configured**.
The fx should be bold and not enclosed in single ticks. Please refer to the [style guide](https://docs.tooljet.com/docs/contributing-guide/documentation-guidelines/style-guide/#1-text-formatting-guidelines) for details.

2024-10-03 16:25 UTC, Asymtode712 commented
@RudraPratik30 I have done the changes as requested by you, please review the changes and merge them if they are good to go

2024-10-03 16:34 UTC, RudraPratik30 commented on docs/docs/widgets/timeline.md
> +| Show on desktop | Controls the component's desktop visibility | Set to `{{true}}` to show on desktop, `{{false}}` to hide |
@Asymtode712 I think this issue is yet to be resolved.

2024-10-03 16:42 UTC, RudraPratik30 commented
Hey @Asymtode712, I think one of the reviews is yet to be resolved, please make the necessary changes and then I will forward the PR to the team, thanks!
Please check this: https://github.com/ToolJet/ToolJet/pull/10860#discussion_r1786058133

2024-10-03 16:57 UTC, Asymtode712 commented
> Hey @Asymtode712, I think one of the reviews is yet to be resolved, please make the necessary changes and then I will forward the PR to the team, thanks! Please check this: [#10860 (comment)](https://github.com/ToolJet/ToolJet/pull/10860#discussion_r1786058133)

@RudraPratik30 Done!

2024-10-03 17:15 UTC, RudraPratik30 submitted a review, later dismissed

2024-10-03 17:17 UTC, RudraPratik30 commented
Hey @Asymtode712, thanks for contributing!
I have approved the changes from my end, now forwarding the PR to the team.
Your PR will be merged soon. Happy Coding!

2024-10-04 13:16 UTC, adishM98 approved these changes

2024-10-04 13:16 UTC, merged