updated the documentation for the vertical divider component
ToolJet/ToolJet pull request #10862
Opened 2024-10-01 13:38 UTC by PARVNEMA

i have updated the documentation for the vertical divide component .
fixes #10844

2024-10-01 13:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10862) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10862) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=10862) it.</sub>

2024-10-04 06:07 UTC, RudraPratik30 commented
Hey @PARVNEMA!!

Can you please correct the syntax on line no. 17?
There should be two closing curly braces, in both the version.
Please do it, so that we can deploy the PR on render and test it out.

2024-10-04 07:23 UTC, PARVNEMA commented
Ok i am doing it

2024-10-04 07:28 UTC, PARVNEMA commented
@RudraPratik30  done it sir

2024-10-04 07:41 UTC, RudraPratik30 commented
Hey, you just made the changes in only one version, can you edit the next version as well?

2024-10-04 07:43 UTC, PARVNEMA commented
@RudraPratik30  sir i have made changes in both the versions

2024-10-04 07:47 UTC, PARVNEMA commented
@RudraPratik30  done it sir and sorry this is my first open source contribution and i am learning

2024-10-04 08:38 UTC, RudraPratik30 commented
No worries @PARVNEMA, It's alright!

2024-10-04 10:05 UTC, RudraPratik30 requested changes
Hey, Please make the MENTIONED changes in both the versions.

2024-10-04 10:05 UTC, RudraPratik30 commented on docs/docs/widgets/vertical-divider.md
> +| Visibility | Controls whether the divider is visible. Accepts Boolean values. | `true` (visible), `false` (hidden) |
Row: Visibility, Column: Configuration Options
Please update the content, include how we can use the fx function there, check out the [reference](https://docs.tooljet.com/docs/widgets/text-input/#label).

2024-10-04 10:05 UTC, RudraPratik30 commented on docs/docs/widgets/vertical-divider.md
> +| Box Shadow | Adds shadow around the divider to create depth. | Accepts `box-shadow` values like `none`, `2px 4px 6px rgba(0, 0, 0, 0.1)` |
Row: Box Shadow, Column: Configuration Options
box-shadow should be a normal text and should not be enclosed in single ticks

2024-10-04 10:05 UTC, RudraPratik30 commented on docs/docs/widgets/vertical-divider.md
> +Under the <b>General</b> accordion, you can set the value in the string format. Now hovering over the component will display the string as the tooltip.
Use * to mark something bold instead of using HTML tags

2024-10-04 10:08 UTC, PARVNEMA commented
Ok will apply changes and send

2024-10-05 00:44 UTC, PARVNEMA commented
@RudraPratik30  done changes

2024-10-07 06:02 UTC, RudraPratik30 approved these changes
Hey @parvnema approving the changes from my end and forwarding it to the team for final review.
Thanks for contributing! Your PR will be merged by the end of this week.

2024-10-07 06:07 UTC, PARVNEMA commented
Thanks @RudraPratik30  for this opportunity and if any more issue please tell me

2024-10-07 06:15 UTC, RudraPratik30 approved these changes

2024-10-09 09:01 UTC, karan-rathod-316 approved these changes
Looks good to me.

2024-10-10 04:36 UTC, merged