Updated the documentation for the Timer Component #10846
ToolJet/ToolJet pull request #10863
Opened 2024-10-01 17:17 UTC by krishnadev7

#  Description

Closes [10846](https://github.com/ToolJet/ToolJet/issues/10846)

### Changes Made

1. Formatting updates:  
- Updated the formatting based on the latest guidlines 
- For each h2 (created using ##), removed 24px padding-bottom.

2. Content updates: 

-  Added more descriptive introduction
- Replaced the word "widget" with "component" everywhere
- Replaced the header "Layout" with "Devices"
- Updated the Description and Expected Value columns 
- Added a divider before the "Styles" section
- Updated the description in the Events table
- Updated the styles table with three headers - Property, Description, Configuration Options
- Updated the content of the style table
- Included box-shadow under the Styles table

## Files Modified

- Next -` ToolJet/docs/docs/widgets/timer.md`
- Version 2.50.0 (LTS) - `ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/timer.md`

2024-10-01 17:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10863) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10863) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=10863) it.</sub>

2024-10-04 06:11 UTC, RudraPratik30 commented
Hey @krishnadev7!
Can you please correct the syntax on line no. 81?
<hr> tag must be written as <hr/> since it is a self-closing tag.
Please do it so that we can deploy this on render and complete the review.

2024-10-04 07:31 UTC, RudraPratik30 requested changes

2024-10-04 07:31 UTC, RudraPratik30 commented on docs/docs/widgets/timer.md
> +| Default value                                  | It specifies the initial value of timer. Format is: `HH.mm.ss.SS`.
Hey, the format should be `HH.MM.SS.MS`, can you please change this?

2024-10-04 07:31 UTC, RudraPratik30 commented on docs/docs/widgets/timer.md
> +| :------------------------------------------ | :---------------------------------------------------------------------------------------------------------------- |
Hey @krishnadev7, can you please recheck this table?
The events and their descriptions do not match. Also, this is the timer component, you have added description for the text input component, please correct that too.
Thanks!

2024-10-04 10:17 UTC, closed without merging

2024-10-04 11:02 UTC, krishnadev7 commented
Hey @RudraPratik30 , I accidentally closed the PR and can't reopen it. I've raised a new PR. Please take a look!

2024-10-04 11:06 UTC, RudraPratik30 commented
Hey @krishnadev7, there must be an option to reopen the PR, @PriteshKiri can you help us with this?

Also @krishnadev7 I can see you have opened 2 new PRs #10880 and #10881 can you close the one that is not needed?

2024-10-04 11:11 UTC, PriteshKiri commented
Hey @RudraPratik30, we can keep this issue closed for now.
@krishnadev7, please close the stale PR and let us know which one needs to be reviewed.

2024-10-04 13:32 UTC, krishnadev7 commented
hey @PriteshKiri  Closed PR #10880. I would like to review PR #10881. Thanks!