Fix: #10870
ToolJet/ToolJet pull request #10889
Opened 2024-10-04 17:33 UTC by prathamranjansingh

Fixed the isuue- [docs]: Wrong roadmap link in README #10870

2024-10-04 17:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10889) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10889) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=10889) it.</sub>

2024-10-06 15:08 UTC, RudraPratik30 requested changes
Hey @prathamranjansingh, please make the mentioned change. Thanks!

2024-10-06 15:08 UTC, RudraPratik30 commented on README.md
> +_For users upgrading their ToolJet version, we recommend choosing the LTS version over the latest version. The LTS version ensures stability with production bug fixes, security patches, and performan
Hey @prathamranjansingh!
Can you please revert this change? Use ** instead of _ _ for this line.

2024-10-07 05:50 UTC, RudraPratik30 approved these changes
Hey @prathamranjansingh!
Approving changes from my end and forwarding this to the team for final review.
Thank you for contributing, your PR will be merged by the end of this week.

2024-10-07 11:24 UTC, prathamranjansingh commented
I am really sorry sir that you had to do the changes. Next time i will be
careful and ask someone to assign me the issue also. Thank you sir


On Mon, Oct 7, 2024 at 11:20 AM Pratik Agrawal ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hey @prathamranjansingh <https://github.com/prathamranjansingh>!
> Approving changes from my end and forwarding this to the team for final
> review.
> Thank you for contributing, your PR will be merged by the end of this week.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ToolJet/ToolJet/pull/10889#pullrequestreview-2350913342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQEWYRNNHLDCK7V4P2TOEI3Z2IOLJAVCNFSM6AAAAABPMJ2GXSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNJQHEYTGMZUGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-08 05:29 UTC, RudraPratik30 requested changes

2024-10-08 05:29 UTC, RudraPratik30 commented on package.json
Can you check what's the change in this file and revert it?

2024-10-08 05:36 UTC, RudraPratik30 commented
Also @prathamranjansingh can you please let me know what changes you have made after the PR was approved?

2024-10-08 05:41 UTC, RudraPratik30 approved these changes
Hey @prathamranjansingh, approving the PR from my end and forwarding it to the team for final review. Your PR will be merged by the end of this week.
You are not required to push any more commits once your PR is approved, this will revoke the stable review.
Thanks for contributing!

2024-10-09 09:10 UTC, karan-rathod-316 approved these changes
Looks good to me.

2024-10-10 04:37 UTC, merged