[docs]: Updated the documentation for the Timer Component #10846
ToolJet/ToolJet pull request #10881
Opened 2024-10-04 10:58 UTC by krishnadev7

my previous pr was closed accidently and i am submiting the updated changes.
[link to the previous pr](https://github.com/ToolJet/ToolJet/pull/10863)

_Updated Review changes_

- removed internal.sh file from docker
- removed rest of the rows from styles table and updated description
- changed fx, count down and count up to bold from single tick
- updated time fromat `HH.MM.SS.MS` from `HH.mm.ss.SS`
- rechecked the events table and updated the description

2024-10-04 11:46 UTC, RudraPratik30 requested changes
Hey @krishnadev7 please make the mentioned changes, thanks!

2024-10-04 11:46 UTC, RudraPratik30 commented on docs/docs/widgets/timer.md
> +| Timer type                                     | It specifies If its a upward or downward counter. Select **Count Up** or **Count Down** from the dropdown or you can click on **Fx** to programmatic
Hey, the f in the fx should be small and not Fx, please check for this in the whole doc and both the version.

2024-10-04 11:46 UTC, RudraPratik30 commented on docs/docs/widgets/timer.md
> +<div style={{paddingTop:'24px'}}>
The div should start after the hr tag

2024-10-04 11:58 UTC, RudraPratik30 commented on docs/docs/widgets/timer.md
> -</div>
Please close the div tag initialized for the style section.

2024-10-06 12:10 UTC, RudraPratik30 submitted a review, later dismissed
Hey @krishnadev7!
Approving the PR from my end, and forwarding it to the team for final review.
Your PR will be merged by the end of this week.
Thanks for contributing!
Cc: @PriteshKiri

2024-10-08 08:12 UTC, karan-rathod-316 approved these changes
Looks good to me.

2024-10-10 04:36 UTC, merged

2024-11-04 10:25 UTC, PriteshKiri commented
fixes #10846