Update the documentation for the SVG Image Component
ToolJet/ToolJet pull request #10910
Opened 2024-10-08 12:53 UTC by sanketshinde3001

Solved the issue - #10898 

Changes done in both docs (current and Version 2.50.0 (LTS) )

@RudraPratik30 Solved that Bold Text issue.

2024-10-08 12:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10910) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10910) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=10910) it.</sub>

2024-10-09 05:38 UTC, RudraPratik30 requested changes

2024-10-09 05:38 UTC, RudraPratik30 commented on docs/docs/widgets/svg-image.md
> +| Show on desktop | Toggle on or off to display desktop view. | You can programmatically determining the value by clicking on **fx** to set the value `{{true}}` or `{{false}}` |
Hey, can you just add the full stops at the end? In the expected value column, probably the last change needed.
Please make the changes in both versions.

2024-10-09 10:03 UTC, RudraPratik30 approved these changes
Hey, @sanketshinde3001 approving the PR from my end and forwarding it to the team for final review.
Thanks for contributing!
Your PR will be merged by the end of this week

2024-10-11 07:32 UTC, RudraPratik30 commented
Hey @sanketshinde3001 can you please sign the [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10910) before we can accept your contribution.

2024-10-11 10:52 UTC, sanketshinde3001 commented
@RudraPratik30 Done Sir 👍

2024-10-15 04:11 UTC, sanketshinde3001 commented
@RudraPratik30 waiting to merge this pr.

2024-10-15 04:26 UTC, RudraPratik30 commented
Hey @sanketshinde3001, sorry the things got delayed since the CLA was not signed, but we assure you that your PR will be merged as soon as possible, you can expect it by the end of this week.

2024-10-15 06:22 UTC, sanketshinde3001 commented
@RudraPratik30  Ohk Sir. I signed CLA already.

2024-10-15 06:45 UTC, merged