updated spinner.md
ToolJet/ToolJet pull request #10931
Opened 2024-10-10 12:35 UTC by lakshita10341

i have done the changes. please verify it

2024-10-10 12:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10931) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10931) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=10931) it.</sub>

2024-10-11 07:48 UTC, RudraPratik30 requested changes

2024-10-11 07:48 UTC, RudraPratik30 commented on docs/docs/widgets/spinner.md
> +| Show on desktop | Toggle on or off to display desktop view. | You can programmatically determining the value by clicking on `fx` to set the value `{{true}}` or `{{false}}` |
Hey @lakshita10341, the fx should be in bold and not enclosed in back tick, can you please make this change in the whole doc and both versions where ever applicable.

2024-10-11 07:48 UTC, RudraPratik30 commented on docs/docs/widgets/spinner.md
> +| Show on mobile  | Toggle on or off to display mobile view.  | You can programmatically determining the value by clicking on `fx` to set the value `{{true}}` or `{{false}}` |
Can you please also add a full stop at the end of sentence here? Please do this for both the sentence in the table and in both versions.

2024-10-13 11:39 UTC, PriteshKiri commented
Hey @lakshita10341,

Can you please make the changes asked by @RudraPratik30 ?

2024-10-14 05:41 UTC, RudraPratik30 commented
Hey @lakshita10341!
Closing this PR due to lack of progress.

2024-10-14 05:41 UTC, closed without merging

2024-10-18 11:51 UTC, lakshita10341 commented
Hi @PriteshKiri 
I have done the changes which was said earlier and the PR was merged. Sorry for not replying on above suggested changes because I was busy that time somewhere else. So didn't see the mail. But now it is showing my pr is not merged which was merged earlier.
Can this issue be resolved?