[docs]: Update documentation for Spinner
ToolJet/ToolJet pull request #10978
Opened 2024-10-15 08:37 UTC by himanshubalani

**Description**
Updated spinner docs as mentioned in issue #10926

 **Formatting updates** 
 - removed padding bottom
 - added separator above styles
 
 **Content updates** 
- changed widgets to components
- changed `Fx` to **fx**
 - Didn't change any existing link, but changed alt text in "version-2.50.0-LTS/widgets/spinner.md" -  Widget Reference -> Component Reference.
 
[X] This PR solves https://github.com/ToolJet/ToolJet/issues/10926

Files on which changes are implemented -
Next - ToolJet/docs/docs/widgets/spinner.md
Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/spinner.md

Let me know if I am missing something else. I followed references when updating the content.

2024-10-15 08:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10978) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10978) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=10978) it.</sub>

2024-10-15 10:07 UTC, RudraPratik30 commented
Hey @himanshubalani, you were expected to make the changes in the LTS version - 2.50.0
Please revert all the changes from the 2.5.0 version and make the necessary changes in the LTS version.

2024-10-15 10:49 UTC, himanshubalani commented
@RudraPratik30 I apologize for the mistake earlier. I have reverted the changes made in the wrong file. And made a commit with required changes to the correct file.

2024-10-15 11:00 UTC, RudraPratik30 requested changes
Hey @himanshubalani please make the mentioned changes, Thanks!

2024-10-15 11:25 UTC, himanshubalani commented on docs/docs/widgets/spinner.md
> +| Show on desktop | Toggle on or off to display desktop view. | You can programmatically change the value by clicking on **fx** to set the value `{{true}}` or `{{false}}`. |
Alright, I will edit the LTS version to have the word "change" instead of "determine".

2024-10-15 11:46 UTC, RudraPratik30 approved these changes
Hey @himanshubalani, thanks for contributing!
Approving the changes from my end and forwarding it to the team for final review.
Your PR will be merged by the end of this week, thanks again!

2024-10-20 07:44 UTC, karan-rathod-316 approved these changes
Looks good to me.

2024-10-21 10:31 UTC, merged