Update the documentation for the Image Component #10970
ToolJet/ToolJet pull request #10975
Opened 2024-10-15 07:49 UTC by devagn611

I understand. Here's a revised summary of the work you've done on Issue #10970 :

I have addressed Issue #10970 , implementing the following changes:

Formatting updates:
1. Replaced "Fx" with "**fx**" throughout the document, removing backticks and applying bold formatting.
2. Modified the padding for h2 sections:
   - Removed the 24px padding-bottom.
   - Adjusted the wrapping div to have only a padding-top of 24px, eliminating the padding-bottom.

Content updates:
1. Replaced the term "widget" with "component" throughout the document, while preserving URLs.
2. Updated the description of the "On click" event in the Events table, aligning with the reference provided (https://docs.tooljet.com/docs/widgets/text-input/#events).
3. Added a divider before the "Styles" section, as shown in the reference (https://docs.tooljet.com/docs/widgets/textarea#styles).

These changes improve the consistency and readability of the documentation, bringing it in line with the desired format and content structure.

2024-10-15 07:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10975) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=10975) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=10975) it.</sub>

2024-10-15 09:34 UTC, RudraPratik30 requested changes
Hey, @devagn611 please make the mentioned changes in both versions.
Few points to keep in mind:
1. You only need to edit 2 files that are mentioned in the issue, rest of the files should be kept untouched.
2. You only need to make fx bold and not rest of the things
3. You have to change widget to component in both version (except URLs)
4. Make constant changes in both versions.

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/text-input.md
Hey, @devagn611 you are supposed to edit the Image doc file only, please revert the changes from this file

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/textarea.md
Please revert changes from this file as well.

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/versioned_docs/version-2.50.0-LTS/widgets/textarea.md
Please revert changes from this file.

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/image.md
> +| Loading state | Loading state can be used to show a spinner as the image content. Loading state is commonly used with **isLoading** property of the queries to show a loading status while a query is
Hey, here only fx was needed to be in bold.
Can you please revert the changes you made on isLoading, true and false?
Please update this in the whole doc and both versions.

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/image.md
> +| Show on desktop | Toggle on or off to display desktop view. | You can programmatically determine the value by clicking on **fx** to set the value **{{true}}** or **{{false}}**. |
Here also, please revert the changes done on true and false.

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/image.md
> +| Image fit | Choose an image fit - similar to object fit for the image from available options: **fill**, **cover**, **contain**, **scale-down**. |
make the necessary changes in this section as well.

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/image.md
> +info Any property having an **fx** button next to its field can be **programmatically configured**.
info needs to be on the above line only.

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/image.md
>  The **Image** widget is used to display images in your app.
Here widget needs to be changed to component

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/image.md
>  | URL | Enter the URL of the image to display it on the widget. |
Here widget needs to be changed to component
Also, you have made a different change for this particular line in the LTS version, please check it and make the constant changes in both the docs.

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/image.md
For line no. 32
 you have made a different change for this particular line in the LTS version, please check it and make the constant changes in both the docs.

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/image.md
>  A Tooltip is often used to specify extra information about something when the user hovers the mouse pointer over the widget.
Please change the widget to component in both line 58 and 60

2024-10-15 09:34 UTC, RudraPratik30 commented on docs/docs/widgets/image.md
> +| Image fit | Choose an image fit - similar to object fit for the image from available options: **fill**, **cover**, **contain**, **scale-down**. |
1. revert the unnecessary bold
2. change widget to component

2024-10-15 12:55 UTC, devagn611 commented
Ok, I will make those changes

2024-10-16 12:02 UTC, RudraPratik30 commented
Hey @devagn611 if it is difficult to make these many changes in this PR then you can raise a new PR from scratch.

2024-10-16 12:46 UTC, devagn611 commented
Ok @RudraPratik30 
I'll let you know give me time to check the files.

2024-10-17 12:22 UTC, RudraPratik30 commented
Hey @devagn611 please let us know if you are still working on this, also if you raise a new PR then please mention it here so that we can check and keep track, thanks!

2024-10-18 05:34 UTC, PriteshKiri commented
Closing because of lack of progress!

2024-10-18 05:34 UTC, closed without merging