Fixed link.md
ToolJet/ToolJet pull request #11016
Opened 2024-10-17 13:09 UTC by AsifQamar

@RudraPratik30 here the link.md changes

2024-10-18 06:37 UTC, RudraPratik30 requested changes
Hey @AsifQamar, please make the mentioned changes in both versions, also please add full stops wherever needed.

2024-10-18 06:37 UTC, RudraPratik30 commented on docs/docs/widgets/link.md
>  ### Tooltip
Hey @AsifQamar here on line no. 62 you need to change the widget to the component.

2024-10-18 06:37 UTC, RudraPratik30 commented on docs/docs/widgets/link.md
> +| Visibility | Toggle on or off to control the visibility of the widget. You can programmatically change its value by clicking on the **fx** button next to it. If `{{false}}` the component will not v
Here on line no. 88 as well, change the widget to component

2024-10-21 10:35 UTC, RudraPratik30 approved these changes
Hey @AsifQamar, thanks for contributing!
The changes look good to me and forwarding it to the team for final review.
You can expect your PR to be merged by the end of this week, thanks!

2024-10-25 07:48 UTC, johnsoncherian approved these changes

2024-10-25 07:48 UTC, merged

2024-11-04 09:38 UTC, PriteshKiri commented
#10969