Update the documentation for the Color Picker Component
ToolJet/ToolJet pull request #11028
Opened 2024-10-18 16:18 UTC by NohaFahmi

This PR includes the fix for: [https://github.com/ToolJet/ToolJet/issues/11017](https://github.com/ToolJet/ToolJet/issues/11017)

### Formatting updates:

- [x] Replace "Fx" with "fx" wherever applicable. ( i.e. remove the backticks (``) make it lowercase and bold -> fx)

- [x] For each h2 (created using ##), remove 24px padding-bottom. The div that wraps up the h2 headers and the section below the header should only have a "padding-top" of 24px and no "padding-bottom".

### Content updates:

- [x] Replace the word "widget" with "component" wherever applicable. ( Please do not update the URLs )

### Events Tabel

- [x] Remove the description Under the "Events" heading.

- [x] Update the description of the "On change" event - [reference](https://docs.tooljet.com/docs/widgets/text-input/#events) ( Please just check the sentence structure from the given reference )

- [x] Add a divider before the "Styles" section [reference](https://docs.tooljet.com/docs/widgets/textarea#styles)

2024-10-18 16:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11028) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11028) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=11028) it.</sub>

2024-10-21 11:14 UTC, RudraPratik30 requested changes
Hey @nohafahmi, please make the mentioned changes in both versions, thanks!

2024-10-21 11:14 UTC, RudraPratik30 commented on docs/docs/widgets/color-picker.md
> +| On change | Triggers whenever the user types something in the text input.|
Hey @NohaFahmi, you were not supposed to exactly copy the content from the reference but instead, you were expected to reframe this content according to the color picker component, please update this.

2024-10-21 11:14 UTC, RudraPratik30 commented on docs/versioned_docs/version-2.50.0-LTS/widgets/color-picker.md
> +<div style={{paddingTop:'24px'}>
I think there is a syntax error on this line which might break the code, can you please correct it?
You have done this correctly in the Next version, please refer that.

2024-10-21 11:14 UTC, RudraPratik30 commented on docs/docs/widgets/color-picker.md
>  <div style={{paddingTop:'24px', paddingBottom:'24px'}}>
You need to remove the paddingBottom from here.

2024-10-21 11:14 UTC, RudraPratik30 commented on docs/docs/widgets/color-picker.md
> +**Color Picker** component is used to select the desired color from the color picker
Can you please add a full stop at the end of this sentence? Also please add the full stops wherever necessary.

2024-10-22 11:50 UTC, PriteshKiri commented
Hey @NohaFahmi 

Can you please make the changes requested by @RudraPratik30 in the review comments ?

2024-10-23 11:20 UTC, RudraPratik30 commented
Closing the PR due to lack of progress.

2024-10-23 17:48 UTC, closed without merging