Updated the documentation for the Date-Range Picker Component
ToolJet/ToolJet pull request #11020
Opened 2024-10-17 14:20 UTC by rudrakshnalbalwar

🔧 Documentation Update for Date-Range Picker Component 🗓️
This PR addresses several improvements in the date-range-picker.md documentation to enhance readability and consistency. Below is a summary of the changes:

Formatting Updates:

Replaced Fx with fx (bold and lowercase) for consistency 🔄.
Removed padding-bottom: 24px from h2 headers to maintain consistent spacing 🎨.
Content Updates:

Replaced the term "widget" with "component" to align with current terminology across the document 🖥️.
Updated the "On select" event description for better sentence structure and clarity ✍️.
Added missing full stops at the end of descriptions in the Properties and Events tables for better formatting 📑.
Removed unnecessary description under the "Events" heading to streamline the section 🚮.
Added a horizontal divider before the "Styles" section for better visual separation 📏.
Documentation Structure:

Ensured the file adheres to markdown and JSX conventions for proper rendering on the ToolJet platform ✅.

2024-10-17 14:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11020) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11020) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=11020) it.</sub>

2024-10-17 14:23 UTC, rudrakshnalbalwar commented
@PriteshKiri I had made the changes as you mentioned. You can check it and let me know if any change has to be made. Thank you!!

2024-10-18 06:14 UTC, RudraPratik30 requested changes
Hey @rudrakshnalbalwar please make the mentioned changes.

2024-10-18 06:14 UTC, RudraPratik30 commented on docs/versioned_docs/version-2.50.0-LTS/widgets/date-range-picker.md
Hey @rudrakshnalbalwar, here on line no. 43 you need to remove the paddingBottom

2024-10-18 06:14 UTC, RudraPratik30 commented on docs/versioned_docs/version-2.50.0-LTS/widgets/date-range-picker.md
> +| Visibility | This is to control the visibility of the widget. If `{{false}}` the component will not visible after the app is deployed. It can only have boolean values i.e. either `{{true}}` or `{{f
Here you need to update the widget to the component.

2024-10-21 06:52 UTC, rudrakshnalbalwar commented
Hey @PriteshKiri 
I already made the changes requested by @RudraPratik30  can you please review it and let me know if any further change has to be made

2024-10-21 10:15 UTC, RudraPratik30 commented
Hey @rudrakshnalbalwar, thanks for contributing!
The changes look good to me and forwarding it to the team for final review.
You can expect your PR to be merged by the end of this week, thanks again!

2024-10-21 10:33 UTC, RudraPratik30 submitted a review, later dismissed

2024-10-30 08:16 UTC, karan-rathod-316 approved these changes
Looks good to me.

2024-10-30 09:24 UTC, merged