issue #11060
ToolJet/ToolJet pull request #11099
Opened 2024-10-24 06:05 UTC by eyesee11

2024-10-24 06:46 UTC, PriteshKiri commented
Hey @eyesee11,

Thanks for your contribution.

Can you please update the PR name ( add a relevant PR name ) and link your issue to this PR.

2024-10-24 12:14 UTC, RudraPratik30 requested changes
Hey @eyesee11 please make the mentioned changes in both versions, thanks!

2024-10-24 12:14 UTC, RudraPratik30 commented on docs/docs/widgets/checkbox.md
> +
Hey, you are not supposed to edit this section, can you please revert the changes from this section?

2024-10-24 12:14 UTC, RudraPratik30 commented on docs/docs/widgets/checkbox.md
> +| Label          | The text to be used as the label for the checkbox.          | String (e.g., **Select payment preference**).                 |
You have to remove backticks from fx only and rest of the backticks should be untouched, please make this change wherever necessary.

2024-10-24 12:14 UTC, RudraPratik30 commented on docs/docs/widgets/checkbox.md
> +| On change | The on change event is triggered when the checkbox input is changed. |
You need to update the content of this table referring to the reference given to you in the issue, you don't need to exactly copy from the reference but you have to frame the sentence in a similar way.

2024-10-24 12:14 UTC, RudraPratik30 commented on docs/docs/widgets/checkbox.md
> +---
Can you please remove this? we don't need a divider at the end of the doc

2024-10-24 12:17 UTC, eyesee11 commented
Hey Pratik!!
I'm really sorry for the inconvenience
Sure I'll adhere to those mentioned
I just need to ask if I have to make a new PR for both the files again or
just for this file.

On Thu, 24 Oct, 2024, 17:44 Pratik Agrawal, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey @eyesee11 <https://github.com/eyesee11> please make the mentioned
> changes in both versions, thanks!
> ------------------------------
>
> In docs/docs/widgets/checkbox.md
> <https://github.com/ToolJet/ToolJet/pull/11099#discussion_r1814852241>:
>
> > @@ -1,129 +1,133 @@
>  ---
> -id: checkbox
> -title: Checkbox
> ----
> +
>
> Hey, you are not supposed to edit this section, can you please revert the
> changes from this section?
> ------------------------------
>
> In docs/docs/widgets/checkbox.md
> <https://github.com/ToolJet/ToolJet/pull/11099#discussion_r1814853767>:
>
> >
>  ## Properties
>
>  ### Data
>
>  | Property       | Description    | Expected Value         |
>  |:---------------|:---------------|:-----------------------|
> -| Label          | The text to be used as the label for the checkbox.          | String (e.g., `Select payment preference`).                 |
> -| Default status | Sets the default status when the app is loaded.                | Toggle the on/off switch or click on `fx` and dynamically set the value. |
> +| Label          | The text to be used as the label for the checkbox.          | String (e.g., **Select payment preference**).                 |
>
> You have to remove backticks from fx only and rest of the backticks should
> be untouched, please make this change wherever necessary.
> ------------------------------
>
> In docs/docs/widgets/checkbox.md
> <https://github.com/ToolJet/ToolJet/pull/11099#discussion_r1814856195>:
>
> >
>  ## Events
>
>  | <div style={{ width:"100px"}}> Event </div>     | <div style={{ width:"100px"}}> Description </div> |
>  |:----------- |:----------- |
> -| On change | On change event is triggered when checkbox input is changed. |
> -| On check (deprecated) | On check event is triggered when checkbox input is checked. |
> -| On uncheck (deprecated)| On uncheck event is triggered when checkbox input is unchecked. |
> +| On change | The on change event is triggered when the checkbox input is changed. |
>
> You need to update the content of this table referring to the reference
> given to you in the issue, you don't need to exactly copy from the
> reference but you have to frame the sentence in a similar way.
> ------------------------------
>
> In docs/docs/widgets/checkbox.md
> <https://github.com/ToolJet/ToolJet/pull/11099#discussion_r1814857907>:
>
> >
>  </div>
>
> -
> +---
>
> Can you please remove this? we don't need a divider at the end of the doc
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ToolJet/ToolJet/pull/11099#pullrequestreview-2392280865>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7QD2YF2RJIE3QBC6NYDOGTZ5DQDXAVCNFSM6AAAAABQQJMID2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGOJSGI4DAOBWGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-24 17:33 UTC, PriteshKiri commented
Hey @eyesee11,

You can update the same PR.

2024-10-30 08:06 UTC, closed without merging

2024-10-30 08:06 UTC, PriteshKiri commented
Closing the PR due to lack of progress.