Successfully Updated the documentation for the Circular Progressbar Component
ToolJet/ToolJet pull request #11091
Opened 2024-10-23 14:08 UTC by DeepanshuYadav-code

2024-10-23 14:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11091) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11091) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=11091) it.</sub>

2024-10-24 12:19 UTC, RudraPratik30 requested changes
Hey @DeepanshuYadav-codes please make the mentioned changes in both versions, thanks!

2024-10-24 12:19 UTC, RudraPratik30 commented on docs/docs/widgets/circular-progressbar.md
Hey @DeepanshuYadav-code you need to add a divider before the style section.

2024-10-25 07:45 UTC, DeepanshuYadav-code commented
hey @RudraPratik30, thanks for the timely review. I have add the divider before the styles section.

2024-10-27 08:32 UTC, RudraPratik30 approved these changes
Hey @DeepanshuYadav-code, thanks for contributing!
The changes look good to me and forwarding it to the team for final review.
You can expect your PR to be merged soon.

2024-10-30 08:26 UTC, karan-rathod-316 approved these changes
Looks good to me.

2024-10-30 09:25 UTC, merged