docs: Update text widget documentation formatting and table styling
ToolJet/ToolJet pull request #11139
Opened 2024-10-26 16:34 UTC by OoONANCY

Fixes #11059

This PR updates the Text widget documentation with the following changes:

1. Formatting Updates:
   - Replaced all instances of `fx` with **fx** to maintain consistent styling
   - Made the text lowercase and bold as per requirements

2. Content Structure Changes in Devices Section:
   - Converted text content to table format matching Additional Actions section styling
   - Added proper div styling for column headers:
     ```
     | <div style={{ width:"100px"}}> Action </div> | <div style={{ width:"150px"}}> Description </div> | <div style={{ width:"250px"}}> Configuration Options </div>|
     ```
   - Ensured all sentences in Description column end with a full stop

Files modified:
- docs/docs/widgets/text.md
- docs/versioned_docs/version-2.50.0-LTS/widgets/text.md

---
I have tested the changes locally and verified that the documentation renders correctly.

2024-10-26 16:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11139) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11139) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=11139) it.</sub>

2024-10-27 08:50 UTC, RudraPratik30 requested changes
Hey @OoONANCY can you please make the mentioned changes in both versions?

2024-10-27 08:50 UTC, RudraPratik30 commented on docs/docs/widgets/text.md
> +| Show on desktop | Makes the component visible in desktop view. You can set it with the toggle button or dynamically configure the value by clicking on **fx** and entering a logical expression. |
Hey, can you please check this once again?
I guess there are only 2 columns in this row, while 3 columns were required.

2024-10-27 08:50 UTC, RudraPratik30 commented on docs/docs/widgets/text.md
> +| Size         | Dimensions of the characters in a font. | Enter any number between `1-100` or dynamically configure it using **fx** |
can you please add full stops at the end of these sentences, also wherever applicable in the doc?

2024-10-29 06:10 UTC, PriteshKiri commented
Hey @OoONANCY,

Any updates on the review comments? Please let me know if you are facing issues

2024-10-30 07:59 UTC, closed without merging

2024-10-30 07:59 UTC, PriteshKiri commented
Closing the PR due to lack of progress.