Updated SVG Image documentation with layout and style changes
ToolJet/ToolJet pull request #11144
Opened 2024-10-27 08:05 UTC by vroomvee

I have updated the content according to the requirements mentioned in the issue. I am a beginner and this is my first open-source contribution ever, I hope you excuse my mistakes made inadvertently, if any. Looking forward to some feedback and tips as well. Thank you for this opportunity!

2024-10-27 08:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11144) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11144) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=11144) it.</sub>

2024-10-29 06:01 UTC, PriteshKiri commented
Solves #11116

2024-10-29 12:06 UTC, RudraPratik30 commented
Hey @vroomvee, thanks for contributing!
As per the issue, you were supposed to make changes in two versions (Next and LTS). But I can see you have only edited the LTS version, can you please edit the Next version as well? 
Please refer the [issue](https://github.com/ToolJet/ToolJet/issues/11116) for file path.
You can push the changes in same PR.

2024-10-30 07:44 UTC, PriteshKiri commented
Hey @vroomvee 

Can you please check the comment by @RudraPratik30 and make the changes in the same PR?

2024-10-30 07:46 UTC, vroomvee commented
> Hey @vroomvee
> 
> Can you please check the comment by @RudraPratik30 and make the changes in the same PR?

Yes, on it right now!

2024-10-30 08:24 UTC, RudraPratik30 commented on docs/docs/widgets/svg-image.md
> +| Show on desktop | Makes the component visible in desktop view. | You can set it with the toggle button or dynamically configure the value by clicking on fx and entering a logical expression. |
Hey @vroomve fx should be in bold, can you please update this in both rows and both versions?

2024-10-30 08:26 UTC, RudraPratik30 commented on docs/docs/widgets/svg-image.md
> +| Visibility | Controls component visibility. Toggle or set dynamically. | Enable/disable the toggle button or dynamically configure the value by clicking on fx and entering a logical expression. |
Here as well, the fx needs to be in bold

2024-10-30 08:26 UTC, vroomvee commented
@RudraPratik30 is everything good now? i pushed changes in the Next version as well.

2024-10-30 11:12 UTC, RudraPratik30 requested changes
Hey @vroomvee can you please just delete that file? Rest of the changes look good to me!

2024-10-30 11:12 UTC, RudraPratik30 commented on svg-image.md
I think you created this file by mistake, can you please delete it?

2024-10-30 16:18 UTC, vroomvee commented on svg-image.md
oh gosh yes okay, im sorry im still figuring all this out!

2024-10-31 05:22 UTC, RudraPratik30 approved these changes
Hey @vroomvee, thanks for contributing!
The changes look good to me and forwarding it to the team for final review.

2024-10-31 07:25 UTC, karan-rathod-316 approved these changes
Looks good to me!

2024-10-31 07:33 UTC, adishM98 approved these changes

2024-10-31 07:33 UTC, merged