[docs]: Fix documentation for Tree Select Component
ToolJet/ToolJet pull request #11166
Opened 2024-10-29 09:54 UTC by hahaanisha

**Description**

1. Formatting Updates:

- Replaced "Fx" with fx (lowercase, bold) throughout the documentation.
- Removed padding-bottom: 24px from the div elements wrapping h2 headers; retained padding-top: 24px.

2. Content Updates:

- Replaced the term "widget" with "component" where applicable (URLs remain unchanged).
- Added a divider before the "Styles" section.

3. Files Updated:

- Next - ToolJet/docs/docs/widgets/tree-select.md
- Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/tree-select.md

will close #11058

2024-10-29 09:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11166) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11166) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=11166) it.</sub>

2024-10-29 11:50 UTC, RudraPratik30 requested changes
Hey @hahaanisha please make the mentioned changes in both versions.
Thanks!

2024-10-29 11:50 UTC, RudraPratik30 commented on docs/docs/widgets/tree-select.md
> +<div style={{padding-top:'24px'}}>
Hey @hahaanisha, you have to use `paddingTop` only and not `padding-top`, please update this wherever necessary.

2024-10-29 15:25 UTC, hahaanisha commented
Hello @RudraPratik30 
I have made the  required changes. Can you please review it?

2024-10-30 08:03 UTC, PriteshKiri commented
Hey @hahaanisha,

Thanks for your contribution.  Can you please sign the CLA?

2024-10-30 08:11 UTC, hahaanisha commented
Hey @PriteshKiri 
I have already signed the CLA yesterday, still its showing not signed on github. I have tried multiple times, but its not reflecting on github. I have attached the screenshot below. 
![Screenshot 2024-10-30 133838](https://github.com/user-attachments/assets/3259f55f-8e49-4783-8304-432165b69927)

2024-10-30 17:42 UTC, RudraPratik30 approved these changes
Hey @hahaanisha, thanks for contributing!
The changes look good to me and forwarding it to the team for final review!

2024-10-31 07:23 UTC, karan-rathod-316 approved these changes
Looks good to me.

2024-10-31 07:32 UTC, adishM98 approved these changes

2024-10-31 07:32 UTC, merged