[docs]: Updated Icon Component Documentation.
ToolJet/ToolJet pull request #11176
Opened 2024-10-29 18:10 UTC by niranjan-kurhade

This PR fixes #11168 
Screenshots of the changes made are attached- 
1) CSA Table-
![image](https://github.com/user-attachments/assets/e8964603-be57-4126-9642-3fa0fdb2d27b)
2) Layout Table
![image](https://github.com/user-attachments/assets/60bf54dd-19be-4244-89be-ba0a5b9e8050)

2024-10-29 18:12 UTC, niranjan-kurhade commented
Hey @PriteshKiri, please review the PR

2024-10-30 06:27 UTC, PriteshKiri commented
Hey @niranjan-kurhade,

Thanks for the contribution.

Can you please update the "Devices" table as per the given reference? Please make sure you update both the files.

2024-10-30 09:50 UTC, niranjan-kurhade commented
> Hey @niranjan-kurhade,
> 
> Thanks for the contribution.
> 
> Can you please update the "Devices" table as per the given reference? Please make sure you update both the files.

Hey, I have made the changes, Can you please check if they are correct?

2024-10-30 11:22 UTC, RudraPratik30 requested changes
Hey @niranjan-kurhade, please make the mentioned changes in both the versions, thanks!

2024-10-30 11:22 UTC, RudraPratik30 commented on docs/versioned_docs/version-2.10.0/widgets/icon.md
>  | Actions     | Description |
Hey @niranjan-kurhade, here you need to add the "How To Access" column and then update the content accordingly.

2024-10-30 11:22 UTC, RudraPratik30 commented on docs/versioned_docs/version-2.50.0-LTS/widgets/icon.md
> +| setVisibility()                                 | Toggles the visibility of the Icon component. | Employ a RunJS query (for e.g., `await components.icon1.setVisibility(false))` or trigger it using
In the description column, please use "Sets the visibility of the component." instead of "Toggles the visibility of the Icon component."

2024-10-30 13:27 UTC, niranjan-kurhade commented
> Hey @niranjan-kurhade, please make the mentioned changes in both the versions, thanks!

Can you check if the changes are correct?

2024-10-31 05:36 UTC, RudraPratik30 requested changes
Hey @niranjan-kurhade, I just noticed that you have made changes in wrong file.
As per the issue, you have to update the Next and LTS version only, but I think by mistake you have made changes in 2..10.0 version, can you please revert all the changes from this particular file and make the changes in correct file?

Refer the following file paths:
- Next - ToolJet/docs/docs/widgets/icon.md
- Version 2.50.0 (LTS) - ToolJet/docs/versioned_docs/version-2.50.0-LTS/widgets/icon.md

2024-11-07 05:55 UTC, RudraPratik30 commented
Closing the PR due to inactivity.

2024-11-07 05:55 UTC, closed without merging