Ce local data source/platform
ToolJet/ToolJet pull request #11344
Opened 2024-11-15 13:02 UTC by rohanlahori

2024-11-15 13:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11344) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11344) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=11344) it.</sub>

2024-11-19 09:09 UTC, shah21 requested changes
@rohanlahori I have added some comments. Please take a look.

2024-11-19 09:09 UTC, shah21 commented on frontend/src/AppBuilder/QueryManager/Components/QueryManagerBody.jsx
> +      selectedDataSource?.kind !== 'runjs' &&
```suggestion
      const staticDataSources = ['runjs', 'runpy', 'tooljetdb'];
      // use this check instead
      !staticDatasources.includes(selectedDataSource?.kind) &&
```

2024-11-19 09:09 UTC, shah21 commented on frontend/src/AppBuilder/QueryManager/Components/QueryManagerBody.jsx
> +            <NotificationBanner />
Does support dark mode styles automatically? If yes, please add the dark mode variable inside the component itself or pass value from the referenced files.

2024-11-19 11:02 UTC, rohanlahori reviewed
fixed

2024-11-19 11:54 UTC, shah21 approved these changes

2024-11-20 09:28 UTC, merged