[docs]: Add Guide on How to Display Listview Record on a New Page
ToolJet/ToolJet pull request #11362
Opened 2024-11-19 09:58 UTC by RudraPratik30

Added a new guide on how-to display listview record on a new page, only in 3.1.0-Beta version

`/how-to/display-listview-record-on-new-page`

2024-12-04 05:09 UTC, karan-rathod-316 requested changes
1. `from the bottom query panel.` - This sounds very awkward.

2. click on your listview component - Formatting and tone issues. It should be `click on the **Listview** component`

3. `select operation as **list rows**` - Casing issue for List rows operation

4. This can be achieved without running 2 queries. Update the guide accordingly.

5. Improve the UI of the app in the screenshots

2024-12-04 10:27 UTC, RudraPratik30 commented
@karan-rathod-316 updated

2025-01-07 09:15 UTC, karan-rathod-316 requested changes
Please make the relevant changes as discussed on call.

2025-02-03 05:40 UTC, adishM98 approved these changes

2025-02-03 05:41 UTC, adishM98 approved these changes

2025-02-03 05:41 UTC, karan-rathod-316 approved these changes
Looks good to me.

2025-02-03 05:41 UTC, merged