feat: Qdrant plugin
ToolJet/ToolJet pull request #11547
Opened 2024-12-09 07:26 UTC by Anush008

## Description

This PR adds a new plugin to interface with Qdrant - https://qdrant.tech/

## NOTE

I'll be moving this plugin to `marketplace/plugins`. Currently it is at `plugins/` because I found it faster to iterate from there.

2024-12-09 07:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11547) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=11547) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=11547) it.</sub>

2024-12-30 07:31 UTC, mansukh-tj commented
@Anush008 thanks for this contribution. Upon reviewing this plugin, we noticed that error handling is something that can be improved. Please refer to this [documentation](https://docs.tooljet.com/docs/contributing-guide/marketplace/creating-a-plugin/#step-6-add-error-handling) to refine this aspect. Let us know if our input is required somewhere.

2025-01-02 20:42 UTC, Anush008 commented
Refactored with https://github.com/ToolJet/ToolJet/pull/11547/commits/ec8f28d11c8f7e914e1d18733c6c3416cb8dac31.

2025-01-13 15:37 UTC, Anush008 commented
Hey @mansukh-tj. Just bumping this PR.
Please take a look when possible.

2025-01-17 05:45 UTC, akshaysasidrn requested changes
Can you please make these small correction?
Looks good otherwise!

2025-01-17 05:45 UTC, akshaysasidrn commented on server/src/assets/marketplace/plugins.json
> +    "name": "qdrant",
Please capitalize

2025-01-17 05:45 UTC, akshaysasidrn commented on server/src/assets/marketplace/plugins.json
> +    "description": "api plugin from qdrant",
API plugin from Qdrant

2025-01-17 06:49 UTC, akshaysasidrn submitted a review, later dismissed

2025-01-20 07:10 UTC, akshaysasidrn approved these changes

2025-01-20 07:10 UTC, merged