fix: Incorrect placement for delete button on text input
ToolJet/ToolJet pull request #1479
Opened 2021-12-01 13:22 UTC by singh-vikas-m

fix for issue - https://github.com/ToolJet/ToolJet/issues/1417

The issue is with not having the default min-width of the ConfigHandle.jsx.
Added changes to theme.css now work with all small widgets.

2021-12-01 13:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=1479) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=1479) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=1479) it.</sub>

2021-12-02 08:15 UTC, arpitnath requested changes
Would you please revert the changes and use the recommended linter setup?

2021-12-02 10:01 UTC, singh-vikas-m commented
Sure !

2021-12-23 17:01 UTC, Navaneeth-pk commented
Closing a there is no update.

2021-12-23 17:01 UTC, closed without merging