Bugfix: Scrolling is broken for code editor on postgresql query manager
ToolJet/ToolJet pull request #1583
Opened 2021-12-15 15:21 UTC by arpitnath

Fixes #1546 

**Loom**: https://www.loom.com/share/184d43381df046dca3d8089efe120612

2021-12-17 05:13 UTC, gondar00 requested changes
Let's use className istead of isScrollable

2021-12-17 05:13 UTC, gondar00 commented on frontend/src/Editor/CodeBuilder/CodeHinter.jsx
> +  isScrollable = false,
```suggestion
  className = 'code-hinter,
```

2021-12-17 05:13 UTC, gondar00 commented on frontend/src/Editor/QueryManager/QueryEditors/Postgresql.schema.json
> +        "isScrollable": true
```suggestion
        "className": ""
```

2021-12-20 06:47 UTC, sherfin94 submitted a review, later dismissed

2021-12-22 07:06 UTC, gondar00 approved these changes

2021-12-25 03:21 UTC, merged