[Feature] file parser option for FilePicker widget
ToolJet/ToolJet pull request #1764
Opened 2022-01-08 15:42 UTC by arpitnath

2022-01-10 08:19 UTC, arpitnath commented
NOTE: just included `PDF`  option for testing, will remove that

2022-01-10 08:23 UTC, gondar00 requested changes

2022-01-10 08:23 UTC, gondar00 commented on frontend/src/Editor/Components/FilePicker.jsx
> +    const autoDetectFileType = fileTypeFromExtension === 'auto-detect' ? true : false;
```suggestion
    const autoDetectFileType = fileTypeFromExtension === 'auto-detect';
```

2022-01-10 08:23 UTC, gondar00 commented on frontend/src/Editor/Components/FilePicker.jsx
> +  return newArray;
probably can add a try catch here to handle bad data in csv

2022-01-10 09:06 UTC, gondar00 submitted a review, later dismissed

2022-01-12 08:43 UTC, sherfin94 requested changes
@arpitnath It works awesome!. Can we also add an `isParsing` property so that I can show loading icon on table when the file is still being processed?

2022-01-14 01:36 UTC, arpitnath commented
> @arpitnath It works awesome!. Can we also add an `isParsing` property so that I can show loading icon on table when the file is still being processed?

Yeah sure 😎

2022-01-21 11:06 UTC, Navaneeth-pk approved these changes

2022-01-22 05:15 UTC, merged