Adds support for custom variables
ToolJet/ToolJet pull request #1780
Opened 2022-01-10 11:14 UTC by arpitnath

Resolves #1779

2022-01-12 02:55 UTC, Navaneeth-pk submitted a review, later dismissed

2022-01-12 06:18 UTC, sherfin94 requested changes
@arpitnath Code looks great but I couldn't get it working as I expected. I'm not able to access  the value in another component. Also, the code hinter shows erroneous hints. And the code preview is not resolving it either. Please check.

https://user-images.githubusercontent.com/20333972/149074350-741a1ef3-39e1-4bd9-b8de-91fff46627cf.mov

2022-01-14 01:35 UTC, arpitnath commented
Sorry, looks like I missed this notification, will look into it today for sure @sherfin94

2022-01-24 00:43 UTC, arpitnath commented
@sherfin94 resolved merge conflicts

2022-01-30 23:09 UTC, sherfin94 approved these changes

2022-01-31 03:36 UTC, merged