added dark theme to querymanager dropdown lists
ToolJet/ToolJet pull request #1839
Opened 2022-01-16 01:26 UTC by karlrez

Resolves #1745 

No changes to functionality, just added dark theme.

Datasource dropdown:
![image](https://user-images.githubusercontent.com/47090434/149643706-47d5a48c-7dc1-46bd-988d-cccd537900ba.png)
![image](https://user-images.githubusercontent.com/47090434/149643709-50f8d7af-a18e-4303-8ce5-6a32e343e8ec.png)

Operation dropdown:
![image](https://user-images.githubusercontent.com/47090434/149643758-57e0818e-362b-4eb5-816f-6a69857b12e4.png)
![image](https://user-images.githubusercontent.com/47090434/149643777-450e0308-f6c7-4704-b7be-99e0d1a6e997.png)

2022-01-16 04:53 UTC, karlrez commented
Pushed again as I noticed the width of the Operation dropdown did not match light mode. This is fixed now:

![image](https://user-images.githubusercontent.com/47090434/149647727-c46dc8be-4636-461a-9d00-7883b4ce5f3e.png)


I did add quite a bit to the theme.scss file. Would you prefer if I added a seperate file for the styling? Let me know of any suggestions.

2022-01-17 03:36 UTC, Navaneeth-pk commented
@arpitnath can you please review this PR?

2022-01-18 09:24 UTC, arpitnath commented
@karlrez 
Here the svgs are inverted and some of the icons are not legible for a user to understand.
Since we can rename the datasources, proper visibility of the icons is necessary.
But yes we need to update the background accordingly to the theme.
<img width="648" alt="Screenshot 2022-01-18 at 2 12 34 AM" src="https://user-images.githubusercontent.com/67645175/149908294-f40dbce4-ef9c-4487-956c-759db02a2631.png">

Can you please revert the changes for the icons for now and we are good to go 😅

2022-01-18 09:25 UTC, arpitnath requested changes

2022-01-18 09:25 UTC, arpitnath commented on frontend/src/_styles/theme.scss
> +/**
Also can you remove the unused commented parts

2022-01-19 03:42 UTC, karlrez commented
Hi @arpitnath, thank you for your review and suggestions, I've just pushed my updates.

I agree, icons look better this way:
![image](https://user-images.githubusercontent.com/47090434/150059890-ed8e5bd7-3186-45d3-9385-5067e5ddbe89.png)

2022-01-20 04:40 UTC, Navaneeth-pk approved these changes

2022-01-20 04:41 UTC, merged