[Bugfix] Typing  "this"  or  "window" or "app"  on any code box will crash the app completely
ToolJet/ToolJet pull request #1998
Opened 2022-01-28 11:52 UTC by arpitnath

Fixes #1997 

trying to display a circular structure in a JSON like a format in the previewBox was causing the crash.

### Screencas

https://user-images.githubusercontent.com/67645175/151542375-17ef1bef-78d4-4d26-aeb2-5c2d03784078.mov

t

2022-02-03 10:00 UTC, sherfin94 commented
It is working, but I think we use https://www.npmjs.com/package/flatted to stringify object from code preview.

I remember using `JSON.parse(JSON.stringify(someObj))` in the sidebar inspector as well, please try converting that to `Flatted.parse(Flatted.stringify(someObj))` as well, so that we can avoid the same crash occurring there as well.

2022-02-03 10:01 UTC, sherfin94 requested changes
I've suggested an experiment

2022-02-05 06:25 UTC, gondar00 approved these changes

2022-02-15 06:47 UTC, sherfin94 approved these changes

2022-02-15 06:49 UTC, merged