[Bugfix] stripe query selection dropdown menu should display the selected component value on saving the query
ToolJet/ToolJet pull request #2106
Opened 2022-02-02 20:56 UTC by arpitnath

Fixes #2104 

### Loom

2022-02-25 09:48 UTC, gondar00 requested changes

2022-02-25 09:48 UTC, gondar00 commented on frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
> +    };
```suggestion
    const newOptions = JSON.parse(JSON.stringify(options));
    options[paramName].= undefined;
```

2022-04-06 09:18 UTC, gondar00 requested changes

2022-04-06 09:18 UTC, gondar00 commented on frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
> +    options[paramName] = undefined;
I think this should be `newOptions` ?
```suggestion
    newOptions[paramName] = undefined;
```

2022-04-06 09:18 UTC, gondar00 commented on frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
> +    const newOptions = JSON.parse(JSON.stringify(options));
nit
```suggestion
    const newOptions = JSON.parse(JSON.stringify(this.state.options));
```

2022-04-06 09:18 UTC, gondar00 commented on frontend/src/Editor/QueryManager/QueryEditors/Stripe.jsx
> +    this.props.optionsChanged(newOptions);
nit
```suggestion
    this.setState({
      options: newOptions,
    }, () => {
      this.props.optionsChanged(newOptions);
    });
```

2022-04-06 12:59 UTC, gondar00 submitted a review, later dismissed

2022-04-14 10:52 UTC, arpitnath commented
Todo: Refactor

2022-04-19 10:55 UTC, sherfin94 approved these changes

2022-04-19 10:56 UTC, merged