Integration couch
ToolJet/ToolJet pull request #2337
Opened 2022-02-24 05:02 UTC by stepinfwd

2022-02-28 07:51 UTC, akshaysasidrn requested changes

2022-02-28 07:51 UTC, akshaysasidrn commented on docs/docs/data-sources/couchdb.md
> +## Connection
Please update documentation here

2022-02-28 07:51 UTC, akshaysasidrn commented on plugins/packages/couchdb/lib/index.ts
> +// const NodeCouchDb = require('node-couchdb');
can remove if not used

2022-02-28 11:21 UTC, gsmithun4 requested changes

2022-02-28 11:21 UTC, gsmithun4 commented on plugins/packages/couchdb/lib/index.ts
> +    // const couch = new NodeCouchDb();
Remove commented codes

2022-02-28 11:21 UTC, gsmithun4 commented on plugins/packages/couchdb/lib/index.ts
> +    // return couchAuth;
Should we return something?

2022-02-28 11:21 UTC, gsmithun4 commented on plugins/packages/couchdb/lib/manifest.json
> +        "type": "string"
option types are not used anymore, but should keep the encryption issue, 
```
"options": {
   "password": {
     "encrypted": true
   },
}
```
this is enough

2022-02-28 11:21 UTC, gsmithun4 commented on plugins/packages/couchdb/lib/index.ts
> +              records: JSON.parse(queryOptions.body),
will be good if we use [JSON5](https://json5.org/) to parse user entered json string

2022-02-28 19:45 UTC, gsmithun4 requested changes

2022-02-28 19:45 UTC, gsmithun4 commented on plugins/packages/couchdb/lib/index.ts
> +          result = JSON5.parse(response.body);
No need to parse response using `json5` parse user inputs like `queryOptions.body`. Create a private function to parse json
refer https://github.com/ToolJet/ToolJet/blob/develop/plugins/packages/bigquery/lib/index.ts

2022-03-01 05:57 UTC, gsmithun4 submitted a review, later dismissed
LGTM

2022-03-07 04:49 UTC, stepinfwd commented
> @stepinfwd @gsmithun4 The `List records` query seems to be returning the documents in this format described in their documentation: <img alt="image" width="363" src="https://user-images.githubusercontent.com/20333972/156326749-358f03c2-7400-45bf-923b-3a759750dfcc.png">
> 
> It is not returning any additional data that I attach while creating record using the `create record` operation or from the dashboard. That is, it is returning the document that I create, but it is not returning any data that I attach to the document, other than the reserved fields like `id`, `key` and `value`(inside which there is only `rev`).
> 
> I'm not exactly sure if this is an issue or if it is indeed the behaviour this operation is supposed to work.



> @stepinfwd @gsmithun4 The `List records` query seems to be returning the documents in this format described in their documentation: <img alt="image" width="363" src="https://user-images.githubusercontent.com/20333972/156326749-358f03c2-7400-45bf-923b-3a759750dfcc.png">
> 
> It is not returning any additional data that I attach while creating record using the `create record` operation or from the dashboard. That is, it is returning the document that I create, but it is not returning any data that I attach to the document, other than the reserved fields like `id`, `key` and `value`(inside which there is only `rev`).
> 
> I'm not exactly sure if this is an issue or if it is indeed the behaviour this operation is supposed to work.

https://pouchdb.com/api.html#batch_fetch
pouchDB is similar to couchDB alldocs does not returning any attachments inherently ,also its not mentioned in docs of couchDB.in pouchDB docs a key "include_docs" is mentioned to return the attachments its working for couchDB too (default is false).

or we can use  this for getting attachments : https://docs.couchdb.org/en/3.2.0/api/database/bulk-api.html#db-design-docs

2022-03-10 12:51 UTC, sherfin94 approved these changes

2022-03-10 12:54 UTC, merged