Bugfix ::  Fixing alignment of FX button
ToolJet/ToolJet pull request #2438
Opened 2022-03-07 07:31 UTC by stepinfwd

resolves #2410

2022-03-14 10:19 UTC, sherfin94 commented
Please fix this alignment issue, otherwise everything looks fine.

<img width="216" alt="image" src="https://user-images.githubusercontent.com/20333972/158150195-91ccba5d-ea8b-486d-b3a8-4cea9b3b690f.png">

2022-03-14 10:20 UTC, sherfin94 requested changes
Alignment issue I've mentioned.

2022-03-14 19:26 UTC, stepinfwd commented
> Please fix this alignment issue, otherwise everything looks fine.
> 
> <img alt="image" width="216" src="https://user-images.githubusercontent.com/20333972/158150195-91ccba5d-ea8b-486d-b3a8-4cea9b3b690f.png">

updated

2022-03-31 09:44 UTC, sherfin94 approved these changes

2022-03-31 09:44 UTC, merged