[UI improvement] :: Datasource selector in query manager updated from dropdown to cards
ToolJet/ToolJet pull request #2469
Opened 2022-03-09 10:59 UTC by stepinfwd

resolves #2468

2022-03-14 10:43 UTC, sherfin94 commented
Clicking on `+` icon when a new query screen is already opened, sends the panel to a blank state with only a `<-` character.

https://user-images.githubusercontent.com/20333972/158156573-a95b3ab9-6c6c-412e-8ce0-aec544220b10.mov

2022-03-14 10:45 UTC, sherfin94 commented
`General`, `Advanced`, `Preview` , `Save` etc still exists when `+` button is clicked. They are irrelevant while selecting a query type.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/20333972/158156754-f3f5a8b4-364c-4b85-bdf7-f9d5da37be7a.png">

2022-03-14 10:50 UTC, sherfin94 requested changes
Mentioned the changes required on the other comments.

2022-03-18 04:57 UTC, Navaneeth-pk approved these changes

2022-03-18 04:57 UTC, merged