fix: set `exposedVariables.value` to "" for TextArea components fixes Issue: #2454
ToolJet/ToolJet pull request #2486
Opened 2022-03-10 16:38 UTC by KaviiSuri

This PR fixes #2454 by settings the exposedVariables.value for TextArea to an empty string.

2022-03-10 16:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=2486) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=2486) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=2486) it.</sub>

2022-03-10 19:41 UTC, sherfin94 requested changes
Hey @KaviiSuri , your change unfortunately does not resolve the issue. When a TextArea is dragged in, it still is empty instead of showing the default value.

My suggestion is to change the default value of the exposed variable `value` to ```'ToolJet is an open-source low-code platform for building and deploying internal tools with minimal engineering efforts 🚀'``` instead of `""`

2022-03-11 07:01 UTC, KaviiSuri commented
Hey @sherfin94 , thanks for the correction,
I've implemented it.

2022-03-13 09:23 UTC, Navaneeth-pk commented
@KaviiSuri please revert the changes to package and package lock files.

2022-03-13 18:35 UTC, Navaneeth-pk approved these changes

2022-03-13 18:36 UTC, merged