Feature :: influxDB integration
ToolJet/ToolJet pull request #2590
Opened 2022-03-21 10:26 UTC by stepinfwd

resolves #2564

2022-03-21 18:19 UTC, gsmithun4 requested changes

2022-03-21 18:19 UTC, gsmithun4 commented on plugins/packages/influxdb/lib/index.ts
> +          result = JSON.parse(response.body);
Use `this.parseJSON`

2022-03-21 18:19 UTC, gsmithun4 commented on plugins/packages/influxdb/lib/manifest.json
> +    "options": {
`type` is not required in `options`
```
      "api_token": {
        "encrypted": true
      },
```
This is enough

2022-03-21 18:19 UTC, gsmithun4 commented on plugins/packages/oracledb/package.json
> -    "@types/oracledb": "^5.2.2"
Please revert the other plugin changes, if required add it in separate PR

2022-03-22 18:01 UTC, gsmithun4 commented on plugins/packages/influxdb/lib/manifest.json
> +      "port": {
You can remove `port`, `host` and `protocol`

2022-03-22 18:03 UTC, gsmithun4 commented on docs/yarn.lock
>  # yarn lockfile v1
Are these changes expected?

2022-03-23 05:02 UTC, gsmithun4 approved these changes

2022-03-23 09:20 UTC, Navaneeth-pk approved these changes

2022-03-23 09:29 UTC, merged