Feature/update timer behaviour
ToolJet/ToolJet pull request #2597
Opened 2022-03-21 21:12 UTC by felipeTht

Resolves #2549 

Update che json on component.js for **Timer**, I added a new prop under:

definition: {
   ...,
   defaults: [
        {
          type: _selectValue_,
          value: _defaultValue_
          paramName: _nameOfTheValue,_
        },
}.

The default values work for all select changes that has a defaults value under the component definition.

2022-03-27 13:51 UTC, arpitnath requested changes
@felipeTht Please revert the changes which are not related to this issue.
It will be great if you can follow the repo's eslint rules, it's easier to review 😅

2022-04-02 15:19 UTC, felipeTht commented
> 

I'm sorry it was setted the default auto saving with prettier conf. I pushed the file reverted.

2022-04-02 16:54 UTC, gsmithun4 reviewed
Timer changes looks good, @arpitnath please take a look into components and inspector

2022-04-07 07:16 UTC, arpitnath approved these changes

2022-04-07 10:45 UTC, merged