[ enhancement ] :: added on select event
ToolJet/ToolJet pull request #2707
Opened 2022-04-01 11:14 UTC by stepinfwd

resoves #2705

2022-04-18 17:56 UTC, sherfin94 approved these changes

2022-04-18 17:57 UTC, sherfin94 requested changes
Works great. Could you add this on the documentation as well?

2022-04-21 09:51 UTC, stepinfwd commented
> Works great. Could you add this on the documentation as well?



> Works great. Could you add this on the documentation as well?

updated

2022-04-21 09:51 UTC, stepinfwd commented
> Works great. Could you add this on the documentation as well?



> Works great. Could you add this on the documentation as well?

updated

2022-04-21 10:01 UTC, sherfin94 approved these changes

2022-04-21 10:01 UTC, merged