Feature: OpenApi plugin
ToolJet/ToolJet pull request #2728
Opened 2022-04-04 07:53 UTC by shah21

2022-04-18 12:26 UTC, gsmithun4 requested changes

2022-04-18 12:26 UTC, gsmithun4 commented on plugins/packages/openapi/lib/index.ts
> +  async fetchOAuthToken(sourceOptions: any, code: string): Promise<any> {
add `private` access modifier

2022-04-18 12:26 UTC, gsmithun4 commented on plugins/packages/openapi/lib/index.ts
> +  fetchHttpsCertsForCustomCA() {
add `private` access modifier

2022-04-18 12:26 UTC, gsmithun4 commented on plugins/packages/openapi/lib/index.ts
> +  checkIfContentTypeIsURLenc(headers: []) {
add `private` access modifier

2022-04-18 12:26 UTC, gsmithun4 commented on plugins/packages/openapi/lib/index.ts
> +  async refreshToken(sourceOptions, error) {
add `private` access modifier

2022-04-20 07:18 UTC, gsmithun4 approved these changes
LGTM

2022-04-21 07:11 UTC, gondar00 requested changes

2022-04-21 07:11 UTC, gondar00 commented on frontend/src/_ui/OpenAPI/OpenapiAuth.jsx
> +  if (auth_type === 'basic') {
Feels like this should be inside a `switch` instead of `if..else`

2022-04-21 07:11 UTC, gondar00 commented on frontend/src/_ui/OpenAPI/index.js
> +        if (security[0].key === auth_key || security[0].key === auth_key) {
```suggestion
        if (security[0].key === auth_key) {
```

2022-04-21 07:11 UTC, gondar00 commented on frontend/src/_ui/OpenAPI/index.js
> +        if (security.key === auth_key || security.key === auth_key) {
```suggestion
        if (security.key === auth_key) {
```

2022-04-21 07:11 UTC, gondar00 commented on frontend/src/_ui/OpenAPI/index.js
> +      </div> */}
❌

2022-04-21 07:11 UTC, gondar00 commented on frontend/src/_ui/OpenAPI/index.js
> +      {!loadingSpec && securities.length > 0 && (
```suggestion
      {!loadingSpec && Array.isArray(securities) && securities.length > 0 && (
```

2022-04-21 09:02 UTC, shah21 commented on frontend/package.json
> +    "yaml-parser": "^3.5.3",
Oh Forgot to remove the package after testing various libs.

2022-04-21 10:09 UTC, gondar00 reviewed
nit

2022-04-21 10:09 UTC, gondar00 commented on docs/docs/data-sources/openapi.md
> +ToolJet has a datasource for generate REST API operations from OpenAPI Specs.
```suggestion
ToolJet has a data source for generating REST API operations from OpenAPI Specs. 
```

2022-04-21 10:09 UTC, gondar00 commented on docs/docs/data-sources/openapi.md
> +- Connections can generate from OpenAPI Specifications. Currently supports Basic, API Key, Bearer, Oauth2
```suggestion
- Connections are generated from OpenAPI specifications. Currently supports Basic Auth, API Key, Bearer Token, OAuth 2.0
```

2022-04-21 10:09 UTC, gondar00 commented on docs/docs/data-sources/openapi.md
> +- Operations will be generate from specs and each one will be different from other
```suggestion
- Operations will be generated from specifications and each one will be different from other 
```

2022-04-21 10:09 UTC, gondar00 commented on docs/docs/data-sources/openapi.md
> +  Some specs can have one or more base urls/ servers and specific operations may have seperate Base URL. So you can select URL from host select
```suggestion
Some specs can have one or more base URLs/servers and specific operations may have separate Base URLs. So you can select the URL from the host select
```

2022-04-21 10:09 UTC, gondar00 commented on frontend/src/_ui/OpenAPI/index.js
> +          setValidationError(err?.message ?? 'Enter valid definition');
Need to add `setLoadingSpec(false);` here too in the catch block

2022-04-21 16:58 UTC, gondar00 approved these changes

2022-04-25 10:15 UTC, gsmithun4 approved these changes
LGTM

2022-04-25 13:57 UTC, gondar00 approved these changes

2022-04-26 08:44 UTC, merged