[ Feature ]:: Datepicker exlcudedates addition
ToolJet/ToolJet pull request #2751
Opened 2022-04-05 05:40 UTC by stepinfwd

resolves #2710

2022-04-05 06:20 UTC, gondar00 requested changes

2022-04-05 06:20 UTC, gondar00 commented on frontend/src/Editor/Components/components.js
> +      disabledDates: { type: 'code', displayName: 'Diasbled dates' },
```suggestion
      disabledDates: { type: 'code', displayName: 'Disabled dates' },
```

2022-04-05 06:20 UTC, gondar00 commented on frontend/src/Editor/Components/Datepicker.jsx
> +    setExludedDates(_exluded);
```suggestion
   if(Array.isArray(disabledDates) && disabledDates.length > 0) {
     const _excluded = [];
     disabledDates?.map((item) => {
        if (moment(item, format).isValid()) {
          _excluded.push(moment(item, format).toDate());
        }
      });
      setExcludedDates(_excluded);
   }
```

2022-04-05 06:20 UTC, gondar00 commented on frontend/src/Editor/Components/Datepicker.jsx
> +  const [excludedDates, setExludedDates] = useState([]);
```suggestion
  const [excludedDates, setExcludedDates] = useState([]);
```

2022-04-05 08:40 UTC, stepinfwd commented
changes updated

2022-04-05 11:41 UTC, sherfin94 commented
Please document this field on Date-picker documentation as well.

2022-04-05 11:42 UTC, sherfin94 requested changes
Works well!, requested few enhancements.

2022-04-05 11:42 UTC, sherfin94 commented on frontend/src/Editor/Components/Datepicker.jsx
> +  }, [disabledDates, format]);
Nice 🙌🏼

2022-04-05 11:42 UTC, sherfin94 commented on frontend/src/Editor/Components/components.js
> +        disabledDates: { value: ['1/09/2021'] },
Let's supply `'{{[]}}'` as the default value. Otherwise the user might assume all dates are allowed.

2022-04-18 17:40 UTC, sherfin94 approved these changes

2022-04-18 17:42 UTC, merged