Feature/delete data source
ToolJet/ToolJet pull request #2790
Opened 2022-04-11 19:42 UTC by shah21

Resolves #1554

2022-04-18 07:49 UTC, akshaysasidrn commented
@shah21 Please add a spec with app having multiple versions with data sources and data queries such that deleting data source in a particular version only deletes the corresponding data queries.

2022-04-18 09:01 UTC, shah21 commented
> @shah21 Please add a spec with app having multiple versions with data sources and data queries such that deleting data source in a particular version only deletes the corresponding data queries.

will do that

2022-04-18 09:22 UTC, gsmithun4 commented on server/src/controllers/data_sources.controller.ts
> +    return decamelizeKeys(result);
Do we need to send back postgres response back? shall we check if the operation is success from response and send back empty response with status `200`?

2022-04-18 17:38 UTC, sherfin94 requested changes
<img width="144" alt="image" src="https://user-images.githubusercontent.com/20333972/163849154-23e40792-71c4-4e43-897a-13f29d11da64.png">

The new delete button seem to be breaking down the label of certain data sources. Maybe increase the width of the popover a bit?

Other than this everything looks fine editor-wise.

2022-04-21 16:36 UTC, sherfin94 requested changes
Requested one change, functionality works perfectly!

2022-04-21 16:36 UTC, sherfin94 commented on server/src/controllers/data_sources.controller.ts
> +    if (!ability.can('deleteQuery', dataSource.app)) {
Can we add a `deleteSource` ability type and use it?

2022-04-21 20:26 UTC, gsmithun4 commented on frontend/src/Editor/LeftSidebar/SidebarDatasources.jsx
> +                // display: this.state.showHiddenOptionsForDataQueryId === dataQuery.id ? 'block' : 'none',
Remove the commented code

2022-04-26 08:41 UTC, gsmithun4 approved these changes
LGTM

2022-04-27 13:02 UTC, akshaysasidrn submitted a review, later dismissed

2022-04-29 07:45 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Cases<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Case | Steps | Result
-- | -- | --
Delete button should work for added data sources. | Create an application. | Application gets created.
  | Add data source & save it. | Data sources should be added.
  | Click on the data source. | It should have delete button on the right corner.
  | Click on the delete button. | It gets pop up
Delete should delete the queries created corresponding it. | Create an application. | Application gets created.
  | Add data source & save it. | Data sources should be added.
  | Create a query for the added data source. | The query gets created.
  | Click on the data source. | It should have delete button on the right corner.
  | Click on the delete button. | It deletes the datasource and the query
Imported application should have data source delete button as working. | Import the application. | The application gets imported.
  | Click on datasource. | Data sources is displayed.
  | Click on delete button. | It deletes the datasource & query with it.

<!--EndFragment-->
</body>
</html>

2022-04-29 09:33 UTC, gsmithun4 requested changes
Found two issues
1. Delete conformation alert box style (button should be red)
2. https://www.loom.com/share/e20f911fa6844f588f34c21dd65c0532

2022-04-29 09:41 UTC, shah21 commented
> Found two issues
> 
> 1. Delete conformation alert box style (button should be red)
> 2. https://www.loom.com/share/e20f911fa6844f588f34c21dd65c0532

The second one is a general issue.its not related to my changes. It existed in develop branch for a long. something goes wrong after coming back to same data source modal

2022-04-29 13:02 UTC, gsmithun4 approved these changes
LGTM

2022-05-02 11:29 UTC, sherfin94 approved these changes

2022-05-02 13:12 UTC, merged