Bugfix :: Canvas background made programmable and fix for alpha not working
ToolJet/ToolJet pull request #2807
Opened 2022-04-13 05:38 UTC by stepinfwd

#resolves #2776 #2775

2022-04-18 12:35 UTC, sherfin94 requested changes
Few major issues:

- Whatever code that we type using Fx, gets applied immediately and does not get applied when the app is running. For eg, we should be able to set the value of the color from an input widget, and if the user edits the text on the widget while the app is running, background color should change.
- When I press the popout button for the Fx field, the area that I can type on the portal that appears is small, there is something buggy thats going on. Not fully sure if its related to this PR

https://user-images.githubusercontent.com/20333972/163809169-433b1c25-1ec1-40af-abe7-4830f76c1745.mov

2022-05-23 07:56 UTC, stepinfwd commented
Link : https://canvas-toool.herokuapp.com/
@sherfin94

2022-05-23 08:38 UTC, sherfin94 requested changes

2022-05-23 08:38 UTC, sherfin94 commented on frontend/src/Editor/LeftSidebar/SidebarGlobalSettings.jsx
> +  }, [realState]);
How about this to make the background color change as soon as the value computed by backgroundFxQuery changes?
```suggestion
  }, [JSON.stringify(resolveReferences(backgroundFxQuery, realState))]);
```

2022-05-23 20:11 UTC, sherfin94 commented
Its not working on viewer @stepinfwd, please check.

2022-05-30 07:04 UTC, stepinfwd commented
issue fixed @sherfin94

2022-06-01 11:18 UTC, merged