[Feature] Notion plugin 🚀
ToolJet/ToolJet pull request #2853
Opened 2022-04-19 07:09 UTC by shah21

Resolves #2818

2022-04-22 07:01 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Cases<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Case | Steps | Result
-- | -- | --
Icon for Notion in light mode. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Observe the icon for notion. | The notion icon should be visible.
Icon for Notion in dark mode. | Create an application | Application gets created.
  | Click on dark mode. | The application should be
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Observe the icon for notion. | The notion icon should be visible.
Test the connection for Notion. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
Retrieve database operation should retrieve the database | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with database in resource & retrieve database in operation. | It gets the database details.
Query database operation should return the correct results. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with database in resource & query database in operation. | It gets the correct result for the query.
Create database operation should create a databse. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with database in resource & create database in operation. | It creates a new database.
Update database operation should update the database. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with database in resource & update database in operation. | It gets the database updated.
Retrieve page operation should retrieve the page. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with page in resource & retrieve page in operation. | It gets the page details.
Create page operation with page as parent type should create a page. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with a page in resource & create a page in operation & parent type as a page. | It creates a new page.
Create page operation with database as parent type should create a page. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with a page in resource & create a page in operation & parent type as a database. | It creates a new page.
Update page operation should update the page. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with page in resource & update a page in operation. | It gets the page updated.
Retrieve a page property operation should retrieve the page property. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with page in resource & retrieve a page property in operation. | It gets the retrieve the properties of the page.
Archive a page operation should archive the page. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with page in resource & archive a page property in operation & select archive in archive. | The page gets archive.
Unarchive a page operation should unarchive the page. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with page in resource & archive a page property in operation & select unarchive in archive. | The page gets unarchived.
Retrieve a block operation should retrieve the block. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with a block in resource & retrieve a block in operation. | It gets the retrieve the block details.
Append a block operation should append the block. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with block in resource & append a block property in operation. | It appends the block details.
Retrieve a block children operation should retrieve the block. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with block in resource & retrieve a block children in operation. | It retrieves the block of children.
Update a block operation should update the block. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with block in resource & update a block in operation. | It updates the block.
Delete a block operation should delete the block. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with block in resource & delete a block in operation. | It deletes the block.
List all the users should provide list of users. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The token is entered.
  | Click on test connection | It gets verified.
  | Create a query with user in resource & list users in operation. | It lists all the users.
Retrieve the user should provide detail of user. | Create an application | Application gets created.
  | Click on datasources & add datasource. | Datasources gets displayed.
  | Click on Notion & give token. | The to [...]

2022-04-22 07:27 UTC, gsmithun4 requested changes

2022-04-22 07:27 UTC, gsmithun4 commented on docs/docs/data-sources/notion.md
> +
Please add documentation

2022-04-22 08:41 UTC, shah21 commented on docs/docs/data-sources/notion.md
> +
will do

2022-04-25 07:51 UTC, gsmithun4 approved these changes
LGTM

2022-04-26 08:45 UTC, Navaneeth-pk commented
@shah21 please resolve the merge conflicts.

2022-04-26 09:28 UTC, Navaneeth-pk approved these changes

2022-04-26 09:28 UTC, merged