added HTML-CSS widget
ToolJet/ToolJet pull request #2938
Opened 2022-05-01 09:56 UTC by manishkushare

Resolve #2861

2022-05-02 21:43 UTC, gsmithun4 requested changes

2022-05-02 21:43 UTC, gsmithun4 commented on frontend/src/Editor/Components/Html.jsx
> +  console.log(css);
remove console log

2022-05-02 21:43 UTC, gsmithun4 commented on frontend/src/Editor/Components/Html.jsx
> +  console.log(baseStyle);
remove console log

2022-05-02 21:43 UTC, gsmithun4 commented on frontend/src/Editor/Components/Html.jsx
> +    console.log(css);
remove console log

2022-05-03 09:31 UTC, sherfin94 commented
Hey @manishkushare , it seems like the raw css feature is not working.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/20333972/166431797-bb83338f-42ea-43e7-8dcd-90ae7888e917.png">

2022-05-03 09:35 UTC, gsmithun4 commented
> Hey @manishkushare , it seems like the raw css feature is not working. <img alt="image" width="895" src="https://user-images.githubusercontent.com/20333972/166431797-bb83338f-42ea-43e7-8dcd-90ae7888e917.png">

@sherfin94 @manishkushare Is it possible to use code hinter type input for HTML and CSS?

2022-05-03 09:59 UTC, manishkushare commented
[image: Screenshot 2022-05-03 at 3.28.58 PM.png]

On Tue, 3 May 2022 at 15:01, Sherfin Shamsudeen ***@***.***>
wrote:

> Hey @manishkushare <https://github.com/manishkushare> , it seems like the
> raw css feature is not working.
> [image: image]
> <https://user-images.githubusercontent.com/20333972/166431797-bb83338f-42ea-43e7-8dcd-90ae7888e917.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ToolJet/ToolJet/pull/2938#issuecomment-1115903515>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJASFJLCZZAT5URTOIY2QHTVIDW7ZANCNFSM5UZUPJKQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-03 10:02 UTC, manishkushare commented
@sherfin, we don't need to put string for color:''red', we can simply write
color:red

On Tue, 3 May 2022 at 15:29, Manish Kushare ***@***.***>
wrote:

> [image: Screenshot 2022-05-03 at 3.28.58 PM.png]
>
> On Tue, 3 May 2022 at 15:01, Sherfin Shamsudeen ***@***.***>
> wrote:
>
>> Hey @manishkushare <https://github.com/manishkushare> , it seems like
>> the raw css feature is not working.
>> [image: image]
>> <https://user-images.githubusercontent.com/20333972/166431797-bb83338f-42ea-43e7-8dcd-90ae7888e917.png>
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ToolJet/ToolJet/pull/2938#issuecomment-1115903515>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AJASFJLCZZAT5URTOIY2QHTVIDW7ZANCNFSM5UZUPJKQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-05-03 10:16 UTC, manishkushare commented
@gsmithun4 @sherfin94, we don't need to provide color:"red" instead, we can
simply write color:red. Since we are expecting it as raw CSS and also
according to CSS rule, we generally write color : red, for React we need to
write color:"red"

Also, yes we can think about the code hinter input type, Last time, I had a
conversation with Arpit, and we thought that, since we expecting raw HTML
and CSS from the user, we can keep the input field as it is, and we also
have code hinter widget, where user can write code into it and pass that
value as raw HTML inside HTML widget

On Tue, 3 May 2022 at 15:29, Manish Kushare ***@***.***>
wrote:

> [image: Screenshot 2022-05-03 at 3.28.58 PM.png]
>
> On Tue, 3 May 2022 at 15:01, Sherfin Shamsudeen ***@***.***>
> wrote:
>
>> Hey @manishkushare <https://github.com/manishkushare> , it seems like
>> the raw css feature is not working.
>> [image: image]
>> <https://user-images.githubusercontent.com/20333972/166431797-bb83338f-42ea-43e7-8dcd-90ae7888e917.png>
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ToolJet/ToolJet/pull/2938#issuecomment-1115903515>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AJASFJLCZZAT5URTOIY2QHTVIDW7ZANCNFSM5UZUPJKQ>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-05-03 10:43 UTC, manishkushare commented
@gsmithun4 I can try adding code hinter as an input field.

On Tue, 3 May 2022 at 15:46, Manish Kushare ***@***.***>
wrote:

> @gsmithun4 @sherfin94, we don't need to provide color:"red" instead, we
> can simply write color:red. Since we are expecting it as raw CSS and also
> according to CSS rule, we generally write color : red, for React we need to
> write color:"red"
>
> Also, yes we can think about the code hinter input type, Last time, I had
> a conversation with Arpit, and we thought that, since we expecting raw HTML
> and CSS from the user, we can keep the input field as it is, and we also
> have code hinter widget, where user can write code into it and pass that
> value as raw HTML inside HTML widget
>
> On Tue, 3 May 2022 at 15:29, Manish Kushare ***@***.***>
> wrote:
>
>> [image: Screenshot 2022-05-03 at 3.28.58 PM.png]
>>
>> On Tue, 3 May 2022 at 15:01, Sherfin Shamsudeen ***@***.***>
>> wrote:
>>
>>> Hey @manishkushare <https://github.com/manishkushare> , it seems like
>>> the raw css feature is not working.
>>> [image: image]
>>> <https://user-images.githubusercontent.com/20333972/166431797-bb83338f-42ea-43e7-8dcd-90ae7888e917.png>
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/ToolJet/ToolJet/pull/2938#issuecomment-1115903515>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AJASFJLCZZAT5URTOIY2QHTVIDW7ZANCNFSM5UZUPJKQ>
>>> .
>>> You are receiving this because you were mentioned.Message ID:
>>> ***@***.***>
>>>
>>

2022-05-11 12:05 UTC, sherfin94 requested changes
Hey @manishkushare , could you resolve conflicts and merge the latest develop into this and add documentation?

2022-05-11 19:37 UTC, arpitnath requested changes
@manishkushare Please fix the eslint errors and warnings

2022-05-12 06:30 UTC, arpitnath commented
> @manishkushare Please fix the eslint errors and warnings


@sherfin94 Ignore my comment, will fix the eslint issue in a separate PR.

2022-05-12 06:30 UTC, arpitnath commented
> @manishkushare Please fix the eslint errors and warnings


@sherfin94 Ignore my comment, will fix the eslint issue in a separate PR.

2022-05-16 10:39 UTC, sherfin94 requested changes
@manishkushare As we discussed, lets remove the style property for now.

Also, it would be nice to fix the lint as @arpitnath suggested. Only some minor linting issues are there.

2022-06-03 00:22 UTC, saingsocheat approved these changes

2022-06-16 12:28 UTC, merged