[Feature] Added an option to save edited queries to avoid losing values by state changes  🚀
ToolJet/ToolJet pull request #2944
Opened 2022-05-02 02:38 UTC by shah21

Resolves #2943

2022-05-02 10:33 UTC, akshaysasidrn commented on frontend/src/Editor/QueryManager/QueryEditors/Restapi/index.jsx
> +      arrayValuesChanged: false,
Is this state being used directly? Looks like we are only setting it within options to be used with.

2022-05-02 10:33 UTC, akshaysasidrn commented on frontend/src/Editor/QueryManager/QueryManager.jsx
> +    delete options.arrayValuesChanged;
This would modify the object and delete the key in the original object.
Better to copy and remove to compare?

2022-05-03 10:02 UTC, sherfin94 commented
Looks like the issue where the query gets discarded when the panel is dragged is back

https://user-images.githubusercontent.com/20333972/166435477-4b3988fd-7298-44ac-ae49-9088acbd176a.mov

2022-05-04 10:27 UTC, sherfin94 requested changes
One change requested

2022-05-16 08:57 UTC, sherfin94 commented
@shah21  Right now, if I click on `+` and start creating a new query, and add a widget to the canvas while doing this, then the confirmation dialogue is shown. I understand that the panel already resets in this scenario, even without this confirmation box. So is that something we can fix in this PR itself, or is it a separate issue that should be fixed separately?

2022-05-17 07:43 UTC, shah21 commented
> @shah21 Right now, if I click on `+` and start creating a new query, and add a widget to the canvas while doing this, then the confirmation dialogue is shown. I understand that the panel already resets in this scenario, even without this confirmation box. So is that something we can fix in this PR itself, or is it a separate issue that should be fixed separately?

Yeah, it is the expected behavior of the query manager, if the user does something in the canvas area while editing a query, the popup will be shown.

2022-05-23 22:32 UTC, sherfin94 approved these changes

2022-05-23 22:33 UTC, merged