Feature :: Button group widget
ToolJet/ToolJet pull request #2977
Opened 2022-05-05 04:59 UTC by stepinfwd

closes #2876

2022-05-11 10:38 UTC, sherfin94 requested changes
Widget works fine!, few things:

Since you're using an array as exposed variable for both single selection and multiple selection, please ensure that the initially exposed value is `[1]` and not `1`.

Also please add documentation, sync with @withshubh if that helps.

2022-05-11 15:34 UTC, stepinfwd commented
updated with required changes @sherfin94

2022-05-23 22:22 UTC, sherfin94 commented
Can we make it so, that we can supply default selected an actual array instead of a string that will be parsed as an array?
<img width="337" alt="image" src="https://user-images.githubusercontent.com/20333972/169914364-9844bde7-1efe-49ce-81c2-a1dcff9a58eb.png">

2022-05-23 22:26 UTC, sherfin94 commented
When the `Enable multiple selection` property is toggled on or off, the widget's state (the buttons that are displayed as selected, and the exposed value) should reset to the `default selected` value. Presently, the widget stays as if no buttons are selected and the exposed value remains the same.

2022-05-23 22:29 UTC, sherfin94 requested changes
Suggested few changes, otherwise looks fine.

2022-05-23 22:29 UTC, sherfin94 commented on frontend/src/Editor/Components/components.js
> +        label: { value: `Button` },
```suggestion
        label: { value: `Button group` },
```

2022-06-01 07:31 UTC, sherfin94 requested changes
Final change, there seems to be unnecessary padding on the top when button group label is removed:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/20333972/171351396-97c12ccf-4a6a-4e64-b88d-d8d1ad5cf290.png">

If header is removed, this padding is not required.

2022-06-01 08:19 UTC, sherfin94 approved these changes

2022-06-01 08:20 UTC, merged