Avoid creation of system group names
ToolJet/ToolJet pull request #2999
Opened 2022-05-06 13:09 UTC by tanmoyopenroot

#### Fixes #2969 and #2824 (Dublicate)

#### Checklist
- [x] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:
Check for possible values like `'All Users', 'all_users', 'Admin', 'admin'`

#### Reviewers should focus on:
Currently hard cording all the possible values in the create method in `GroupPermissionsService`
```javascript
    const reservedGroups = ['All Users', 'all_users', 'Admin', 'admin'];
```

2022-05-10 06:52 UTC, gsmithun4 requested changes

2022-05-10 06:52 UTC, gsmithun4 commented on server/src/services/group_permissions.service.ts
> +    const reservedGroups = ['All Users', 'all_users', 'Admin', 'admin'];
`['All Users', 'Admin']`
are enough

2022-05-10 06:52 UTC, gsmithun4 commented on server/src/services/group_permissions.service.ts
> +      throw new BadRequestException('Cannot create group with system reserved group name');
shall we throw the same error
```
Group name already exist
```

2022-05-10 06:52 UTC, gsmithun4 commented
@tanmoyopenroot Please fix the lint errors

2022-05-10 08:38 UTC, tanmoyopenroot commented on server/src/services/group_permissions.service.ts
> +      throw new BadRequestException('Cannot create group with system reserved group name');
Sure, Will do

2022-05-10 23:53 UTC, tanmoyopenroot commented on server/src/services/group_permissions.service.ts
> +      throw new BadRequestException('Cannot create group with system reserved group name');
Done

2022-05-10 23:53 UTC, tanmoyopenroot commented on server/src/services/group_permissions.service.ts
> +    const reservedGroups = ['All Users', 'all_users', 'Admin', 'admin'];
Done

2022-05-12 18:37 UTC, gsmithun4 commented
deployed 
https://group-fixes-tj.herokuapp.com/

2022-05-13 07:48 UTC, merged