Inline style support for custom component
ToolJet/ToolJet pull request #3076
Opened 2022-05-18 06:03 UTC by kavinvenkatachalam

Resolves #3075

2022-05-23 22:02 UTC, sherfin94 requested changes
We can access the unresolved value of `code` property from CustomComponent.jsx in this manner:

```const code = props.component.definition.properties.code.value;```

This way we wouldn't have to hack properties resolution.

2022-05-24 03:21 UTC, kavinvenkatachalam commented
> We can access the unresolved value of `code` property from CustomComponent.jsx in this manner:
> 
> `const code = props.component.definition.properties.code.value;`
> 
> This way we wouldn't have to hack properties resolution.

The `code` value can be accessed using the `component` prop. But while resolving the `code` value, I'm getting an error `Unexpected token ':'`. So, I skipped the resolvable when the property is `code` in `CustomComponent`. Any suggestions?

<img width="554" alt="image" src="https://user-images.githubusercontent.com/50441969/169942016-16bfb8d7-cb18-4653-80a2-fcf45750ff46.png">

2022-06-01 12:27 UTC, sherfin94 commented
> > We can access the unresolved value of `code` property from CustomComponent.jsx in this manner:
> > `const code = props.component.definition.properties.code.value;`
> > This way we wouldn't have to hack properties resolution.
> 
> The `code` value can be accessed using the `component` prop. But while resolving the `code` value, I'm getting an error `Unexpected token ':'`. So, I skipped the resolvable when the property is `code` in `CustomComponent`. Any suggestions?
> 
> <img alt="image" width="554" src="https://user-images.githubusercontent.com/50441969/169942016-16bfb8d7-cb18-4653-80a2-fcf45750ff46.png">

Hey @kavinvenkatachalam, I'm not sure I understand. we don't need to resolve the value of `code`, that is the reason why we are accessing it from `component.definition` instead of `props`, is it not?. 

If you're facing `undefined` related errors, might be a good idea to use `component.definition?.properties?.code?.value ?? ''`

2022-06-03 12:17 UTC, sherfin94 approved these changes

2022-06-03 12:17 UTC, merged