Cypress test for the profile settings page
ToolJet/ToolJet pull request #3083
Opened 2022-05-18 14:14 UTC by ajith-k-v

Fixes: #3077 

1. Added cypress test for the profile settings page.
2. Updated common selector and common text file.
3. Added random names.
4. Added data-cy attribute for the components.

Test Run-Status can be seen from the attached Screenshot.
<img width="1440" alt="Screenshot 2022-05-18 at 7 40 06 PM" src="https://user-images.githubusercontent.com/20367957/169062673-77c31dd3-066b-4345-80d8-9356b23cf350.png">

2022-05-23 21:34 UTC, sherfin94 requested changes
I reset db and seeded it and run the spec, there seems to be some issue:

<img width="763" alt="image" src="https://user-images.githubusercontent.com/20333972/169909507-4ba46c9d-31a2-4f83-96ef-932745d961db.png">

2022-05-24 07:30 UTC, ajith-k-v commented
@sherfin94 Updated the changes. Please review

2022-05-30 08:57 UTC, sherfin94 requested changes
Spec still seems to be failing, please check again.

2022-06-01 08:12 UTC, sherfin94 approved these changes

2022-06-01 08:12 UTC, merged