[docs]  :: multi workspace docs
ToolJet/ToolJet pull request #3087
Opened 2022-05-19 10:19 UTC by stepinfwd

resolves #3086

2022-05-22 20:36 UTC, gsmithun4 approved these changes
LGTM

2022-05-25 08:25 UTC, withshubh requested changes

2022-05-26 11:04 UTC, withshubh submitted a review, later dismissed

2022-05-27 19:39 UTC, gsmithun4 commented
@withshubh Multi-Workspace documentation is under `Tutorials`, is that a perfect fit?

2022-05-28 21:03 UTC, gsmithun4 approved these changes

2022-05-30 05:16 UTC, merged