#3030 - hide user details when getting apps
ToolJet/ToolJet pull request #3097
Opened 2022-05-20 08:09 UTC by mslourens

Remove sensitive user details from the apps api response.

Fixes #3030

2022-05-20 17:12 UTC, gsmithun4 requested changes

2022-05-20 17:12 UTC, gsmithun4 commented on server/src/controllers/apps.controller.ts
> +    apps.forEach((app) => this.userService.removeSensitiveData(app.user));
Shall we try changing the query?
```
const viewableAppsQb = createQueryBuilder(App, 'apps')
      .select(['app_group_permissions', 'user.first_name', 'user.last_name'])
      .innerJoin('apps.groupPermissions', 'group_permissions')
      .innerJoin('apps.appGroupPermissions', 'app_group_permissions')
      .innerJoin('apps.user', 'user')
      .innerJoin(
        UserGroupPermission,
        'user_group_permissions',
        'app_group_permissions.group_permission_id = user_group_permissions.group_permission_id'
      )
      .where('apps.organization_id = :organizationId', { organizationId: user.organizationId })
      .andWhere(
        new Brackets((qb) => {
          qb.where('user_group_permissions.user_id = :userId', {
            userId: user.id,
          })
            .andWhere('app_group_permissions.read = :value', { value: true })
            .orWhere('apps.is_public = :value OR apps.user_id = :userId', {
              value: true,
              userId: user.id,
            });
        })
      );
    if (searchKey) {
      viewableAppsQb.andWhere('LOWER(apps.name) like :searchKey', {
        searchKey: `%${searchKey && searchKey.toLowerCase()}%`,
      });
    }
```
[Reference](https://github.com/typeorm/typeorm/issues/876)

2022-07-05 11:06 UTC, withshubh commented
Hey @mslourens 👋 
Please update the PR with the requested changes so that we can merge this fix?

2022-07-13 21:53 UTC, withshubh commented
@mslourens 👋 I hope you're fine. Please update the PR with the requested changes?

2022-07-20 07:18 UTC, mslourens commented
> @mslourens 👋 I hope you're fine. Please update the PR with the requested changes?

Hi @withshubh, I am fine, but currently a bit busy with my work. Next to that my knowledge of TypeORM and Knex is limited, so if somebody else could update the query, that would be much appreciated.

2022-08-02 20:54 UTC, gsmithun4 commented
duplicate https://github.com/ToolJet/ToolJet/pull/3722

2022-08-02 20:54 UTC, closed without merging