3066 incorrect message while enabling disabling password
ToolJet/ToolJet pull request #3110
Opened 2022-05-24 04:43 UTC by Sam-Kohl

On Form.jsx line 14, removed 'Form' and replaced with 'Password'.

2022-05-24 04:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=3110) it.</sub>

2022-05-24 05:03 UTC, gsmithun4 commented
@Sam-Kohl Can you please fix the lint errors

2022-05-31 00:50 UTC, Navaneeth-pk commented
Please fix the lint errors and sign the CLA so that we can merge this PR.
@Sam-Kohl

2022-05-31 01:42 UTC, Sam-Kohl commented
Hey all. Sorry for the delay. Was away for a wedding.
Fixed and committed.  CLA signed.
Thanks for your patience.

2022-06-07 18:43 UTC, gsmithun4 requested changes

2022-06-07 18:43 UTC, gsmithun4 commented on frontend/src/ManageSSO/Form.jsx
> +        };
```
toast.success(`${enabled_tmp ? 'Enabled' : 'Disabled'} Password login`, {
    position: 'top-center',
});
```

2022-06-20 05:26 UTC, Navaneeth-pk approved these changes

2022-06-20 05:26 UTC, merged