[Feature] Added ability to update and delete app folders
ToolJet/ToolJet pull request #3132
Opened 2022-05-26 11:16 UTC by shah21

- [x] Delete & Update APIs and services
- [x] Delete & Update Group permissions
- [x] Implement folder menu & actions
- [x] API Specs

Resolves #3067

2022-05-30 15:00 UTC, akshaysasidrn requested changes

2022-05-30 15:03 UTC, akshaysasidrn commented on server/src/services/folders.service.ts
> +    return await this.foldersRepository.delete({ id });
Please scope this with organization id

2022-05-31 04:10 UTC, shah21 commented on frontend/src/HomePage/Folders.jsx
> +                  ? `the folder ${deletingFolder.name} has ${deletingFolder.folder_apps.length} apps in it, by deleting the apps contain the folder will moved to uncategoried section.`
Yeah, that will be fine, I just followed the design 👍

2022-05-31 04:13 UTC, shah21 commented on frontend/src/ManageGroupPermissionResources/ManageGroupPermissionResources.jsx
> +                                        <label className="form-check form-check-inline">
Yeah, that's right, I forgot to add the checkbox, I will add it

2022-06-01 15:06 UTC, shah21 commented on frontend/src/HomePage/FolderMenu.jsx
> +  canDeleteApp = true,
That's a typo, I forgot to change the property's names, I should be like canDeleteFolder, canUpdateFolder, my bad

2022-06-07 20:32 UTC, akshaysasidrn requested changes

2022-06-07 20:32 UTC, akshaysasidrn commented on frontend/src/HomePage/Folders.jsx
> +      .catch(() => {
Please show an error toast as well

2022-06-07 20:43 UTC, gsmithun4 requested changes

2022-06-07 20:43 UTC, gsmithun4 commented on server/src/controllers/folders.controller.ts
> +  async update(@Request() req, @Param('id') id, @Body() body: any) {
```suggestion
  async update(@User() user, @Param('id') id, @Body() body: any) {
```

2022-06-09 07:18 UTC, gsmithun4 commented on server/src/controllers/folders.controller.ts
> +  async update(@User() user, @Param('id') id, @Body() body: any) {
```suggestion
  async update(@User() user, @Param('id') id, @Body('name') folderName: string) {
```

2022-06-14 08:20 UTC, gsmithun4 commented on frontend/src/HomePage/Folders.jsx
> +        toast.success('folder has been deleted.', {
please capitalise all toasts

2022-06-16 08:58 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Cases<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Case | Steps | Result
-- | -- | --
Should be able to update folder name as an admin. | Login as admin. | Logged in as admin.
  | Create an application. | Application is created.
  | Create a folder | Folder is created.
  | Click on the 3 dots. | 2 options is displayed.
  | Click on edit folder. | The pop up is displayed.
  | Enter an updated name & click save. | The folder name is updated.
Should be able to delete folder as an admin. | Login as admin. | Logged in as admin.
  | Create an application. | Application is created.
  | Create a folder | Folder is created.
  | Click on the 3 dots. | 2 options is displayed.
  | Click on delete folder. | The pop up is displayed.
  | Click on yes. | The folder is deleted except the apps inside it.
Should be able to cancel the updated name of the folder. | Login as admin. | Logged in as admin.
  | Create an application. | Application is created.
  | Create a folder | Folder is created.
  | Click on the 3 dots. | 2 options is displayed.
  | Click on edit folder. | The pop up is displayed.
  | Click on cancel or cross. | The folder name is not updated.
Should be able to cancel the deletion of the folder. | Login as admin. | Logged in as admin.
  | Create an application. | Application is created.
  | Create a folder | Folder is created.
  | Click on the 3 dots. | 2 options is displayed.
  | Click on delete folder. | The pop up is displayed.
  | Click on cancel. | The folder is not deleted.
Should be able to update as non admin. | Login as admin. | Logged in as admin.
  | Create a new user. | User is created.
  | Create a new group. | New group is created.
  | Give folder create/update/delete permission along with application create permission. | The permissions are given.
  |   |  
  | Create an application. | Application is created.
  | Create a folder | Folder is created.
  | Click on the 3 dots. | 2 options is displayed.
  | Click on edit folder. | The pop up is displayed.
  | Enter an updated name & click save. | The folder name is updated.
Should be able to delete as non admin. | Login as admin. | Logged in as admin.
  | Create a new user. | User is created.
  | Create a new group. | New group is created.
  | Give folder create/update/delete permission along with application create permission. | The permissions are given.
  |   |  
  | Create an application. | Application is created.
  | Create a folder | Folder is created.
  | Click on the 3 dots. | 2 options is displayed.
  | Click on delete folder. | The pop up is displayed.
  | Click on yes. | The folder is deleted except the apps inside it.

<!--EndFragment-->
</body>
</html>

2022-06-16 11:13 UTC, akshaysasidrn approved these changes

2022-06-16 14:11 UTC, merged