Feature :: adding  'add datasource' option  on datasource panel
ToolJet/ToolJet pull request #3191
Opened 2022-06-02 09:29 UTC by stepinfwd

closes #2612

2022-06-09 03:49 UTC, kavinvenkatachalam requested changes
@stepinfwd Few minor changes

2022-06-09 03:49 UTC, kavinvenkatachalam commented on frontend/src/Editor/QueryManager/DataSourceLister.jsx
> +        <p style={{ fontWeight: '500' }}> Add datasource</p>
Reduce the `fontWeight` to `400` and the icon color to `grey` as it looks different from other sources. 
<img width="630" alt="image" src="https://user-images.githubusercontent.com/50441969/172758833-b88bf000-5f7c-4b5f-8a2d-ef786456ee50.png">

2022-06-09 03:49 UTC, kavinvenkatachalam commented on frontend/src/Editor/LeftSidebar/index.js
> +  const [showDataSourceManagerModal, toggleDataSourceManagerModal] = React.useState(false);
Please replace `React.useState` with `useState` as we're importing it at the top and using it in the file

2022-06-09 09:16 UTC, stepinfwd commented
requested changes are  updated @kavinvenkatachalam  @sherfin94

2022-06-09 09:28 UTC, kavinvenkatachalam approved these changes
LGTM

2022-06-15 10:46 UTC, sherfin94 approved these changes

2022-06-15 10:46 UTC, merged