Feature :: event firing on tab selection in Tabs widget
ToolJet/ToolJet pull request #3193
Opened 2022-06-02 12:12 UTC by stepinfwd

resolves #3192

2022-06-03 10:27 UTC, sherfin94 requested changes

2022-06-03 10:27 UTC, sherfin94 commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +    events: { onClick: { displayName: 'On click' } },
```suggestion
    events: { onTabSwitch: { displayName: 'On tab switch' } },
```
`On click` will imply a different kind of meaning @stepinfwd . Let's use `onTabSwitch`.  You will have to add this event handle on the array that starts at `appUtils.js:473` as well as this is a new type of event.

2022-06-07 11:30 UTC, stepinfwd commented
updated require changes @sherfin94

2022-06-08 06:50 UTC, sherfin94 approved these changes

2022-06-08 06:50 UTC, merged