typography correction under Layout section
ToolJet/ToolJet pull request #3248
Opened 2022-06-09 15:18 UTC by AAYUSH-droid

Small update under layout section--> "determing" changed "determine"

2022-06-09 15:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3248) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3248) before we can accept your contribution.<br/><hr/>**AAYUSH SHARMA** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=3248) it.</sub>

2022-06-10 00:51 UTC, withshubh requested changes

2022-06-10 00:51 UTC, withshubh commented on docs/docs/widgets/chart.md
> +Toggle on or off to display the widget in desktop view. You can programmatically determine the value by clicking on `Fx` to set the value `{{true}}` or `{{false}}`.
Can you please fix the same typo here in `Show on desktop` section?

2022-06-14 05:17 UTC, withshubh approved these changes

2022-06-14 05:24 UTC, withshubh commented
Hey @AAYUSH-droid 
Can you please fix the merge conflicts?

2022-06-20 03:56 UTC, Navaneeth-pk commented
We can close this PR as soon as the merge conflicts are resolved. 
@AAYUSH-droid

2022-06-20 06:26 UTC, closed without merging