Feature ::  AWS Athena plugin
ToolJet/ToolJet pull request #3281
Opened 2022-06-14 12:49 UTC by stepinfwd

closes #2937

package used : [](https://www.npmjs.com/package/athena-express)

2022-06-18 14:30 UTC, Navaneeth-pk commented
![image](https://user-images.githubusercontent.com/7828962/174442960-4f518e36-620b-43f3-b65d-6f2e7c84abe5.png)

Probably an app-wide issue not related to this PR.

2022-06-22 05:41 UTC, gsmithun4 requested changes

2022-06-22 05:41 UTC, gsmithun4 commented on plugins/package-lock.json
> -        "@tooljet-plugins/saphana": "file:packages/saphana",
Saphana is removed, please add it

2022-06-22 05:41 UTC, gsmithun4 commented on plugins/packages/athena/lib/index.ts
> +    const AthenaExpress = require('athena-express'),
shall we import them at the top?

2022-06-22 13:34 UTC, stepinfwd commented
All changes are updated @gsmithun4

2022-06-23 12:04 UTC, gsmithun4 approved these changes
LGTM

2022-06-24 11:40 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Cases<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Case | Steps | Result
-- | -- | --
Should be able to view the icon for amazon athena in light mode. | Create an application. | Application gets created.
  | Click on add data source. | The datasource pop up opens up.
  | Search amazon athena. | The icon is visible.
Should be able to view the icon for amazon athena in dark mode. | Create an application. | Application gets created.
  | Click on dark mode. | The application gets into dark mode.
  | Click on add data source. | The datasource pop up opens up.
  | Search amazon athena. | The icon is visible.
Should be able to get results for queries. | Create an application. | Application gets created.
  | Click on add data source. | The datasource pop up opens up.
  | Click on athena. | Athena connection pop up is displayed.
  | Enter the credentials. | The credentials are entered.
  | Click on test connection. | The connection is verified.
  | Click on save. | The datasource is saved.
  | Create a query for creating database & click preview. | Database is created.
  | Create another query for displaying the database created & click preview. | Created database name's are displayed.
Should be able to get results for next token & query execution id. | Create an application. | Application gets created.
  | Click on add data source. | The datasource pop up opens up.
  | Click on athena. | Athena connection pop up is displayed.
  | Enter the credentials. | The credentials are entered.
  | Click on test connection. | The connection is verified.
  | Click on save. | The datasource is saved.
  | Create a query for limiting students with some pagination value less than 10 & click on preview. | The query displayed the correct results.

<!--EndFragment-->
</body>
</html>

2022-06-27 06:53 UTC, gsmithun4 requested changes

2022-06-27 06:53 UTC, gsmithun4 commented on plugins/packages/athena/lib/index.ts
> +      await athenaClient.query('SHOW TABLES');
why are we using try catch here? it doesn't make any difference since we are throwing the same error

2022-06-29 06:47 UTC, gsmithun4 approved these changes
LGTM

2022-06-29 08:17 UTC, merged