graph accordian moved in options
ToolJet/ToolJet pull request #3305
Opened 2022-06-17 05:19 UTC by hrutik7

## In the chart widget, group "show axes" , "show grid lines" and "loading state" inside one accordion named as "options"

![image](https://user-images.githubusercontent.com/62372737/174230237-3376f194-12a9-422b-b60c-60bedfd4199b.png)

2022-06-17 05:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3305) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3305) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=3305) it.</sub>

2022-06-17 13:33 UTC, hrutik7 commented
sure

2022-06-20 05:58 UTC, gondar00 commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +
nit: 
@hrutik7 can you please remove these spaces on line num 240 & 241,

2022-06-20 11:16 UTC, hrutik7 commented
Sure thing

2022-06-21 14:03 UTC, hrutik7 commented
hey @gondar00 ,
I am not getting why one of the test is failing , I am new to opensource will you please look into this once the things get more clear to me I'll do more contributions
Thanks :)

2022-06-28 08:54 UTC, gondar00 commented
Hi @hrutik7, could you once try running the command `npm run --prefix frontend lint`

2022-07-05 10:55 UTC, withshubh commented
Hey @hrutik7 
Please make the required changes so that we can merge this fix?

2022-07-06 11:56 UTC, hrutik7 commented
Hey @withshubh 
issue has been resolved , but I am getting this kind of errors

![image](https://user-images.githubusercontent.com/62372737/177544640-ae1adbc0-602a-4a39-8e8f-a5550bd7a3fa.png)

2022-07-06 18:01 UTC, withshubh commented
@gondar00 Need your help here.

2022-07-07 13:04 UTC, gondar00 commented
@hrutik7  can u try running `docker-compose exec server npm i`

2022-07-13 21:49 UTC, withshubh commented
@hrutik7 - Did you try running the command suggested above?

2022-07-14 02:38 UTC, hrutik7 commented
@withshubh yes but still getting the same problem
![image](https://user-images.githubusercontent.com/62372737/178886230-9307e63a-472d-4470-9d6d-3c437f60f805.png)

2022-07-15 08:41 UTC, arpitnath requested changes
please revert back changes added to plugins lock file and `packages/woocommerce/lib/operations.json`

2022-07-25 08:10 UTC, shivangT commented
Hello @hrutik7 ,
Any updates on the following?
Please revert the changes in the mentioned file. We've to close the issue associated with this. 

Thanks

2022-08-03 11:49 UTC, gondar00 approved these changes

2022-08-03 12:01 UTC, merged