Added confirm input  in profile settings
ToolJet/ToolJet pull request #3375
Opened 2022-06-23 13:29 UTC by Syed-Ansar

Added Confirm password field for profile-change password section and Validated inputs as if there is no input in current passwords and having inputs in other to new passwords then error will be thrown and if confirm password doesn't match with new password then it with throw an error. Recreated pull request because of linting problems

fixes issue https://github.com/ToolJet/ToolJet/issues/3108

<img width="1440" alt="tooljet" src="https://user-images.githubusercontent.com/82027712/175310564-e8d92059-05b6-4fe7-bbfd-9b5a6d823a66.png">

2022-06-23 15:34 UTC, gsmithun4 requested changes

2022-06-23 15:34 UTC, gsmithun4 commented on frontend/src/SettingsPage/SettingsPage.jsx
> +        toast.error('Please verify that confirm new password is incorrect', {
```suggestion
        toast.error('New password and confirm password are not matching', {
```

2022-06-24 06:12 UTC, Syed-Ansar commented
Hi @gsmithun4 I have made changes as you suggested.

2022-06-24 14:17 UTC, gsmithun4 commented
Deployed
https://tj-3375.herokuapp.com/

2022-06-27 06:43 UTC, Nandinisaha13 commented
![Screenshot (71)](https://user-images.githubusercontent.com/41302917/175872207-d71fe87a-4bfb-4e32-a107-111fbfc3c846.png)
![Screenshot (70)](https://user-images.githubusercontent.com/41302917/175872215-15c24542-e9ca-4dcd-941a-b9ab1bc1cb6e.png)
There is some extra white space at the bottom for both light & dark mode. @Syed-Ansar can you look into this?

2022-06-27 06:51 UTC, Syed-Ansar commented
Hey @Nandinisaha13 I have just taken screen-shots on deployed [Here](https://tj-3375.herokuapp.com/). I did'nt get any whitespace 

<img width="1440" alt="Screenshot 2022-06-27 at 12 18 53 PM" src="https://user-images.githubusercontent.com/82027712/175877218-b4fc478f-5359-462a-9de3-19e865fc4b13.png">

<img width="1440" alt="Screenshot 2022-06-27 at 12 18 46 PM" src="https://user-images.githubusercontent.com/82027712/175877275-b550ba64-4881-4d27-ae88-49678aaa00f3.png">

2022-06-27 08:13 UTC, Nandinisaha13 commented
@Syed-Ansar That is being checked because I am checking the same and I can see the white space still, may be a resolution problem! I also found this(screenshot attached) If we can give a error message as "Current password is incorrect" or "Please verify the password entered in current password or may be something more suitable.
![Screenshot (182)](https://user-images.githubusercontent.com/41302917/175892199-54dca8e7-460b-430d-88e2-5808481aa94e.png)

2022-06-27 08:29 UTC, Syed-Ansar commented
> @Syed-Ansar That is being checked because I am checking the same and I can see the white space still, may be a resolution problem! I also found this(screenshot attached) If we can give a error message as "Current password is incorrect" or "Please verify the password entered in current password or may be something more suitable. ![Screenshot (182)](https://user-images.githubusercontent.com/41302917/175892199-54dca8e7-460b-430d-88e2-5808481aa94e.png)

Hey @Nandinisaha13 I am using Macbook Air so I am not able to detect the problem of white-space, I verified on Chrome as well as Firefox I couldn't detect the whitespace problem on either themes i.e, Light & Dark. When it comes to password toast message it was set before only so I didn't changed it. If you ask me to change I would suggest as "You have entered an invalid password" or "You have entered an invalid current password".

2022-06-27 09:58 UTC, gsmithun4 commented
> > @Syed-Ansar That is being checked because I am checking the same and I can see the white space still, may be a resolution problem! I also found this(screenshot attached) If we can give a error message as "Current password is incorrect" or "Please verify the password entered in current password or may be something more suitable. ![Screenshot (182)](https://user-images.githubusercontent.com/41302917/175892199-54dca8e7-460b-430d-88e2-5808481aa94e.png)
> 
> Hey @Nandinisaha13 I am using Macbook Air so I am not able to detect the problem of white-space, I verified on Chrome as well as Firefox I couldn't detect the whitespace problem on either themes i.e, Light & Dark. When it comes to password toast message it was set before only so I didn't changed it. If you ask me to change I would suggest as "You have entered an invalid password" or "You have entered an invalid current password".

@Nandinisaha13 Let's create separate issues for the cases, Good to merge if functionality works

2022-06-27 10:43 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Cases<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Case | Steps | Result
-- | -- | --
Should be able to view confirm new password field. | Hover over name annotation. | 2 options is displayed.
  | Go to profile. | Profile page is displayed.
  | Observe. | Confirm new password field is displayed.
Should be able to confirm new password. | Hover over name annotation. | 2 options is displayed.
  | Go to profile. | Profile page is displayed.
  | Enter correct current password. | Current password is displayed in dots.
  | Enter new password. | New password is displayed in dots.
  | Enter confirm new password same as new password. | Confirm new password field is displayed in dots.
  | Click on change password. | The password is changed.
Should not be able to confirm new password. | Hover over name annotation. | 2 options is displayed.
  | Go to profile. | Profile page is displayed.
  | Enter correct current password. | Current password is displayed in dots.
  | Enter new password. | New password is displayed in dots.
  | Enter confirm new password not same as new password. | Confirm new password field is displayed in dots.
  | Click on change password. | Error is displayed.

<!--EndFragment-->
</body>
</html>

2022-06-28 07:56 UTC, gsmithun4 submitted a review, later dismissed
LGTM

2022-07-14 05:02 UTC, gsmithun4 approved these changes
LGTM

2022-07-14 05:03 UTC, merged