[Feature]: Re-Order Events
ToolJet/ToolJet pull request #3381
Opened 2022-06-24 07:52 UTC by kavinvenkatachalam

Resolves #3380

2022-07-04 10:50 UTC, shubh22 commented
Task linked: [CU-2h1aaux Re-order Events](https://app.clickup.com/t/2h1aaux)

2022-07-06 11:59 UTC, sherfin94 requested changes
Suggested a code enhancement.

2022-07-06 11:59 UTC, sherfin94 commented on frontend/src/Editor/Inspector/EventManager.jsx
> +    eventsChanged(result);
@kavinvenkatachalam, Even if I removed this `eventsChanged` call, the reordering function will still work, due to the mutation caused by the preceding two `splice` calls. Though I don't see any bugs, I'm feeling a bit scared about introducing state mutation here, can we do it without mutation? At worst we can just use 
`const result = _.cloneDeep(component.component.definition.events);`  on line 609

Perhaps we can do something similar on the third splice call that exists on the `removeHandler` function as well.

2022-07-08 11:53 UTC, sherfin94 approved these changes

2022-07-08 11:53 UTC, merged