Enhancement : added all the css prop for the text in the styles section of the Text Widget
ToolJet/ToolJet pull request #3392
Opened 2022-06-24 18:01 UTC by manishkushare

Resolve #3391

2022-06-28 10:27 UTC, sherfin94 requested changes
Small change requested.

2022-06-28 10:27 UTC, sherfin94 commented on frontend/src/Editor/Components/Text.jsx
> +  console.log('shadow', verticalShadow, horizontalShadow, blur, shadowColor);
Please remove this console log, and while removing it there are some lint errors that are occurring, please fix those also.

2022-07-04 11:19 UTC, shubh22 commented
Task linked: [CU-2h1aaz2 Adding CSS props to Text Widget](https://app.clickup.com/t/2h1aaz2)

2022-08-09 11:56 UTC, sherfin94 requested changes
Few changes requested.

2022-08-09 11:56 UTC, sherfin94 commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +      fontVariant: { type: 'toggle', displayName: 'Font Variant' },
The `font variant` property is not a toggle field, please make it a dropdown.

2022-08-09 11:56 UTC, sherfin94 commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        fontVariant: { value: '{{false}}' },
Again, not a toggle, so its not a boolean value.

2022-08-09 11:56 UTC, sherfin94 commented on server/migrations/1656924847186-addingCssPropsToTextWidget.ts
> +              fontVariant: false,
Same issue as described on previous comments.

2022-08-09 11:56 UTC, sherfin94 commented on frontend/src/Editor/Components/Text.jsx
> +    lineHeight: lineHeight ?? 1.5,
Should we also not append `px` for `line height` ?

2022-08-17 09:21 UTC, sherfin94 approved these changes

2022-08-17 09:22 UTC, merged