Fixed the height of button in navbar
ToolJet/ToolJet pull request #3393
Opened 2022-06-25 10:51 UTC by Syed-Ansar

Fixed the height of button in Navbar.

# Light Mode

<img width="1440" alt="Screenshot 2022-06-25 at 4 15 31 PM" src="https://user-images.githubusercontent.com/82027712/175770331-e7c92ed6-3e15-486f-b732-21554f78e16c.png">

# Dark Mode

<img width="1440" alt="Screenshot 2022-06-25 at 4 15 26 PM" src="https://user-images.githubusercontent.com/82027712/175770354-8bf4db96-7779-466f-9e8b-52599a886297.png">

2022-06-25 10:57 UTC, withshubh commented
@Syed-Ansar - Thanks for contributing. 🎉 
Your PR will be reviewed soon.

2022-06-28 08:03 UTC, gsmithun4 requested changes

2022-06-28 08:20 UTC, Syed-Ansar commented on frontend/src/_styles/theme.scss
> +.organization-list a{
Yes added @gsmithun4 . I haven't noticed as it is scss. Thank you.

2022-07-11 11:12 UTC, gsmithun4 requested changes
![Screenshot 2022-07-11 at 4 41 00 PM](https://user-images.githubusercontent.com/3417097/178251891-d72763ab-780e-4291-b47b-c496c884f063.png)
Horizontal line is broken

2022-07-13 21:45 UTC, withshubh commented
Hey @Syed-Ansar 
Can you please update the PR with the requested changes?

2022-07-31 10:45 UTC, withshubh commented
Hey @Syed-Ansar 
Please update the PR with the suggested changes.

2022-08-18 07:31 UTC, withshubh commented
Closing the PR as there was no update for more than a month.

2022-08-18 07:31 UTC, closed without merging