Chore: [Improvement] Leftsidebar inspector
ToolJet/ToolJet pull request #3407
Opened 2022-06-27 17:32 UTC by arpitnath

2022-06-28 08:44 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Cases<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Cases | Steps | Result
-- | -- | --
Should be able to view the data types. | Create an application. | Application is created.
  | Create a run js query with return new Date(). | The query is created.
  | Click on create & run. | The query is created and is run.
  | Click on the leftside bar inspector. | The inspector is opened.
  | Click on the queries & then on runjs1. | The data type is displayed.
Should be able to toggle with node labels along with the node indicator(arrow). | Create an application. | Application is created.
  | Drag and drop few widgets on canvas. | The widgets are dropped.
  | Click on the leftside bar inspector. | The inspector is opened.
  | Click on the widget labels or arrow before it. | The widget on the canvas is selected.
Should be able to alphabetically sort widgets. | Create an application. | Application is created.
  | Drag and drop few widgets on canvas and change the name of some widgets. | The widgets are dropped & name is changed for few widgets.
  | Click on the leftside bar inspector. | The inspector is opened.
  | Click on the components. | The widgets are alphabetically sorted.
Should be able to alphabetically sort queries. | Create an application. | Application is created.
  | Create some queries & change name of the queries. | Some queries are created with some name changed.
  | Click on the leftside bar inspector. | The inspector is opened.
  | Click on queries. | Queries are sorted alphabetically.

<!--EndFragment-->
</body>
</html>

2022-07-04 11:21 UTC, shubh22 commented
Task linked: [CU-2h1aahr Inspector Improvements](https://app.clickup.com/t/2h1aahr)

2022-07-08 12:16 UTC, sherfin94 requested changes
Hey @arpitnath , sorry for the delayed review, functionality looks fine, please resolve conflicts and then ping me and I'll merge it.

2022-07-11 09:35 UTC, sherfin94 approved these changes

2022-07-11 09:35 UTC, merged