feat: image type on table cell, added
ToolJet/ToolJet pull request #3417
Opened 2022-06-28 09:15 UTC by saxenashivang

Some use case would be to display an image in a table cell.

2022-07-05 03:50 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Table/Table.jsx
> +                  onClick={() => fireEvent('onClick')}
@sherfin94 Can you check this? Do we need `onClick` event for the image?

2022-07-08 12:34 UTC, sherfin94 requested changes
Hey @saxenashivang , thank you so much for the PR!

Presently, the image border seems to be set to rounded shape, would it be possible for you to make it customisable? That is, with different border types similar to that of the Image widget. You can edit how the column configuration popover on file `frontend/src/Editor/Inspector/Components/Table.jsx`

<img width="412" alt="image" src="https://user-images.githubusercontent.com/20333972/177992903-236e73e8-2118-493d-ac47-7d19b60b2d89.png">

2022-07-13 21:48 UTC, withshubh commented
@saxenashivang - Please make the required changes in the PR.

2022-07-31 10:44 UTC, withshubh commented
Hey @saxenashivang 👋 
I hope you're doing good. Can you please update the PR with the suggested changes ?

2022-08-09 10:48 UTC, shubh22 commented
Task linked: [CU-2p7cv60 feat: image type on table cell, added #3417](https://app.clickup.com/t/2p7cv60)

2022-11-14 07:03 UTC, withshubh commented
Closing the PR. ref:
- https://github.com/ToolJet/ToolJet/pull/4547

2022-11-14 07:03 UTC, closed without merging