[Improvement] Dragging ability of inspector popover
ToolJet/ToolJet pull request #3432
Opened 2022-06-29 09:49 UTC by arpitnath

2022-07-04 11:24 UTC, shubh22 commented
Task linked: [CU-2hcxyvh Able to Drag and Reposition the LeftSidebar popover](https://app.clickup.com/t/2hcxyvh)

2022-07-05 03:15 UTC, kavinvenkatachalam requested changes
@arpitnath Few findings

- I moved the inspector and resized it. Then when I try to expand the items, the content overflows out of the parent window. 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/50441969/177241941-9db4ec14-a148-48ac-a1a0-c471b57a90d1.png">

- Opened `CodeHinter` in a popup and tried opening an `Inspector` nothing happens

2022-07-05 03:15 UTC, kavinvenkatachalam commented on frontend/src/_styles/theme.scss
> +    // z-index: 1;
If not needed, Could you please remove this?

2022-07-12 08:10 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Cases<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Cases | Steps | Result
-- | -- | --
Should be able to move inspector. | Create an application | Application gets created.
  | Click on inspector. | Inspector opens up.
  | Drag anywhere on the screen. | Inspector is dragged.
Should be able to close inspector. | Create an application | Application gets created.
  | Click on inspector. | Inspector opens up.
  | Click on cross button. | The inspector is closed.
Should be able to view inspector in light mode. | Create an application | Application gets created.
  | Click on inspector. | Inspector opens up.
  | Observe. | Inspector is clearly visible.
Should be able to view inspector in dark mode. | Create an application | Application gets created.
  | Click on dark mode icon. | Application is visible in dark mode
  | Click on inspector. | Inspector opens up.
  | Observe. | Inspector is clearly visible.
Should be able to expand the inspector popover. | Create an application | Application gets created.
  | Click on inspector. | Inspector opens up.
  | Expand the popover. | Inspector popover is expanded correctly.
Should be able to drag inspector popover. | Create an application | Application gets created.
  | Click on inspector. | Inspector opens up.
  | Drag inspector popover. | Inspector pop over is dragged anywhere on the screen.

<!--EndFragment-->
</body>
</html>

2022-07-13 02:33 UTC, kavinvenkatachalam requested changes
@arpitnath Few findings and suggestions

- Opened the `Inspector` and without closing it I opened the `CodeHinter` in a popup. Then I closed the `CodeHinter` and tried opening the `Inspector`, but I don't see the `Inspector`
- You can see in the screenshot that if I try to expand multiple components then it goes beyond the viewport height and when I try to scroll, the page header is not fixed. (Suggestion - Can we add a fixed height to the `Inspector` and enable the overflow to it?) cc: @sherfin94 
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/50441969/178638376-5d8cf720-c56d-4d6d-9493-91ccafe29736.png">

2022-07-13 07:39 UTC, kavinvenkatachalam approved these changes
LGTM

2022-07-19 07:03 UTC, sherfin94 requested changes
Hey @arpitnath , I'm not able to keep the inspector open and make changes at the same time. This feature is heavily used to see data changes in real time when components are interacted with.

2022-12-13 05:20 UTC, closed without merging