feat: trigger mail when user is mentioned in comment
ToolJet/ToolJet pull request #3443
Opened 2022-06-30 07:04 UTC by gondar00

fixes: #3442

2022-07-06 09:15 UTC, gsmithun4 requested changes

2022-07-06 09:55 UTC, gondar00 commented on server/src/services/comment.service.ts
> +      console.log(error);
Updated with `InternalServerErrorException`

2022-07-07 06:55 UTC, shubh22 commented
Task linked: [CU-2h1aq0e Create comment notifications](https://app.clickup.com/t/2h1aq0e)

2022-07-13 05:32 UTC, gsmithun4 commented on frontend/src/_ui/Mentions/index.js
> +        // regex={/@(\S+)/}
Shall we remove the commented codes?

2022-07-14 12:56 UTC, gsmithun4 approved these changes
LGTM

2022-07-25 05:44 UTC, merged