added component-specific action to set and clear value
ToolJet/ToolJet pull request #3487
Opened 2022-07-05 15:32 UTC by manishkushare

Resolve #3486

2022-07-05 15:35 UTC, shubh22 commented
Task linked: [CU-2hjhvp6 Text Input](https://app.clickup.com/t/2hjhvp6)

2022-07-12 13:13 UTC, manishkushare commented
@sherfin94 , updated the suggested change

2022-07-14 11:53 UTC, sherfin94 requested changes
Hey @manishkushare , please also make sure that the on Change event is fired for both actions, on the `then` of their corresponding `setExposedVariable` calls.

2022-07-15 10:23 UTC, sherfin94 approved these changes

2022-07-15 10:23 UTC, merged