[docs] how-to: run `actions` from RunJS
ToolJet/ToolJet pull request #3602
Opened 2022-07-12 20:54 UTC by withshubh

#### Changes
- Added how-to guide on triggering actions from RunJS query

2022-07-12 20:55 UTC, withshubh commented
https://app.clickup.com/t/2hxxcdf

2022-07-12 20:56 UTC, shubh22 commented
Task linked: [CU-2hxxcdf Documentation for how actions can be run from RunJS](https://app.clickup.com/t/2hxxcdf)

2022-07-13 05:18 UTC, stepinfwd requested changes

2022-07-13 05:18 UTC, stepinfwd commented on docs/docs/how-to/run-action-from-runjs.md
> +actions.setLocalStorage('key':'value')
actions.setLocalStorage('key' , 'value')

2022-07-14 02:08 UTC, merged

2022-08-24 21:03 UTC, shubh22 commented
Task linked: [CU-2juq0q0 [docs] how-to: run `actions` from RunJS](https://app.clickup.com/t/2juq0q0)