Centred time picker ui when datetime widget is time only
ToolJet/ToolJet pull request #3611
Opened 2022-07-13 14:17 UTC by Nathan-Bisson

Fixes #3578

2022-07-14 02:13 UTC, kavinvenkatachalam requested changes
@Nathan-Bisson Thank you for the PR! 

Few suggestions,

- As the classname is nested within the parent and it takes higher precedence compared to just the classname. So,`important` is not needed.
- The child element overflows out of the parent when adding `padding-right`. So, fixed `width` can be used instead of `padding-right`
<img width="220" alt="image" src="https://user-images.githubusercontent.com/50441969/178883111-36cc4de0-1a3f-4fa5-bf7e-ae76b0221260.png">

2022-07-14 12:44 UTC, Nathan-Bisson commented on frontend/src/_styles/custom.scss
>  }
Hey Kavin, thank you for the feedback! I've updated my changes accordingly.

2022-07-15 02:38 UTC, kavinvenkatachalam approved these changes
LGTM

2022-07-25 08:31 UTC, sherfin94 approved these changes

2022-07-25 08:31 UTC, merged