[Bug fix] : FIlePicker - if Parse content is disabled, the "File type" dropdown should be hidden
ToolJet/ToolJet pull request #3622
Opened 2022-07-15 11:40 UTC by manishkushare

Resolve #3621
Fixed: If Parse content is disabled, the "File type" dropdown should be hidden

2022-07-18 06:05 UTC, shubh22 commented
Task linked: [CU-2kbkz8p If Parse content is disabled,  "File type" dropdown should be hidden and don't parse the data](https://app.clickup.com/t/2kbkz8p)

2022-07-19 10:47 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Case<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Cases | Steps | Result
-- | -- | --
Should not be able to see file types while parse content is disabled | Create an application. | Application gets created.
  | Drag and drop file picker. | File picker is displayed on the canvas.
  | Go to parse content in properties. | Parse content is visible.
  | Toggle to disable parse content. | The file type is hidden.

<!--EndFragment-->
</body>
</html>

2022-07-28 07:39 UTC, arpitnath commented on frontend/src/Editor/Inspector/Components/FilePicker.jsx
>      const conditionalOptions = [{ name: 'parseFileType', condition: parseContent }];
Can we check the condition here: 
`const conditionalOptions = [{ name: 'parseFileType', condition: parseContent === '{{true}}' }];`

2022-07-28 07:40 UTC, arpitnath requested changes

2022-07-28 07:40 UTC, arpitnath commented on frontend/src/Editor/Inspector/Components/FilePicker.jsx
> +      if (condition === '{{true}}') renderOptions.push(renderCustomElement(name));
And remove this?

2022-07-28 07:40 UTC, arpitnath commented on frontend/src/Editor/Inspector/Components/FilePicker.jsx
>      const conditionalOptions = [{ name: 'parseFileType', condition: parseContent }];
Can we check the condition here:
const conditionalOptions = [{ name: 'parseFileType', condition: parseContent === '{{true}}' }];

2022-07-28 09:08 UTC, shubh22 commented
Task linked: [CU-2mtjqb9 Filepicker: [Bugfix]](https://app.clickup.com/t/2mtjqb9)

2022-07-28 11:15 UTC, arpitnath submitted a review, later dismissed
LGTM!

2022-08-03 12:50 UTC, sherfin94 requested changes
One issue reported on code, please check

2022-08-03 12:50 UTC, sherfin94 commented on frontend/src/Editor/Inspector/Components/FilePicker.jsx
> +    const conditionalOptions = [{ name: 'parseFileType', condition: parseContent === '{{true}}' }];
If `parseContent` is programmatically configured (eg: `variables.someVariable > 33.3`), this condition will be erroneous won't it?

Resolve it using resolveReferences and then check if it is `true`.

2022-08-04 12:11 UTC, manishkushare commented
@sherfin94 , Made the suggested changes.

2022-08-18 05:34 UTC, kavinvenkatachalam reviewed
Suggestion - Unless the value of `component.definition.properties.parseContent?.value` is undefined, `resolveWidgetFieldValue` function will be called. Can we re-write it in a single line?
cc: @sherfin94 @arpitnath

2022-08-18 05:38 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/FilePicker.jsx
> +  parseContent = typeof parseContent !== 'boolean' ? resolveWidgetFieldValue(parseContent, currentState) : false;
```suggestion
  const parseContent = resolveWidgetFieldValue(component.definition.properties.parseContent?.value ?? false, currentState);
```

2022-08-19 07:06 UTC, manishkushare commented
@kavinvenkatachalam , made the requested changes

2022-08-19 07:21 UTC, kavinvenkatachalam approved these changes
LGTM

2022-08-24 08:47 UTC, sherfin94 approved these changes

2022-08-24 08:53 UTC, merged

2022-09-28 08:39 UTC, shubh22 commented
Task linked: [CU-2k0aqfh File Picker Updates: Improvements and Bugfixes](https://app.clickup.com/t/2k0aqfh)