Fixed over-flow bug on widgets with longer names
ToolJet/ToolJet pull request #3638
Opened 2022-07-19 10:12 UTC by UtkarshDixit-py

2022-07-19 10:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3638) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3638) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=3638) it.</sub>

2022-07-19 12:02 UTC, withshubh commented
Hey @UtkarshDixit-py 
Can you please check all the widgets on ToolJet cloud and fix whichever widget is having this issue as I can see you have fixed the issue with two widgets in this PR.
The PR is supposed to fix this issue completely so that it doesn't happen with any widget in the future.

2022-08-04 15:17 UTC, UtkarshDixit-py commented
@stepinfwd Does this need any other changes?

2022-08-07 20:40 UTC, stepinfwd commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +      width: 8,
revert this line , CircularProgressBar size doesn't need any change

2022-08-07 20:42 UTC, stepinfwd commented
> @stepinfwd Does this need any other changes?

mentioned one change rest looks good @UtkarshDixit-py

2022-08-08 05:11 UTC, UtkarshDixit-py commented
Hey @stepinfwd i made the mentioned change

2022-08-08 08:45 UTC, stepinfwd approved these changes
LGTM @Navaneeth-pk 

https://user-images.githubusercontent.com/31006028/183377806-65a2ac21-ded8-48c9-83d2-228fbb23337c.mov

2022-08-08 08:48 UTC, stepinfwd commented
> Hey @stepinfwd i made the mentioned change

There are lint issues can you fix that too @UtkarshDixit-py

2022-08-08 10:55 UTC, UtkarshDixit-py commented
> > Hey @stepinfwd i made the mentioned change
> 
> There are lint issues can you fix that too @UtkarshDixit-py

I don't know how to debug this linting issue

2022-08-08 11:03 UTC, stepinfwd commented
> > > Hey @stepinfwd i made the mentioned change
> > 
> > 
> > There are lint issues can you fix that too @UtkarshDixit-py
> 
> I don't know how to debug this linting issue

cc: @arpitnath

2022-08-10 18:20 UTC, arpitnath requested changes
On renaming any widget, the app freezes!
Will remove the tag `do not merge` after this is fixed.
cc: @Navaneeth-pk

2022-08-10 18:38 UTC, arpitnath commented
@UtkarshDixit-py,
Simply determine the config-handler's width with respect to the length of the component's name.


File: **/frontend/src/Editor/ConfigHandle.jsx**


https://user-images.githubusercontent.com/67645175/183990961-59554a28-e1b3-4f6a-bd9c-02e43b95a806.mov

2022-08-12 06:04 UTC, UtkarshDixit-py commented
> @UtkarshDixit-py, Simply determine the config-handler's width with respect to the length of the component's name.
> 
> File: **/frontend/src/Editor/ConfigHandle.jsx**
> 
>  Screen.Recording.2022-08-11.at.12.01.01.AM.mov

Okay sure

2022-09-28 10:43 UTC, withshubh commented
Hey @UtkarshDixit-py 👋 
Are you working on it?

2022-10-04 21:57 UTC, arpitnath commented
Closing this PR, as the issue is re-assign to someone else.
cc: @withshubh

2022-10-04 21:57 UTC, closed without merging