Bug Fixed : request confirmation before running keeps showing loader, when click cancel
ToolJet/ToolJet pull request #3641
Opened 2022-07-19 12:15 UTC by manishkushare

Resolve #3640

2022-07-19 12:16 UTC, shubh22 commented
Task linked: [CU-2kbnc3q Bug in Request confirmation before running query](https://app.clickup.com/t/2kbnc3q)

2022-07-20 12:31 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Cases<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Cases | Steps | Result
-- | -- | --
Should not be able to show a loader on save & run query  while clicked on cancel. | Create an application. | Application gets created.
  | Click on add new query. | Different datasource is displayed.
  | Click on any datatsource. | Query page for datasource is displayed.
  | Go to advanced. | Advanced page is displayed.
  | Toggle on request confirmation before running query. | The request for confirmation before running query is toggled on.
  | Click on create an run. | The pop up for confirmation is displayed.
  | Click on cancel. | There is no loader on create and run.
Should be able to show loader on create & run or save & run. | Create an application. | Application gets created.
  | Click on add new query. | Different datasource is displayed.
  | Click on any datatsource. | Query page for datasource is displayed.
  | Toggle off request confirmation before running query. | The request for confirmation before running query is toggled off.
  | Go to general. | General page for query is displayed.
  | Click on create & run or save & run. | The loader is displayed until it is created & run or saved & run.

<!--EndFragment-->
</body>
</html>

2022-07-26 04:32 UTC, kavinvenkatachalam requested changes
@manishkushare Minor changes, we're not using the `showQueryConfirmation` in the file other than checking it in `componentWillReceiveProps`. So, we can make use of props and the state can be removed

2022-07-26 04:32 UTC, kavinvenkatachalam commented on frontend/src/Editor/QueryManager/QueryManager.jsx
> +        showQueryConfirmation: props.showQueryConfirmation,
This line can be removed. We're not using the state anywhere in the file

2022-07-26 04:32 UTC, kavinvenkatachalam commented on frontend/src/Editor/QueryManager/QueryManager.jsx
> +    const { appId, options, selectedDataSource, mode, queryName, shouldRunQuery, showQueryConfirmation } = this.state;
```suggestion
    const { appId, options, selectedDataSource, mode, queryName, shouldRunQuery } = this.state;
```

2022-07-26 04:32 UTC, kavinvenkatachalam commented on frontend/src/Editor/QueryManager/QueryManager.jsx
> +      showQueryConfirmation,
```suggestion
```

2022-07-26 06:16 UTC, manishkushare commented
@kavinvenkatachalam , updated the PR with suggested changes, please take a look at it, whenever possible.

2022-07-26 06:18 UTC, kavinvenkatachalam approved these changes

2022-08-03 11:04 UTC, merged