added validation on group name
ToolJet/ToolJet pull request #3657
Opened 2022-07-22 20:06 UTC by mazkaaa

Resolves https://github.com/ToolJet/ToolJet/issues/3147

2022-07-29 13:46 UTC, gsmithun4 requested changes

2022-07-29 13:46 UTC, gsmithun4 commented on frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
> +    if (!this.state.newGroupName.match(/(?!^ +$)^.+$/)) {
the validation should be done in back-end also

2022-08-09 09:46 UTC, withshubh commented
Hey @mazkaaa - Please update the PR with suggested changes.

2022-11-09 11:02 UTC, shubh22 commented
Incomplete solution and contributor not responding for over 3 months. Hence closing this.

2022-11-09 11:02 UTC, closed without merging