[[ Enhancement ]]: FilePicker - added  onFileLoaded and onFileDeselected events
ToolJet/ToolJet pull request #3673
Opened 2022-07-26 08:03 UTC by manishkushare

Resolve #3672

2022-07-28 10:00 UTC, arpitnath commented
@manishkushare 
When we attach an action to the `On File Loaded` event, the action is not triggered. 
https://www.loom.com/share/e22ec42bb5dc4b27a87d9c20ffc1f28d

2022-07-28 11:09 UTC, arpitnath requested changes

2022-07-28 11:09 UTC, arpitnath commented on frontend/src/Editor/Components/FilePicker.jsx
> +        .then(() => onEvent('onFileLoaded ', { component }));
There is an extra white space at the end of the **eventName**, 
`frontend/src/_helpers/appUtils.js :: 488-518` return `false` and the action is not been executed.

2022-07-28 11:27 UTC, arpitnath approved these changes
LGTM!

2022-08-02 11:27 UTC, Nandinisaha13 commented
<html>
<body>
<!--StartFragment--><google-sheets-html-origin>Test Case<!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}-->

Test Case | Steps | Result
-- | -- | --
Should be able to show alert(info) while file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select alert type as info. | Alert type info is selected.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | Alert(ifo) is displayed.
Should be able to show alert(sucess) while file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select alert type as success. | Alert type success is selected.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | Alert(success) is displayed.
Should be able to show alert(warning) while file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select alert type as warning. | Alert type warning is selected.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | Alert(warning) is displayed.
Should be able to show alert(danger) while file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select alert type as danger. | Alert type danger is selected.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | Alert(danger) is displayed.
Should be able to logout when file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select logout as action. | Logout is selected.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | User is logged out.
Should be able to run query when file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Create a query. | Query is created.
  | Select file picker. | File picker is selected.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select run query as action & select the above query. | Run query is selected & the above query is selected in query field.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | The query is successfully executed.
Should be able to open webpage when file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Select file picker. | File picker is selected.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select open webpage in action & enter the url. | Open webpage is selected & url is entered.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | The webpage is opened.
Should be able to open another application when file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Select file picker. | File picker is selected.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select go to app in action & select app name. | Go to app is selected & app name is selected.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | Pop up is opened for confirmation for triggering the application.
  | Click open. | Application is displayed.
Should be able to open modal when file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Drag & drop modal. | Modal is displayed.
  | Select file picker. | File picker is selected.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select open modal & select modal name. | Open modal is selected & modal name is selected.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | Modal is opened.
Should be able to close modal when file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Drag & drop modal. | Modal is displayed.
  | Select file picker. | File picker is selected.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select open modal & select modal name. | Open modal is selected & modal name is selected.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | Modal is opened.
  | Drag & drop fliepicker inside the modal. | Filepicker is displayed inside the modal.
  | Select file picker. | File picker is selected.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select close modal & select modal name. | close modal is selected & modal name is selected.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | Modal is closed.
Should be able to copy to clipboard when file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Select file picker. | File picker is selected.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select copy to clipboard in action & enter text. | Copy to clipboard is selected & text is entered.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | File is loaded. | Text is copied to clipboard.
Should be able to set local storage when file is loaded. | Create an application. | Application gets created.
  | Drag & drop file picker. | File picker is displayed on the canvas.
  | Drag & drop text input & text widget. | Text & text input is displayed.
  | Select file picker. | File picker is selected.
  | Go to event handler. | Event handler is displayed.
  | Click on +Add Handler. | Event handler with action type as alert is displayed.
  | Select set local storage in action & enter key & value. | Set local storage is selected & key & value is entered.
  | Enter {{localStorage.getItem('name')}}. | Entered.
  | Click on file picker. | Browse is opened.
  | Select a file & click open. | File is being loaded.
  | Fi [...]

2022-08-03 12:40 UTC, sherfin94 approved these changes

2022-08-03 12:41 UTC, merged