Cypress test for dashboard, app and folder CRUD operations
ToolJet/ToolJet pull request #3677
Opened 2022-07-26 13:58 UTC by ajith-k-v

Fixes: #3531
<img width="1440" alt="Screenshot 2022-07-26 at 7 22 27 PM" src="https://user-images.githubusercontent.com/20367957/181023950-3152ad63-9601-4465-880f-326d86acceb8.png">

2022-07-28 04:18 UTC, emidhun requested changes
@ajith-k-v Please look at the comments and add modifications according to our last day's discussion.
Please let me know if you need any assistance from my side.
Thank you.

2022-07-28 04:18 UTC, emidhun commented on cypress-tests/cypress/e2e/dashboard/dashboard.cy.js
> +    logout();
Please let me know why we are using this logout.

2022-07-28 04:18 UTC, emidhun commented on cypress-tests/cypress/e2e/dashboard/dashboard.cy.js
> +    cy.wait(1000);
I think we can remove this hardcoded wait.

2022-08-01 03:27 UTC, emidhun reviewed
@ajith-k-v Can we add a custom assertion/method to validate visibility with any other attribute?

2022-08-03 03:46 UTC, ajith-k-v commented
@emidhun Will work on that

2022-08-04 11:28 UTC, emidhun approved these changes
<img width="1356" alt="Screenshot 2022-08-04 at 4 57 50 PM" src="https://user-images.githubusercontent.com/20367955/182836280-c7f40c97-9a88-4138-9e0d-f44f8a434b57.png">
@ajith-k-v Looking good to me.
Thank you.

2022-08-04 15:10 UTC, sherfin94 approved these changes

2022-08-04 15:10 UTC, merged