table-datepicker timezone function added
ToolJet/ToolJet pull request #3724
Opened 2022-08-03 04:18 UTC by developer-honoru

table-datepicker timezone function adde
![Aug-02-2022 21-44-47](https://user-images.githubusercontent.com/33475816/182523085-17668587-8b13-424b-83bb-e83570e6f61a.gif)

2022-08-03 04:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3724) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3724) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=3724) it.</sub>

2022-08-04 08:27 UTC, sherfin94 requested changes
Hey @developer-honoru , thank you for the pull request. There seems to a bug, whenever I select datepicker the table goes to error boundary as it receives some sort of exception. I'm attaching relevant screenshots and app export file.

[table-datepicker-bug-export-1659601335171.json.zip](https://github.com/ToolJet/ToolJet/files/9257946/table-datepicker-bug-export-1659601335171.json.zip)

https://user-images.githubusercontent.com/20333972/182799683-5e4480a8-7058-4cac-a00e-83da282dc5e2.mov

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20333972/182799802-8c0da1b7-4a9d-4116-9007-f2e22efe38eb.png">

2022-08-04 12:16 UTC, developer-honoru commented
As you said, there was a missing variable. Sorry. @sherfin94 

<img width="564" alt="image" src="https://user-images.githubusercontent.com/33475816/182844548-414f4397-2012-41bd-8994-3255028b9bd4.png">

2022-08-08 10:58 UTC, sherfin94 approved these changes

2022-08-08 11:02 UTC, merged