[Bugfix] On deleting any child widget from the listview widget, removes the widget from the editor and from the currentState
ToolJet/ToolJet pull request #3740
Opened 2022-08-04 10:55 UTC by arpitnath

Resolves #3680

2022-08-04 11:17 UTC, shubh22 commented
Task linked: [CU-2me44w5 Listview: deleting any child widget from the listview widget, deletes the widget from the editor but not from the currrentState until we reload the page](https://app.clickup.com/t/2me44w5)

2022-08-09 14:38 UTC, sherfin94 requested changes
Putting ListView inside ListView crashes.

2022-08-18 03:28 UTC, kavinvenkatachalam requested changes
@arpitnath The `exposedVariable` is an object and the reference keeps on changing every time and causing multiple re-renders. Instead of adding a custom hook and counting the number of renders, stringify the `exposedVariable` in the `useEffect` dependency array.

2022-08-18 03:28 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Listview.jsx
> +  }, [exposedVariables]);
```suggestion
  useEffect(() => {
    if (!_.isEqual(exposedVariables.data, childrenData)) {
      setExposedVariable('data', childrenData);
    }

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(exposedVariables)]);
```

2022-08-22 03:28 UTC, kavinvenkatachalam commented
@arpitnath I tried the same as you described in the issue. Seems like `LeftSideBarInspector` is not getting updated after deleting the listItem. Can you check it out?

2022-08-23 03:30 UTC, kavinvenkatachalam commented
> Putting ListView inside ListView crashes.

@arpitnath This issue still exists. Can you please take a look?

2022-08-23 03:31 UTC, kavinvenkatachalam requested changes
Listview crashes when the listview is dropped into it

2022-08-24 07:29 UTC, arpitnath commented
@kavinvenkatachalam Putting this PR on hold for now.
cc: @sherfin94 @shubh22

2022-12-13 05:21 UTC, closed without merging