[docs] added missing actions in action reference
ToolJet/ToolJet pull request #3759
Opened 2022-08-08 03:37 UTC by withshubh

#### Changes
- Added missing docs - show modal, close modal, run query, set var, unset var etc
- updated organization to workspace in sidebar

2022-08-12 09:42 UTC, withshubh commented on docs/docs/actions/control-component.md
> +
```suggestion
```

2022-08-12 09:44 UTC, shubh22 commented
Task linked: [CU-2me529w CSA Documentaion](https://app.clickup.com/t/2me529w)

2022-08-16 05:04 UTC, withshubh commented
@kavinvenkatachalam Please review the CSA doc (Control Component Action)

2022-08-16 06:06 UTC, kavinvenkatachalam requested changes
@withshubh I guess you missed out `FilePicker` CSA in the `control-component.md` . Can you please check and add it?

2022-08-16 06:22 UTC, withshubh commented on docs/docs/actions/control-component.md
> +| Color picker   | Set color |
```suggestion
| Color picker   | Set color |
| File picker    | Clear files |
```

2022-08-16 06:25 UTC, withshubh commented
Added file picker CSA @kavinvenkatachalam

2022-08-16 06:31 UTC, kavinvenkatachalam approved these changes
LGTM

2022-08-18 02:28 UTC, merged