Bug fixed : If Google & GitHub signup is disabled there shouldn’t be the ------OR-------
ToolJet/ToolJet pull request #3766
Opened 2022-08-08 10:40 UTC by manishkushare

Resolved

2022-08-08 10:40 UTC, shubh22 commented
Task linked: [CU-2p1frkb SignUP card UI has an extra 'OR'.](https://app.clickup.com/t/2p1frkb)

2022-08-08 13:04 UTC, gsmithun4 requested changes

2022-08-08 13:04 UTC, gsmithun4 commented on frontend/src/SignupPage/SignupPage.jsx
> +                    {this.ssoConfigs.configs?.git?.enabled && this.ssoConfigs.configs?.google?.enabled && (
should be or condition, if google or git is enabled, or text should be shown
```suggestion
                    {this.ssoConfigs.configs?.git?.enabled || this.ssoConfigs.configs?.google?.enabled && (
```

2022-08-09 04:47 UTC, gsmithun4 approved these changes
LGTM

2022-08-09 04:49 UTC, merged