[ Feature ] :: on drag open widget manager
ToolJet/ToolJet pull request #3775
Opened 2022-08-10 12:13 UTC by stepinfwd

closes #3637

2022-08-10 12:20 UTC, shubh22 commented
Task linked: [CU-2khdu15 [ Feature ] :: Automatically selecting properties on dropping widget to canvas](https://app.clickup.com/t/2khdu15)

2022-08-11 03:27 UTC, kavinvenkatachalam commented on frontend/src/Editor/Container.jsx
> +  }));
```suggestion
```

2022-08-11 03:34 UTC, kavinvenkatachalam reviewed
@stepinfwd Why do we need `useImperativeHandle`?

2022-08-16 09:19 UTC, kavinvenkatachalam requested changes
@stepinfwd It's not working when I drop the widget into a container or tabs. Can you check it?

2022-08-22 07:32 UTC, kavinvenkatachalam requested changes
@stepinfwd After merging the latest develop, it breaks the app when I drop a listview.

2022-09-12 03:07 UTC, kavinvenkatachalam commented
Closing this PR as [new PR](https://github.com/ToolJet/ToolJet/pull/4013) is raised for the issue

2022-09-12 03:07 UTC, closed without merging