Cypress test for button widget happy path
ToolJet/ToolJet pull request #3776
Opened 2022-08-10 13:32 UTC by ajith-k-v

Fixes: #3694
<img width="1440" alt="Screenshot 2022-08-10 at 6 48 47 PM" src="https://user-images.githubusercontent.com/20367957/183913835-bcc81375-af7d-4b18-905b-fdc67b55b506.png">

2022-08-10 13:37 UTC, ajith-k-v commented
Multi-select widget happy path

<img width="1440" alt="Screenshot 2022-08-10 at 7 04 56 PM" src="https://user-images.githubusercontent.com/20367957/183915096-931b1d40-5685-4e71-8193-fc5f1386ee3f.png">

2022-08-11 08:50 UTC, emidhun requested changes
I think we can add verification of widget form preview as well.
Thank you.

2022-08-17 06:26 UTC, ajith-k-v commented
@emidhun Added the widget verification from preview. Please review

2022-08-24 04:57 UTC, emidhun requested changes
PR looks good, I think we can add the changes we discussed.
Please let me know if I can do something.

2022-08-24 04:57 UTC, emidhun commented on cypress-tests/cypress/constants/texts/button.js
>    buttonProperties: "Properties",
I think we can move commonly used labels to commonTexts.

2022-08-24 04:57 UTC, emidhun commented on cypress-tests/cypress/support/utils/button.js
> +export const openButtonStylesEditorSideBar = (widgetText, widgetName) => {
I think we can use the common methods to open the sidebar by modifying the `data-cy` of the button.

2022-09-01 04:14 UTC, emidhun commented on cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
> +      data.colourHex
I think we can use a different color for each color field.
We can assign different values for `data.colourHex`

2022-09-01 05:21 UTC, ajith-k-v commented
@emidhun Added review changes. Please review 

<img width="1440" alt="Screenshot 2022-09-01 at 10 50 41 AM" src="https://user-images.githubusercontent.com/20367957/187837250-1007b714-b17d-484c-a213-ad2356c0e27d.png">

2022-09-01 05:30 UTC, emidhun approved these changes
LGTM

2022-09-05 08:36 UTC, merged