[docs]: Table widget info update
ToolJet/ToolJet pull request #3824
Opened 2022-08-19 08:17 UTC by shivangT

- Added information about custom validations
- Removed minor text. bug in password input doc

2022-08-19 08:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3824) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=3824) before we can accept your contribution.<br/><hr/>**Shivang Tiwari** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=3824) it.</sub>

2022-08-24 01:37 UTC, shivangT commented
Hey @arpitnath, 
As we discussed the other day, Please review the descriptions updated for cell types.

2022-08-25 08:13 UTC, arpitnath requested changes

2022-09-06 13:38 UTC, arpitnath approved these changes

2022-09-07 09:28 UTC, shivangT commented
@Navaneeth-pk 
This can be closed as well.

2022-09-07 10:54 UTC, withshubh approved these changes

2022-09-23 17:43 UTC, merged