[Fixed] Bug: User can reset their password with a space
ToolJet/ToolJet pull request #3825
Opened 2022-08-19 09:20 UTC by shah21

Resolves #3335

2022-08-19 09:40 UTC, shubh22 commented
Task linked: [CU-2quvpzq [Bug] Password reset: accepting blank space as a password](https://app.clickup.com/t/2quvpzq)

2022-08-23 06:55 UTC, gsmithun4 requested changes

2022-08-23 06:55 UTC, gsmithun4 commented on server/src/dto/app-authentication.dto.ts
> +  @Transform(({ value }) => value.trim())
```suggestion
  @Transform(({ value }) => value?.trim())
```
to avoid error if value is empty

2022-08-23 12:40 UTC, gsmithun4 approved these changes
LGTM

2022-08-26 05:34 UTC, merged