Bug Fixed : Success message not displayed clearly in dark mode in advanced option for queries
ToolJet/ToolJet pull request #3861
Opened 2022-08-24 16:04 UTC by manishkushare

Resolves #3714

2022-08-24 16:06 UTC, shubh22 commented
Task linked: [CU-2r6akd9 Success message not displayed clearly in dark mode in advanced option for queries](https://app.clickup.com/t/2r6akd9)

2022-08-25 02:30 UTC, kavinvenkatachalam requested changes
@manishkushare The text is not vertically aligned with `p-0`. Can we replace it with `p-1` class?

<img width="182" alt="image" src="https://user-images.githubusercontent.com/50441969/186560154-ebb7d905-a2c3-4980-8722-d8674d8be84c.png">

2022-08-25 02:30 UTC, kavinvenkatachalam commented on frontend/src/Editor/QueryManager/QueryManager.jsx
> +                          className="form-control p-0"
```suggestion
                          className="form-control p-1"
```

2022-08-25 11:41 UTC, kavinvenkatachalam approved these changes

2022-08-25 11:41 UTC, merged