Bug fix : Container widget background color is not consistent with the dark theme
ToolJet/ToolJet pull request #3866
Opened 2022-08-25 08:56 UTC by manishkushare

Resolves #2649

2022-08-25 08:58 UTC, shubh22 commented
Task linked: [CU-2r6cdzw Container widget does not adapt to the dark theme](https://app.clickup.com/t/2r6cdzw)

2022-08-29 16:17 UTC, arpitnath requested changes
https://user-images.githubusercontent.com/67645175/187246673-57c4cddb-f486-4fc8-a507-b1874e2df89c.mov

@manishkushare If we pick white (#FFFFFF) then the dark mode is not handled.

2022-09-12 05:14 UTC, arpitnath approved these changes
LGTM!

2022-09-12 05:14 UTC, arpitnath commented on frontend/src/Editor/Components/Container.jsx
> +  console.log(styles.backgroundColor);
Can we remove this 😅

2022-09-12 06:45 UTC, manishkushare commented on frontend/src/Editor/Components/Container.jsx
> +  console.log(styles.backgroundColor);
@arpitnath , removed console.log

2022-09-12 06:46 UTC, arpitnath approved these changes

2022-09-12 09:04 UTC, kavinvenkatachalam approved these changes

2022-09-12 09:04 UTC, merged