Bug fixed : List view widget background color is not consistent with the dark theme
ToolJet/ToolJet pull request #3867
Opened 2022-08-25 09:12 UTC by manishkushare

Resolves #2648

2022-08-25 09:14 UTC, shubh22 commented
Task linked: [CU-2r6ck2y List view widget does not adapt to the dark theme](https://app.clickup.com/t/2r6ck2y)

2022-08-29 16:20 UTC, arpitnath requested changes
<img width="1440" alt="Screenshot 2022-08-29 at 9 49 04 PM" src="https://user-images.githubusercontent.com/67645175/187247534-ab3cab0a-05d1-4633-97bc-18f93cd22ed5.png">
@manishkushare 
If we pick white (#FFFFFF) then the dark mode is not handled.

2022-08-29 17:42 UTC, manishkushare commented
@arpitnath , made the suggested changes

2022-09-12 05:57 UTC, arpitnath approved these changes

2022-09-14 08:05 UTC, kavinvenkatachalam approved these changes

2022-09-14 08:06 UTC, merged