[ Bugfix ] :: calendar preview is broken when events are added as a result of any query
ToolJet/ToolJet pull request #3928
Opened 2022-09-01 11:11 UTC by stepinfwd

closes #3927

2022-09-01 11:43 UTC, shubh22 commented
Task linked: [CU-2rx0yd1 calendar preview is broken when events are added as a result of any query](https://app.clickup.com/t/2rx0yd1)

2022-09-02 03:25 UTC, kavinvenkatachalam requested changes
@stepinfwd `typeof` in the array will always be `object`. To check if it is an array, you can use `Array.isArray()`

2022-09-02 03:25 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Calendar.jsx
> +    typeof properties?.events === Array
```suggestion
    Array.isArray(typeof properties?.events)
```

2022-09-06 02:58 UTC, kavinvenkatachalam approved these changes

2022-09-06 02:58 UTC, merged