[docs] ClickHouse
ToolJet/ToolJet pull request #3951
Opened 2022-09-05 07:17 UTC by withshubh

#### changes
- Added clickhouse.md in datasource reference and clickhouse images in static/img

2022-09-05 07:31 UTC, shubh22 commented
Task linked: [CU-2r6bmz5 Clickhouse DB](https://app.clickup.com/t/2r6bmz5)

2022-09-27 19:09 UTC, stepinfwd commented on docs/docs/data-sources/clickhouse.md
> +- **Protocal**
protocol

2022-09-27 19:14 UTC, stepinfwd commented on docs/docs/data-sources/clickhouse.md
> +	:::info
can remove this info

2022-09-27 19:24 UTC, stepinfwd requested changes

2022-09-27 19:24 UTC, stepinfwd commented on docs/docs/data-sources/clickhouse.md
> +	SELECT * FROM test array1 WHERE str='Somethingl...'  1 ALTER TABLE test_array1 UPDATE arr = (12] WHERE str='Somethingl...'
second query is not needed

2022-09-27 19:24 UTC, stepinfwd commented on docs/docs/data-sources/clickhouse.md
> +ToolJet can connect to the ClickHouse databases to read and write data. ClickHouse® is a column-oriented database management system (DBMS) for online analytical processing of queries (OLAP).
**databases

2022-10-08 03:40 UTC, stepinfwd approved these changes

2022-10-10 02:38 UTC, merged