chore: apply primary-color in more places
ToolJet/ToolJet pull request #4025
Opened 2022-09-12 19:16 UTC by pateketrueke

Hi, I was investigating how easily you can change the `$primary` colors from the entire app and I found it's bit hardcoded on many places... so far what I did was replacing it with their proper variables, and also tweaking a bit the css+svgs to use `currentColor` and inherit whatever color the current theme is.

- changes made on SVG icons is for taking into account the `currentColor` property
- Button.jsx now considers if it has a custom background-color, and update its darker hue accordingly
- for widgetConfig.js, I noticed if you leave the `backgroundColor` empty then it'll take the `--tblr-btn-color` as default

IMHO this would help on companys adopting this technology to setup their own primary/accent color on build-time, by just replacing the `$primary-rgb` and `$primary-rgb-darker` variables. However this solutions will not scale well because we're using Sass and we should be able to setup colors un the `:root` instead.

Do you think this PR is worth to merge? Thank you!

2022-09-12 19:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4025) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4025) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=4025) it.</sub>

2022-09-15 05:35 UTC, shivangT commented
Hey @pateketrueke 

Seems like there is a merge conflict in the above-mentioned file. Please quickly resolve this before we review your code. Thanks

2022-09-19 05:48 UTC, gondar00 requested changes

2022-09-19 13:36 UTC, pateketrueke commented on frontend/src/_styles/colors.scss
> +$primary-light: unquote("rgb(#{$primary-rgb})");
It should be using the primary-rgb-darker, sorry for that.

2022-09-28 05:18 UTC, gondar00 submitted a review, later dismissed

2022-09-28 11:56 UTC, gondar00 commented
@pateketrueke could you please fix the merge conflicts

2022-09-29 08:01 UTC, gondar00 approved these changes

2022-09-29 08:03 UTC, merged