Enhancement : [ text input widget ] refactor
ToolJet/ToolJet pull request #4036
Opened 2022-09-14 11:18 UTC by manishkushare

Resolves #4035

2022-09-16 07:22 UTC, shubh22 commented
Task linked: [CU-2u58p8u Text input widget enhancement](https://app.clickup.com/t/2u58p8u)

2022-09-23 09:41 UTC, kavinvenkatachalam requested changes
@manishkushare Few suggestions,

1. Move all the `useState` above and `useEffect` below which will make better readability of the code
2. Move all the register actions inside `useEffect` with corresponding dependencies

2022-09-23 09:41 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/TextInput.jsx
> +  });
```suggestion

  useEffect(() => {
    registerAction('setFocus', async function () {
      textInputRef.current.focus();
    });
    registerAction('setBlur', async function () {
      textInputRef.current.blur();
    });
  }, [textInputRef.current]);
```

2022-09-23 09:41 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/TextInput.jsx
> +  });
```suggestion

  useEffect(() => {
    registerAction('setText', async function (text) {
      setValue(text);
      setExposedVariable('value', text).then(fireEvent('onChange'));
    });
    registerAction('clear', async function () {
      setValue('');
      setExposedVariable('value', '').then(fireEvent('onChange'));
    });
    registerAction('disable', async function (value) {
      setDisable(value);
    });
    registerAction('visibility', async function (value) {
      setVisibility(value);
    });
  }, []);
```

2022-09-26 09:27 UTC, kavinvenkatachalam submitted a review, later dismissed

2022-09-28 12:20 UTC, kavinvenkatachalam approved these changes

2022-09-28 12:21 UTC, merged