Enhancement : [ Text widget ] refactor
ToolJet/ToolJet pull request #4038
Opened 2022-09-14 12:49 UTC by manishkushare

Resolves #4037

2022-09-16 07:22 UTC, shubh22 commented
Task linked: [CU-2u58p4g Text widget enhancement](https://app.clickup.com/t/2u58p4g)

2022-09-23 14:07 UTC, kavinvenkatachalam requested changes

2022-09-23 14:07 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Text.jsx
> +  // const [loadingState, setLoadingState] = useState(false);
```suggestion
```

2022-09-23 14:07 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Text.jsx
> +  useEffect(() => setVisibility(styles.visibility), [styles.visibility]);
```suggestion
  useEffect(() => visibility !== styles.visibility && setVisibility(styles.visibility), [styles.visibility]);
```

2022-09-26 09:35 UTC, kavinvenkatachalam approved these changes

2022-09-26 09:35 UTC, merged