[improvement] Modal widget
ToolJet/ToolJet pull request #4045
Opened 2022-09-15 12:01 UTC by arpitnath

2022-09-19 10:37 UTC, shubh22 commented
Task linked: [CU-2tzfzh8 Improvements: Modal widget](https://app.clickup.com/t/2tzfzh8)

2022-09-20 09:51 UTC, kavinvenkatachalam requested changes
@arpitnath `onClose` event is called whenever I reload the page. It's because we're calling the `fireEvent` in the useEffect

2022-09-20 09:51 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Modal.jsx
> +  }, [showModal]);
`fireEvent` in the useEffect will trigger when the component is mounted

2022-09-26 08:26 UTC, kavinvenkatachalam approved these changes
LGTM

2022-09-26 09:44 UTC, sherfin94 commented
@arpitnath Please test the updated migration once

2022-09-26 10:16 UTC, kavinvenkatachalam approved these changes

2022-09-26 10:16 UTC, merged