Add happy path spec for number input widget
ToolJet/ToolJet pull request #4074
Opened 2022-09-20 11:48 UTC by ajith-k-v

Fixes: #4067

2022-09-21 04:40 UTC, shubh22 commented
Task linked: [CU-2uw67c7 Add HappyPath Spec for Number Input](https://app.clickup.com/t/2uw67c7)

2022-09-24 04:12 UTC, ajith-k-v commented
@emidhun Please review

<img width="449" alt="Screenshot 2022-09-24 at 9 41 12 AM" src="https://user-images.githubusercontent.com/20367957/192079423-ab059375-d9f0-4359-82a9-83add49b90a4.png">

2022-10-04 01:53 UTC, emidhun requested changes
Can we keep the failing code on the codebase, since the failures are due to application issues.

2022-10-04 01:53 UTC, emidhun commented on cypress-tests/cypress/e2e/editor/widget/buttonHappyPath.cy.js
> -    addAndVerifyTooltip(
I think we can keep the code, Sice it fails because of a bug.

2022-10-04 06:53 UTC, emidhun approved these changes
LGTM

2022-10-04 07:38 UTC, merged