Feature :: Table bugfixes and option for pagination number added
ToolJet/ToolJet pull request #4083
Opened 2022-09-21 14:01 UTC by stepinfwd

close #4082 4082

2022-09-22 09:11 UTC, sherfin94 commented
@stepinfwd There is still a very small gulf between the right most border of the table and the right most border of the right most column: 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/20333972/191707339-41b5d6de-0643-4b67-9230-7bbe14d0d7d8.png">

This might also be causing the horizontal scrollbar to appear all the time. That is, there seems to be no way to get rid of the horizontal scroll bar at all.

2022-09-22 09:17 UTC, sherfin94 commented
`Number of results per page` is being shown even if it is not client side pagination. Please show it only for client side pagination, and try to see if we can show it below the client side pagination option. Also, lets call it `Number of rows per page`
<img width="254" alt="image" src="https://user-images.githubusercontent.com/20333972/191708589-7254295b-829f-49d1-b624-f3c85b392616.png">

2022-09-22 09:20 UTC, sherfin94 commented on frontend/src/_styles/theme.scss
> +  display: flex !important;
This is not urgent, but see if we could avoid `!important` if possible.

2022-09-22 09:21 UTC, sherfin94 requested changes
I've commented few issues.

Implementation generally looks good!

2022-09-27 06:45 UTC, sherfin94 requested changes
Hey @stepinfwd ,

Few items:

1. Resizing still seems to trigger sort in certain scenarios: 

https://user-images.githubusercontent.com/20333972/192452090-7c6ad8c6-ebea-4172-b4ed-b596786af116.mov


https://user-images.githubusercontent.com/20333972/192452131-f7092158-dc89-4056-b180-f716d772ff38.mov

2. If it is a server side pagination, lets not show the number of records per page property: 
<img width="219" alt="image" src="https://user-images.githubusercontent.com/20333972/192452787-31c038d5-853c-43df-8612-096012bec8e6.png">

3. Resolve conflicts

2022-09-27 09:19 UTC, shubh22 commented
Task linked: [CU-2vjw3h2 Table Enhancements](https://app.clickup.com/t/2vjw3h2)

2022-09-27 11:10 UTC, shubh22 commented
Task linked: [CU-2q9mdw7 Resizing column, automatically sorts the column in table](https://app.clickup.com/t/2q9mdw7)

2022-09-27 18:31 UTC, shubh22 commented
Task linked: [CU-2vjy6xc Downloaded data must be according  filter - Table widgets](https://app.clickup.com/t/2vjy6xc)

2022-09-27 18:33 UTC, shubh22 commented
Task linked: [CU-2vjy6y0 Change the number of results per page - client side pagination (configurable by user)-Table widget](https://app.clickup.com/t/2vjy6y0)

2022-10-13 09:46 UTC, sherfin94 approved these changes

2022-10-13 09:46 UTC, merged