[ Enhancement] : adding local storage support in query manager panel
ToolJet/ToolJet pull request #4087
Opened 2022-09-21 22:27 UTC by manishkushare

Resolves #4086

2022-09-21 22:29 UTC, shubh22 commented
Task linked: [CU-2v1vhaq Adding local storage support to query panel](https://app.clickup.com/t/2v1vhaq)

2022-09-28 02:51 UTC, kavinvenkatachalam requested changes
@manishkushare Added a small suggestion to support backward compatibility for the users who configured the button on the query panel previously.

2022-09-28 02:51 UTC, kavinvenkatachalam commented on frontend/src/Editor/QueryManager/QueryManager.jsx
> +    this.buttonConfig = this.queryManagerPreferences?.buttonConfig ?? {};
```suggestion

    if (localStorage.getItem('queryManagerButtonConfig') === null) {
      this.buttonConfig = this.queryManagerPreferences?.buttonConfig ?? {};
    } else {
      this.buttonConfig = JSON.parse(localStorage.getItem('queryManagerButtonConfig'));
      localStorage.setItem(
        'queryManagerPreferences',
        JSON.stringify({ ...this.queryManagerPreferences, buttonConfig: this.buttonConfig })
      );
      localStorage.removeItem('queryManagerButtonConfig');
    }
```

2022-09-29 04:50 UTC, kavinvenkatachalam approved these changes

2022-09-29 07:22 UTC, merged