[ hotfix ] : filter pop-up and dropdown inside it are  not scrollable
ToolJet/ToolJet pull request #4098
Opened 2022-09-22 19:09 UTC by manishkushare

Resolves #4097

2022-09-22 19:12 UTC, shubh22 commented
Task linked: [CU-2v7en4a Hotfix : filter section is not scrollable](https://app.clickup.com/t/2v7en4a)

2022-09-27 08:39 UTC, sherfin94 reviewed
Hey @manishkushare , PR works well!, please resolve the conflicts and then we can merge it.

2022-10-06 02:44 UTC, kavinvenkatachalam approved these changes
LGTM

2022-10-06 02:55 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Table/Filter.jsx
>  import SelectSearch, { fuzzySearch } from 'react-select-search';
@manishkushare Can you remove `SelectSearch` if it is not used anywhere?

2022-10-06 02:56 UTC, kavinvenkatachalam requested changes
@manishkushare Suggested a minor change

2022-10-06 11:52 UTC, merged