Bugfix: update both comments collections when socket message is received
ToolJet/ToolJet pull request #4105
Opened 2022-09-23 07:24 UTC by mslourens

I split both notification collections into resolved and unresolved, because setting the collection based on the state of the tab and using the same collection for both tabs feels weird. 
Also whenever a notifications message is received, it is not possible to determine whether an unresolved comment is marked as resolved or visa versa. Therefore I suggest we update both collections whenever a message is received.

2022-09-23 10:20 UTC, withshubh commented
Thanks for your contribution @mslourens 🎉 
A team member will review the PR soon.

2022-09-26 05:46 UTC, gondar00 commented on frontend/src/Editor/CommentNotifications/index.jsx
> -    const isResolved = k === 'resolved';
@mslourens I believe the issue exists when the user switches to the "resolved" tab, feel like the issue can be solved by adding another check for `isResolved` based on the tab `key` value and prevent making an extra api call i.e

```js
const isResolved = k === 'resolved' || key === 'resolved';
```

2022-12-12 09:40 UTC, withshubh commented
Hey @mslourens 
Please update the PR with the changes suggested above. 🙌

2022-12-12 20:00 UTC, mslourens commented
That's the whole issue here, for some reason the key is always 'acrive' when a notification is received. That's why I added the 
'both' argument to at least keep them both up to date. I am not very experienced with React, so I don't know why the key property is always active (even when the received tab is selected and the setKey hook is called with 'received'). This PR at least fixes the issue for now.

2023-04-06 07:08 UTC, kavinvenkatachalam requested changes
@mslourens Thanks for the PR.

Can you change the base branch to `ToolJet:develop` and take a pull from latest develop?

2023-11-01 11:54 UTC, tejakummarikuntla commented
closing the PR due to inactivity

2023-11-01 11:54 UTC, closed without merging