Add happy path spec for password input widget
ToolJet/ToolJet pull request #4112
Opened 2022-09-26 04:36 UTC by ajith-k-v

Fixes: #4076 
![Screenshot 2022-09-26 at 10 02 14 AM](https://user-images.githubusercontent.com/20367957/192194641-0270122b-741f-42cb-a010-58be6c59f275.png)

2022-09-26 14:09 UTC, shubh22 commented
Task linked: [CU-2uw67d1 Add HappyPath Spec for Password Input](https://app.clickup.com/t/2uw67d1)

2022-10-04 01:48 UTC, emidhun requested changes

2022-10-04 01:48 UTC, emidhun commented on cypress-tests/cypress/e2e/editor/widget/passwordInputHappyPath.cy.js
> +    verifyAndModifyParameter('Placeholder', data.customText);
can we add validation for the default placeholder before modifying that?

2022-10-11 08:12 UTC, emidhun requested changes
I think we can remove the unused methods from the import section,
and the spec is failing.
<img width="488" alt="Screenshot 2022-10-11 at 1 41 08 PM" src="https://user-images.githubusercontent.com/20367955/195035239-46c96a2f-6b74-4b64-9160-ea3e8fb15d96.png">
Please fix this and let me know.

2022-10-12 05:21 UTC, ajith-k-v commented
@emidhun Added review changes. Please review

<img width="443" alt="Screenshot 2022-10-12 at 10 13 55 AM" src="https://user-images.githubusercontent.com/20367957/195252093-f77e5cf7-a05e-4264-81ec-47f1cce86570.png">

2022-10-14 02:41 UTC, emidhun approved these changes
Looking Good To Me.
@ajith-k-v  Thank you for the changes.

2022-10-14 11:46 UTC, merged