[ Enhancement ] :: selectedRow CSA for table widget
ToolJet/ToolJet pull request #4128
Opened 2022-09-27 09:11 UTC by stepinfwd

part of #4093

2022-09-27 09:15 UTC, shubh22 commented
Task linked: [CU-2vjw22z Table Enhancements :: add selectedrow CSA](https://app.clickup.com/t/2vjw22z)

2022-09-30 10:32 UTC, kavinvenkatachalam requested changes
@stepinfwd Made a suggestion below. Instead of `map` which loops all the element of the array we can use `find` - it stops when it finds the first element.

2022-09-30 10:32 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Table/Table.jsx
> +      const selectedRowDetails = { selectedRow: item[0], selectedRowId: rowId };
```suggestion
const row = page.find((item, index) => item.original.id == id);
      const selectedRowDetails = { selectedRow: item[0], selectedRowId: row?.id ?? '' };
```

2022-10-06 04:13 UTC, kavinvenkatachalam requested changes
@stepinfwd Changes look good. One suggestion,

If I pass the `id` which is not in the table, it throws an error. Can we add an `undefined` check to skip that?

2022-10-06 04:13 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Table/Table.jsx
> +      const original = row.original;
Can you remove the `original` variable if it is not needed? And we can use `row.id` directly in the object instead of creating a new variable

2022-10-07 05:49 UTC, kavinvenkatachalam submitted a review, later dismissed
LGTM

2022-11-03 06:22 UTC, stepinfwd commented
closing this one  , opened new implementation here https://github.com/ToolJet/ToolJet/pull/4591

2022-11-03 06:22 UTC, closed without merging