[DRAFT] Feature: Versioned exports
ToolJet/ToolJet pull request #4140
Opened 2022-09-28 16:37 UTC by akshaysasidrn

2022-09-29 08:50 UTC, shubh22 commented
Task linked: [CU-2vrm5d4 Ability to export versioned apps](https://app.clickup.com/t/2vrm5d4)

2022-11-30 09:42 UTC, gsmithun4 requested changes

2022-11-30 10:03 UTC, akshaysasidrn commented on server/src/controllers/app_import_export.controller.ts
> +    if (!ability.can('viewApp', appToExport)) {
will change it

2022-11-30 10:03 UTC, akshaysasidrn commented on server/src/services/app_import_export.service.ts
> +    const queryForappToExport = this.entityManager
I don't think it would make much sense to right? This is simply select operation.

2022-12-01 06:37 UTC, gsmithun4 submitted a review, later dismissed

2022-12-02 08:42 UTC, gsmithun4 approved these changes

2022-12-02 08:43 UTC, merged