Feature :: Table sort disable/enable
ToolJet/ToolJet pull request #4142
Opened 2022-09-29 06:36 UTC by stepinfwd

part of #4093
*disable sorting - option to enable/disable

2022-09-29 12:57 UTC, shubh22 commented
Task linked: [CU-2vjy73m Option to disable sorting - Table widget](https://app.clickup.com/t/2vjy73m)

2022-09-30 09:31 UTC, kavinvenkatachalam requested changes
@stepinfwd Seems like `disabledBtn` is not needed in this PR. Can you please check and update?

2022-09-30 09:31 UTC, kavinvenkatachalam commented on frontend/src/Editor/Inspector/Components/Table.jsx
> +      disabledBtn: false,
```suggestion
```

2022-10-07 05:45 UTC, kavinvenkatachalam submitted a review, later dismissed

2022-10-13 09:02 UTC, sherfin94 approved these changes

2022-10-13 09:02 UTC, merged