Adds background color property to password input editor
ToolJet/ToolJet pull request #4190
Opened 2022-10-01 07:04 UTC by Srisuma13

Fixes https://github.com/ToolJet/ToolJet/issues/4181

2022-10-01 07:06 UTC, Srisuma13 commented
Hey @arpitnath, Opened this PR for https://github.com/ToolJet/ToolJet/issues/4181. Could you please check?

2022-10-01 07:09 UTC, arpitnath commented
@Srisuma13 Thanks for contributing to ToolJet 🚀
We shall review your PR soon, till then you can check out issues with [hactoberfest](https://github.com/ToolJet/ToolJet/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) tags.

2022-10-04 10:04 UTC, arpitnath requested changes
Can you please add the default value in the **widgetConfig.jsx**
And also fix the lint errors.

2022-10-04 15:21 UTC, Srisuma13 commented
@arpitnath Fixed the lint issues, could you please review it now?

2022-10-04 22:12 UTC, arpitnath requested changes
Please add a default value `#fff` for the style definitions in the **widgetConfig.js**

2022-10-05 06:32 UTC, Srisuma13 commented
made the requested changes @arpitnath, thanks for reviewing.

2022-10-09 10:19 UTC, arpitnath approved these changes

2022-10-09 10:19 UTC, arpitnath commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        value: '#fff',
Not here, in the definitions schema.
Ref: https://github.com/ToolJet/ToolJet/pull/4356/files#diff-05ef203383ea521c66bce82f07f8b921e28441a4818ab30af45ed08d4e4d5b6bR510

2022-10-09 10:23 UTC, arpitnath requested changes
Please ref: https://github.com/ToolJet/ToolJet/pull/4356/files#diff-05ef203383ea521c66bce82f07f8b921e28441a4818ab30af45ed08d4e4d5b6bR510

2022-10-11 07:20 UTC, withshubh commented
Hey @Srisuma13 👋 
Any updates on the changes?

2022-10-11 10:01 UTC, Srisuma13 commented
> Hey @Srisuma13 👋 Any updates on the changes?

Hey @withshubh @arpitnath, will push the suggested changes shortly. Thanks

2022-10-11 10:36 UTC, Srisuma13 commented on frontend/src/Editor/Components/Container.jsx
> +  const { visibility, disabledState, borderRadius, borderColor } = styles;
the pipeline was failing because of a lint issue here after pulling the master branch. So had to make this change.

2022-10-11 10:42 UTC, Srisuma13 commented
@arpitnath @withshubh Done. Can you please check now?

2022-10-25 21:04 UTC, arpitnath approved these changes

2022-10-26 04:35 UTC, merged