Feature: Number input text color
ToolJet/ToolJet pull request #4193
Opened 2022-10-01 08:55 UTC by danielevilela

![image](https://user-images.githubusercontent.com/5096692/193401591-5415d774-9fd3-4dc3-a94a-28f3d24d555b.png)

2022-10-01 08:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4193) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=4193) it.</sub>

2022-10-04 09:57 UTC, arpitnath requested changes
Please add default value for the widget in `widgetConfig.jsx`

Under definitions, styles.

2022-10-04 22:59 UTC, arpitnath requested changes
Can you resolve the merge conflicts too?

2022-10-04 22:59 UTC, arpitnath commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        textColor: { value: '' },
Can you use the current input color as the default value?
```suggestion
        textColor: { value: '#232e3c' },
```

2022-10-04 23:37 UTC, arpitnath approved these changes

2022-10-04 23:38 UTC, arpitnath approved these changes

2022-10-25 13:19 UTC, gsmithun4 commented
deployed https://tj-4193.herokuapp.com/

2022-10-25 20:56 UTC, arpitnath requested changes

2022-10-25 20:56 UTC, arpitnath commented on frontend/src/Editor/Components/NumberInput.jsx
> +  const textColor = darkMode && styles.textColor === '#000' ? '#fff' : styles.textColor;
As the default color is **#232e3c**, that should be handled, or else on switching from light to dark the input is not legible
```suggestion
  const textColor = darkMode && ['#232e3c', '#000000ff'].includes(styles.textColor) ? '#fff' : styles.textColor;
```

2022-10-28 09:15 UTC, arpitnath approved these changes

2022-11-03 02:15 UTC, merged

2022-11-04 05:47 UTC, withshubh commented
Hey @danielevilela 
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7