Added Background Color to Text Input
ToolJet/ToolJet pull request #4194
Opened 2022-10-01 09:07 UTC by rahulsunil2

Related to #4171

2022-10-01 09:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4194) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4194) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=4194) it.</sub>

2022-10-04 21:27 UTC, arpitnath requested changes
Can you please add the default value (in the definitions) in the **widgetConfig.js**?

2022-10-04 22:18 UTC, arpitnath commented
@rahulsunil2 You did not make any changes?

2022-10-04 22:45 UTC, rahulsunil2 commented
> @rahulsunil2 You did not make any changes?

I made that commit to merge the latest pull from the origin repo to fix the docker issue.

2022-10-04 22:54 UTC, arpitnath commented
Okay, I have requested a few changes related to the issue. Can you please look into it 😅

2022-10-05 13:55 UTC, rahulsunil2 commented
> Can you please add the default value (in the definitions) in the **widgetConfig.js**?

I have made this change and pushed the commit.

2022-10-15 08:55 UTC, rahulsunil2 commented
@arpitnath Any updates?

2022-10-25 21:31 UTC, arpitnath requested changes

2022-10-25 21:31 UTC, arpitnath commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +      backgroundColor: {
We also need a default value for the same.

2022-10-25 21:31 UTC, arpitnath commented on frontend/src/Editor/Components/TextInput.jsx
> +        style={{ height, borderRadius: `${styles.borderRadius}px`, color: textColor, backgroundColor: `${styles.backgroundColor}`}}
Also need to handle the background color for the default value on toggling the theme

2022-11-08 10:51 UTC, kavinvenkatachalam approved these changes
LGTM

2022-11-14 09:01 UTC, withshubh commented
Hey @rahulsunil2  
Thanks for contributing to ToolJet. :raised_hands: 
While this PR is under review, you can submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

2022-11-17 09:38 UTC, merged