Border color added
ToolJet/ToolJet pull request #4202
Opened 2022-10-01 13:05 UTC by prateek565

2022-10-01 13:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4202) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4202) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=4202) it.</sub>

2022-10-01 16:37 UTC, prateek565 commented
closes #4164

2022-10-04 21:51 UTC, arpitnath commented on frontend/src/Editor/Components/Container.jsx
> +    borderColor,
```suggestion
    border: "1px solid",
    borderColor,
```

2022-10-04 21:53 UTC, arpitnath commented on frontend/src/Editor/Components/Container.jsx
> +    borderColor,
OR
```suggestion
border: `1px solid ${borderColor}`,
```

2022-10-04 21:55 UTC, arpitnath requested changes
<img width="292" alt="Screenshot 2022-10-05 at 3 24 46 AM" src="https://user-images.githubusercontent.com/67645175/193937486-e64d9dac-d6e4-4106-814e-992e8f37c98d.png">
Also, can we have the border color property next to **border radius**?

2022-10-04 21:55 UTC, arpitnath commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        borderColor: { value: '' },
```suggestion
        borderColor: { value: '#fff' },
```

2022-10-05 01:20 UTC, prateek565 commented
Okayy i will get it done by today . Thanks for feedback 😊.

2022-10-05 03:56 UTC, prateek565 commented
hi @arpitnath  i have done all the changes as recomended.

2022-10-09 10:11 UTC, arpitnath approved these changes

2022-10-11 08:17 UTC, merged

2022-11-14 09:12 UTC, withshubh commented
Hey @prateek565  
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7