closes #4173
ToolJet/ToolJet pull request #4218
Opened 2022-10-01 16:31 UTC by MohammedBajuaifer

2022-10-01 16:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=4218) it.</sub>

2022-10-02 15:45 UTC, Navaneeth-pk commented
@MohammedBajuaifer please add proper title for PRs.

2022-10-02 16:32 UTC, MohammedBajuaifer commented
@Navaneeth-pk,  Updated.

2022-10-04 21:25 UTC, arpitnath commented
@MohammedBajuaifer  Please can you fix the lint errors?

2022-10-05 08:42 UTC, MohammedBajuaifer commented
Hey @arpitnath, updated the PR

2022-10-13 07:53 UTC, arpitnath submitted a review, later dismissed

2022-10-18 07:26 UTC, Navaneeth-pk commented
@MohammedBajuaifer  please resolve merge conflicts.

2022-10-26 04:39 UTC, kavinvenkatachalam requested changes
@MohammedBajuaifer You replaced the `component` prop which is breaking the component. Made a suggestion, can you please update the code?

2022-10-26 04:39 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/PasswordInput.jsx
> +export const PasswordInput = ({ height, validate, properties, styles, setExposedVariable, darkMode, fireEvent }) => {
```suggestion
export const PasswordInput = ({ height, validate, properties, styles, setExposedVariable, darkMode, component, fireEvent }) => {
```

2022-10-31 04:09 UTC, kavinvenkatachalam submitted a review, later dismissed
LGTM

2022-11-02 07:47 UTC, arpitnath submitted a review, later dismissed

2022-11-03 02:02 UTC, kavinvenkatachalam commented
@MohammedBajuaifer Can you fix lint errors?

2022-11-03 11:31 UTC, sherfin94 approved these changes

2022-11-03 11:32 UTC, merged

2022-11-04 05:25 UTC, withshubh commented
Hey @MohammedBajuaifer 
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7