Feature :: Table - option to hide columns
ToolJet/ToolJet pull request #4284
Opened 2022-10-04 07:39 UTC by stepinfwd

closes #4283

2022-10-05 18:58 UTC, shubh22 commented
Task linked: [CU-2vjy6w2 Show/hide Columns (for user) - Table widget](https://app.clickup.com/t/2vjy6w2)

2022-10-06 05:05 UTC, kavinvenkatachalam requested changes
@stepinfwd Made a few suggestions on the code. 

Regarding the UX, I'm not able to close the opened layer by clicking outside. I need to click the eye icon again to close that. It would be good if we close the popup by clicking outside 

cc: @sherfin94 @shubh22

2022-10-10 03:55 UTC, kavinvenkatachalam approved these changes

2022-10-13 08:40 UTC, sherfin94 approved these changes

2022-10-13 08:45 UTC, merged