Feature/list view border color
ToolJet/ToolJet pull request #4300
Opened 2022-10-04 12:24 UTC by FroostyCodes

2022-10-04 12:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=4300) it.</sub>

2022-10-04 22:27 UTC, arpitnath requested changes
Please add a default value in the widget definitions in the **widgetConfig.js**

2022-10-09 09:24 UTC, FroostyCodes commented
@arpitnath I have made the changes you requested, do let me know if any further changes are to be done.

2022-10-09 09:49 UTC, arpitnath approved these changes

2022-10-10 09:27 UTC, kavinvenkatachalam requested changes
@FroostyCodes Can you add an undefined check with transparent color? This way it won't affect the existing apps.

2022-10-10 09:27 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Listview.jsx
> +  const borderColor = styles.borderColor;
```suggestion
  const borderColor = styles.borderColor ?? 'transparent';
```

2022-10-10 09:50 UTC, FroostyCodes commented
@kavinvenkatachalam done

2022-10-10 12:09 UTC, kavinvenkatachalam approved these changes

2022-10-11 03:40 UTC, merged