Updated TextInput.jsx for text color field.
ToolJet/ToolJet pull request #4302
Opened 2022-10-04 13:12 UTC by dmdbilal

Issue #4183

With the reference of the issue #4183. I've resolved this issue by adding the missing codes in the TextInput.jsx file.

2022-10-04 22:15 UTC, arpitnath requested changes
It will have compile errors.
Can you please, check the UI after making changes?

2022-10-07 14:32 UTC, arpitnath commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +      textColor: { value: '#232e3c' },
why are we exposing the values?

2022-10-07 14:35 UTC, arpitnath requested changes

2022-10-07 16:27 UTC, dmdbilal commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +      textColor: { value: '#232e3c' },
OOPS ! Sorry misplaced.

2022-10-07 16:27 UTC, dmdbilal commented
Made changes @arpitnath.

2022-10-09 09:37 UTC, arpitnath requested changes
Both the files have lint issues, please revert those changes.
And before making changes, please use our lint rules and commit the changes.
You can configure the ESLint for ToolJet from [here](https://docs.tooljet.com/docs/contributing-guide/troubleshooting/eslint)

2022-10-09 09:37 UTC, arpitnath commented on frontend/src/Editor/Components/TextInput.jsx
> +  const computedStyles = {
variables : `computedStyles`, `disabledState` are never being used.

2022-10-09 09:37 UTC, arpitnath commented on frontend/src/Editor/Components/TextInput.jsx
> +    backgroundColor,
crashing the widget with a `ReferenceError`.
`backgroundColor` is not defined.

2022-10-09 09:37 UTC, arpitnath commented on frontend/src/Editor/Components/TextInput.jsx
> +        className={`form-control ${!isValid ? 'is-invalid' : ''} validation-without-icon ${darkMode && 'dark-theme-placeholder'
What is/is the change here?

2022-10-09 09:37 UTC, arpitnath commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        validation: {
Please revert back to formatting changes.
And try to follow the repository's Lint rules.

2022-10-10 12:25 UTC, dmdbilal commented
Can you assign this issue to someone. Because my laptop was crashed yesterday so i can't contribute for next 1 month.

2022-10-25 20:58 UTC, arpitnath commented
https://github.com/ToolJet/ToolJet/pull/4302#issuecomment-1273236766

Okay, closing the PR

2022-10-25 20:58 UTC, closed without merging