Fixed the default text color
ToolJet/ToolJet pull request #4319
Opened 2022-10-05 11:30 UTC by abhishekpatil4

#4243 Fixed the default text color, please verify my pull reauest.

2022-10-05 11:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4319) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=4319) it.</sub>

2022-10-06 03:15 UTC, Candida18 commented
Can you pls assign this issue to me
I'll make the changes in a few minutes

2022-10-09 09:24 UTC, arpitnath requested changes

2022-10-09 09:24 UTC, arpitnath commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        backgroundColor: { value: '#fff' },
The issue was for setting the **default text color** not the background color.
```suggestion
        textColor: { value: '#000' },
```

2022-10-09 17:07 UTC, closed without merging

2022-10-09 17:42 UTC, abhishekpatil4 commented
@arpitnath apologies for the misunderstanding, did the suggested changes. please verify my pull request