Added border color property to button styles
ToolJet/ToolJet pull request #4356
Opened 2022-10-08 15:38 UTC by vedant-z

Fixes #4297

2022-10-08 15:38 UTC, vedant-z commented
@withshubh Have I done the required changes correctly?

2022-10-09 08:26 UTC, withshubh commented
> @withshubh Have I done the required changes correctly?

Let's wait for the PR to be reviewed

2022-10-09 09:09 UTC, arpitnath requested changes

2022-10-09 09:09 UTC, arpitnath commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        borderColor: { value: '' },
Can we add a default value for the border color?
```suggestion
        borderColor: { value: '#375FCF' },
```

2022-10-09 09:09 UTC, arpitnath commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        borderColor: { value: '' },
other than that LGTM!
@vedant-z 🚀

2022-10-09 09:35 UTC, vedant-z commented
@arpitnath Done ✅

2022-10-09 09:56 UTC, arpitnath approved these changes

2022-10-10 09:43 UTC, kavinvenkatachalam approved these changes

2022-10-11 03:38 UTC, merged

2022-11-03 15:57 UTC, withshubh commented
Hey @vedant-z 
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

2022-11-03 15:58 UTC, vedant-z commented
Thanks so much @withshubh 

I love contributing to ToolJet and will continue contributing 🔥🔥