[enahancement] Added app loader page
ToolJet/ToolJet pull request #4389
Opened 2022-10-12 10:50 UTC by shah21

Resolves #4388

2022-10-14 08:25 UTC, shubh22 commented
Task linked: [CU-2x0tkdb Manage Forbidden/Unauthorised app errors](https://app.clickup.com/t/2x0tkdb)

2022-10-17 11:00 UTC, gsmithun4 requested changes

2022-10-17 11:00 UTC, gsmithun4 commented on frontend/src/AppLoader/AppLoader.jsx
> +      const statusCode = errorDetails.data?.statusCode;
Shall we change the get apps API and get the application's organization id in error case?
and we can call the switch organization API

2022-10-18 22:13 UTC, gsmithun4 commented
deployed https://tj-app-loader.herokuapp.com/

2022-10-24 11:08 UTC, gsmithun4 requested changes

2022-10-24 11:08 UTC, gsmithun4 commented on frontend/src/Editor/Viewer.jsx
> +        const errorObj = JSON.parse(errorDetails.data?.message);
we should consider the scenario when `errorDetails.data?.message` empty or not valid json. try catch can be added and on error redirected to home page, same for editor loader

2022-11-03 06:03 UTC, gsmithun4 commented on frontend/src/_helpers/utils.js
> +}
```suggestion
export function safelyParseJSON(json) {
  try {
    return JSON.parse(json);
  } catch (e) {
    console.log('JSON parse error');
  }
  return;
}
```

2022-11-08 07:19 UTC, gsmithun4 approved these changes

2022-11-14 06:37 UTC, merged