Toast position fixed
ToolJet/ToolJet pull request #4401
Opened 2022-10-13 06:30 UTC by gagandeepp

2022-10-13 06:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4401) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4401) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=4401) it.</sub>

2022-10-13 06:32 UTC, gagandeepp commented
@withshubh Please review this.

2022-10-13 14:15 UTC, gagandeepp commented
@arpitnath  Please review the PR

2022-10-17 04:40 UTC, gsmithun4 requested changes

2022-10-17 04:40 UTC, gsmithun4 commented on frontend/src/ManageOrgUsers/ManageOrgUsers.jsx
> +      position: 'top-right',
Position should be `top-center`

2022-10-24 17:52 UTC, gsmithun4 approved these changes

2022-10-24 18:14 UTC, merged

2022-10-24 22:57 UTC, Oluwatobiiiiii commented
The link is not working

2022-11-07 21:12 UTC, withshubh commented
Hey @gagandeepp  
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7

2022-11-14 09:15 UTC, withshubh commented
Hey @gagandeepp - We haven't received your submission for the hacktoberfest swag. Please submit the form as soon as possible.

2022-11-16 06:47 UTC, withshubh commented
Hey @gagandeepp - Please submit the form before the end of this week to claim your Hacktoberfest swag: [airtable.com/shr1qR6xhqsWO7LD7](https://airtable.com/shr1qR6xhqsWO7LD7)