[ Hotfix ] :: Hard to resize table columns
ToolJet/ToolJet pull request #4438
Opened 2022-10-14 13:53 UTC by stepinfwd

* scrollbar should not be visible
 * resizing should be smooth and easy

2022-11-01 08:41 UTC, sherfin94 requested changes
@stepinfwd few issues

1. In editor mode, the resize handle can only be grabbed if we click slightly to the left of it
2. In viewer mode, it does not seem to be possible to grab and resize columns at all

2022-11-14 10:11 UTC, sherfin94 approved these changes

2022-11-15 07:54 UTC, shubh22 commented
Task linked: [CU-30k7rn6 Hard to resize table columns](https://app.clickup.com/t/30k7rn6)

2022-11-17 12:33 UTC, sherfin94 approved these changes

2022-11-17 12:33 UTC, merged