Changed "show bulk update actions" label in Table (#4496)
ToolJet/ToolJet pull request #4497
Opened 2022-10-17 23:31 UTC by 3t8

Changed the label from `Show bulk update actions` to `Show update buttons` in Table component
#4496

2022-10-24 20:56 UTC, withshubh commented on docs/docs/widgets/table.md
>  It's enabled by default. Toggle `off` hide bulk update actions.
Please update this too

2022-10-24 20:57 UTC, withshubh requested changes

2022-10-24 20:57 UTC, withshubh commented on docs/docs/widgets/table.md
>  It's enabled by default. Toggle `off` hide bulk update actions.
Please update this too

2022-10-24 21:24 UTC, 3t8 commented on docs/docs/widgets/table.md
>  It's enabled by default. Toggle `off` hide bulk update actions.
Done

2022-10-25 05:34 UTC, withshubh approved these changes
Docs ✅

2022-10-25 23:49 UTC, 3t8 commented
Resolved conflicts and updated translation @withshubh

2022-10-28 10:07 UTC, arpitnath approved these changes
LGTM!

2022-11-17 12:31 UTC, sherfin94 approved these changes

2022-11-17 12:32 UTC, sherfin94 requested changes
Hey @3t8 , please resolve the conflicts.

2022-12-05 11:25 UTC, merged