Improve toast message shortcut on component deletion
ToolJet/ToolJet pull request #4513
Opened 2022-10-18 13:26 UTC by 3t8

#4512

2022-10-24 10:35 UTC, gsmithun4 commented
deployed https://tj-4513.herokuapp.com/

2022-10-25 06:34 UTC, kavinvenkatachalam requested changes
@3t8 Thanks for the PR.

I agree that `navigator.platform` is supported by all the browsers but as it is depreciated and we can use `navigator?.userAgentData?.platform` with `navigator.platform` as a fallback.

2022-10-25 06:34 UTC, kavinvenkatachalam commented on frontend/src/Editor/Editor.jsx
> +      if (navigator.platform.indexOf('Mac') > -1) {
```suggestion
      const platform = navigator?.userAgentData?.platform || navigator?.platform || 'unknown';
      if (platform.toLowerCase().indexOf('mac') > -1) {
```

2022-10-27 11:13 UTC, 3t8 commented on frontend/src/Editor/Editor.jsx
> +      if (navigator.platform.indexOf('Mac') > -1) {
Committed suggestion

2022-10-27 11:14 UTC, 3t8 commented
@gsmithun4 Do I need any specific email to test the deployed version? I can't figure out how to sign up and get a confimation email

2022-10-31 08:37 UTC, kavinvenkatachalam approved these changes
LGTM

2022-10-31 08:39 UTC, kavinvenkatachalam requested changes
@3t8 Thanks for the changes. Similarly, can you change line no `615`?

2022-10-31 11:12 UTC, 3t8 commented
@kavinvenkatachalam Done!

2022-10-31 11:38 UTC, kavinvenkatachalam approved these changes
LGTM

2022-10-31 11:58 UTC, merged

2022-11-07 20:49 UTC, withshubh commented
Hey @3t8  
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7