Update theme.css
ToolJet/ToolJet pull request #4538
Opened 2022-10-20 11:22 UTC by AyushK-101

Closes #2860

2022-10-20 11:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4538) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=4538) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=4538) it.</sub>

2022-10-24 15:28 UTC, gsmithun4 commented
@AyushK-101 Please sign CLA

2022-10-24 17:16 UTC, AyushK-101 commented
@gsmithun4 done

2022-10-25 06:12 UTC, kavinvenkatachalam requested changes
@AyushK-101 Thanks for the PR.

There is some blank space at the bottom of the screen. Made a suggestion, please check and update the code.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/50441969/197696054-e7382293-e411-4f4e-8331-97d04f83fcfd.png">

2022-10-25 06:12 UTC, kavinvenkatachalam commented on frontend/src/_styles/theme.scss
> +  height: calc(100vh - 2.5rem - 48px);
```suggestion
  height: calc(100vh - 1.25rem - 48px);
```

2022-10-25 10:13 UTC, kavinvenkatachalam approved these changes
LGTM

2022-10-25 10:56 UTC, gsmithun4 commented
deployed https://tj-4538.herokuapp.com/

2022-10-25 11:02 UTC, merged

2022-11-07 21:10 UTC, withshubh commented
Hey @AyushK-101  
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7