Show version name while deleting
ToolJet/ToolJet pull request #4589
Opened 2022-10-24 13:11 UTC by FroostyCodes

Fixes #4575

2022-10-24 14:05 UTC, gsmithun4 commented
deployed https://tj-4589.herokuapp.com/

2022-10-24 14:59 UTC, FroostyCodes commented
Screenshot for reference:
<img width="385" alt="Screen Shot 2022-10-24 at 8 43 58 PM" src="https://user-images.githubusercontent.com/29922887/197558387-1a31d873-9e34-43f3-8a61-1f24025473da.png">

2022-10-25 04:52 UTC, kavinvenkatachalam requested changes
@FroostyCodes Thanks for the PR.

Instead of looping and finding the name of the version, we can maintain it in the state. We already have a `deletingVersionId` state which can be changed to `deletingVersion` and maintain both `{ id: version.id, name: version.name }` in the state. This avoids an unnecessary loop to find the name of the version.

2022-10-25 04:52 UTC, kavinvenkatachalam commented on frontend/src/Editor/AppVersionsManager.jsx
> +                )}
```suggestion
                  { version: deletingVersion?.name ?? '' }
```

2022-10-25 04:52 UTC, kavinvenkatachalam commented on frontend/src/Editor/AppVersionsManager.jsx
>                  queryConfirmationData={deletingVersionId}
```suggestion
                queryConfirmationData={deletingVersion.id}
```

2022-10-26 05:10 UTC, kavinvenkatachalam approved these changes
LGTM

2022-10-27 06:20 UTC, merged

2022-11-03 16:43 UTC, withshubh commented
Hey @FroostyCodes 
Thanks for contributing to ToolJet. :raised_hands: 
Please submit the form to claim your Hacktoberfest swag: https://airtable.com/shr1qR6xhqsWO7LD7