[ Enhancement ] : Adding PDF downloading option in Table widget
ToolJet/ToolJet pull request #4597
Opened 2022-10-25 06:37 UTC by manishkushare

Resolves #4596

2022-11-15 11:39 UTC, sherfin94 requested changes
Requested a small change.

2022-11-21 05:52 UTC, sherfin94 submitted a review, later dismissed
Hey @manishkushare , I've approved, but a dev freeze policy is in place right now, I will merge this as soon as dev freeze is lifted.

2022-11-21 07:40 UTC, shubh22 commented
Task linked: [CU-31a0phm Pdf download for Tables](https://app.clickup.com/t/31a0phm)

2022-12-19 09:42 UTC, sherfin94 approved these changes

2022-12-19 09:42 UTC, merged