Update theme.css
ToolJet/ToolJet pull request #4608
Opened 2022-10-25 19:20 UTC by AyushK-101

Fixes #4382 
Proper dropdown option selection highlight for dark mode

![image](https://user-images.githubusercontent.com/86164395/197862772-ec1ff461-cdf6-4db8-b320-6174fb82fd0f.png)

@withshubh made a few changes, please review

2022-10-31 13:51 UTC, AyushK-101 commented
@arpitnath could you please review this

2022-11-02 05:53 UTC, arpitnath requested changes

2022-11-02 05:53 UTC, arpitnath commented on frontend/src/_styles/theme.scss
> +      background: rgba(137, 196, 244,1) !important;
Can we use 
```suggestion
   background: $primary-rgb-darker !important;
```

2022-11-05 18:51 UTC, AyushK-101 commented
@arpitnath I've made the required changes

2022-11-21 11:12 UTC, arpitnath commented
@AyushK-101 Could you pls resolve the conflicts?

2022-11-21 11:12 UTC, arpitnath submitted a review, later dismissed
LGTM!

2023-02-13 06:47 UTC, arpitnath commented
The issue is not present in the current `develop` branch

2023-02-13 06:47 UTC, closed without merging