Added frontend and backend validation
ToolJet/ToolJet pull request #4612
Opened 2022-10-26 05:36 UTC by Frenchtoast0

2022-10-26 05:38 UTC, Frenchtoast0 commented
https://github.com/ToolJet/ToolJet/issues/4413

2022-11-04 05:36 UTC, Frenchtoast0 commented
Package.lock wasn’t meant to be changed.  The changes can be ignored when resolving the merge,

2022-11-15 17:25 UTC, gsmithun4 requested changes

2022-11-15 17:25 UTC, gsmithun4 commented on frontend/src/Editor/AppVersionsManager.jsx
> +    } else {
```suggestion
    if (versionName.length > 25) {
      toast.error('The version name should not be longer than 25 characters');
      setIsCreatingVersion(false);
      return;
    }
    if (versionName == '') {
      toast.error('The version name should not be empty');
      setIsCreatingVersion(false);
      return;
    }
```
To get rid of if else

2022-11-18 07:51 UTC, gsmithun4 approved these changes

2022-11-22 12:21 UTC, merged