[docs] form and table improvements
ToolJet/ToolJet pull request #4730
Opened 2022-11-08 01:03 UTC by withshubh

#### changes
- added doc for form component
- updated table doc with all the feature updates

2022-11-08 01:05 UTC, withshubh commented
- @kavinvenkatachalam please review the form doc
- @stepinfwd Please review the table doc, and let me know if anything is missing. Also, need your help with the description for `Server-side sort` and `Server-side filter`

2022-11-08 01:37 UTC, kavinvenkatachalam commented
@withshubh There are two property section in the doc for the `FORM` widget . Can we make it one?

<img width="666" alt="image" src="https://user-images.githubusercontent.com/50441969/200452448-dfa43895-41d1-4246-96b3-b69fdeb25db8.png">

2022-11-09 08:15 UTC, withshubh commented
@kavinvenkatachalam moved the form doc(with changes suggested) in the feature PR: https://github.com/ToolJet/ToolJet/pull/4595/files

2022-11-14 12:37 UTC, sherfin94 commented on docs/docs/widgets/table.md
> +This event is triggered when filter is added from the header of the table. `filters` property of the table is updated with an object for each filter added. The objects will have `condition`, `value`,
```suggestion
This event is triggered when filter is added, removed, or updated from the filter section of the table. `filters` property of the table is updated to reflect the status of filters applied. The objects will have properties: `condition`, `value`, and `column`. 
```

2022-11-14 12:38 UTC, sherfin94 requested changes
I've made a small suggestion, but good work anyway!

2022-11-15 06:21 UTC, withshubh commented on docs/docs/widgets/table.md
> +
```suggestion
### Server-side sort
When Server-side sort is enabled, clicking on the column headers will not automatically sort the table, instead, the `Sort applied` event will be fired and the applied sorting will be exposed as `sortApplied`. You can use this data to run any query that feeds data to the table in a manner that reflects the sorting applied.
```

2022-11-15 06:22 UTC, withshubh commented on docs/docs/widgets/table.md
> +
```suggestion
### Server-side filter
When Server-side filter is enabled, applying filters will not automatically filter the table, instead, the `Filter changed` event will be fired and the applied filters will be exposed as `filters`. You can use this data to run any query that feeds data to the table in a manner that reflects the filters applied.
```

2022-11-16 08:48 UTC, sherfin94 approved these changes

2022-11-16 08:50 UTC, merged