[doc] marketplace for plugin
ToolJet/ToolJet pull request #4752
Opened 2022-11-12 17:54 UTC by withshubh

#### changes
- added env var for enabling marketplace in the `environment variables` doc
- added doc for the plugin marketplace

2022-11-12 17:55 UTC, withshubh commented
@gondar00 Please review. For some reason I am not able to add you as the reviewer.

2022-11-14 11:03 UTC, gondar00 requested changes

2022-11-14 11:03 UTC, gondar00 commented on docs/docs/marketplace.md
> +- On CLI, you'll be prompted to enter a display name:
```suggestion
- On the CLI, you'll be prompted to enter a display name:
```

2022-11-14 11:03 UTC, gondar00 commented on docs/docs/marketplace.md
> +- Enter the repository URL if the plugin is hosted on GitHub or else just press the enter to skip to the next step
```suggestion
- Enter the repository URL if the plugin is hosted on GitHub or else just press enter to skip to the next step
```

2022-11-14 12:41 UTC, gondar00 approved these changes

2022-11-14 12:42 UTC, merged