Added data-cy for table widget elements
ToolJet/ToolJet pull request #4792
Opened 2022-11-17 09:52 UTC by emidhun

Fixes: #4791

2022-11-17 10:40 UTC, kavinvenkatachalam requested changes
@emidhun There are few empty strings which can removed. Rest everything looks good

2022-11-17 10:40 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Table/Table.jsx
> +                                {' '}
```suggestion
```

2022-11-17 10:40 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Table/Table.jsx
> +                          {' '}
```suggestion
```

2022-11-18 03:00 UTC, emidhun commented
@kavinvenkatachalam Added the mentioned changes.
Please review.

2022-11-18 03:05 UTC, kavinvenkatachalam approved these changes

2022-11-18 03:46 UTC, merged

2022-11-18 04:04 UTC, shubh22 commented
Task linked: [CU-3149bpv Add data-cy for table widget elements.](https://app.clickup.com/t/3149bpv)