Option to toggle display of column hide ::[ Table widget ]
ToolJet/ToolJet pull request #4831
Opened 2022-11-22 12:24 UTC by stepinfwd

closes #4481

2022-11-24 07:34 UTC, shubh22 commented
Task linked: [CU-2x6h5fg Option to switch on/off show hide button : Table widget](https://app.clickup.com/t/2x6h5fg)

2022-11-30 07:12 UTC, sherfin94 requested changes
Please change the property name and corresponding variable names as suggested. Let's not keep misleading names.

2022-11-30 07:12 UTC, sherfin94 commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        displayName: 'Toggle hide columns',
```suggestion
        displayName: 'Hide column selector button',
```

2022-11-30 07:12 UTC, sherfin94 commented on frontend/src/Editor/Components/Table/load-properties-and-styles.js
> +  const toggleShowColumns = properties?.toggleShowColumns ?? false;
```suggestion
  const hideColumnSelectorButton = properties?.hideColumnSelectorButton ?? false;
```
Let's rename likewise everywhere else also

2022-11-30 07:12 UTC, sherfin94 commented on frontend/src/Editor/Components/Table/Table.jsx
> +              {toggleShowColumns && (
```suggestion
              {!hideColumnSelectorButton && (
```
This negation is required given the new property naming.

2022-12-05 11:23 UTC, sherfin94 approved these changes

2022-12-05 11:23 UTC, merged