[doc] Run Python code
ToolJet/ToolJet pull request #4896
Opened 2022-12-05 13:51 UTC by withshubh

#### changes
- added documentation for Run Python code query
- minor updates in Run JavaScript code

2022-12-06 05:06 UTC, Navaneeth-pk commented
@withshubh please link the PR for feature as well, it needs to be approved/merged before merging this.

2022-12-06 06:54 UTC, arpitnath requested changes

2022-12-06 06:54 UTC, arpitnath commented on docs/docs/data-sources/run-py.md
> +- As of now, Run Python code only supports the internal packages only.
```suggestion
- As of now, Run Python code only supports the (Python standard library)[https://docs.python.org/3/library/] only.
```

2022-12-06 06:59 UTC, withshubh commented on docs/docs/data-sources/run-py.md
> +- As of now, Run Python code only supports the (Python standard library)[https://docs.python.org/3/library/] only.
```suggestion
- As of now, Run Python code only supports the [Python standard library](https://docs.python.org/3/library/) only.
```

2022-12-16 09:17 UTC, arpitnath approved these changes

2022-12-19 09:07 UTC, merged