[Feature] :: Allow users to be filtered via status
ToolJet/ToolJet pull request #4908
Opened 2022-12-07 10:15 UTC by vjaris42

Provisioned a user status dropdown through which the users can be filtered in Manage users page.

2022-12-07 10:28 UTC, shubh22 commented
Task linked: [CU-32qyxnm [Feature] :: Allow users to be filtered via status](https://app.clickup.com/t/32qyxnm)

2022-12-13 16:16 UTC, gsmithun4 requested changes

2022-12-13 16:16 UTC, gsmithun4 commented on server/src/services/organizations.service.ts
> +          qb.andWhere('lower(organization_user.status) like :status', {
Should not be wild card search, should be 
```
qb.andWhere('organization_user.status = :status'
```
no need to convert into lower cases

2022-12-13 16:16 UTC, gsmithun4 commented on frontend/ee/components/UsersPage/UsersFilter.jsx
> +const userStatusOptions = [
there should be `all` option

2022-12-15 13:34 UTC, gsmithun4 approved these changes

2022-12-19 07:06 UTC, merged