Feature :: onboarding self hosted users
ToolJet/ToolJet pull request #4933
Opened 2022-12-09 13:37 UTC by stepinfwd

2022-12-16 12:00 UTC, kavinvenkatachalam requested changes
@stepinfwd Suggested few minor code changes. Other than that,

1. `Skip` and `Back` button in UI, seems like disabled. 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/50441969/208093241-b0063bd8-07c9-481d-9352-e92da6bef00a.png">
2. I see few console errors, can you please check it?

<img width="809" alt="image" src="https://user-images.githubusercontent.com/50441969/208093378-2e741a54-8981-4fc2-9743-e68f54d3aad5.png">

2022-12-16 12:00 UTC, kavinvenkatachalam commented on frontend/src/OnBoardingForm/ContinueButtonSelfHost.jsx
> +import { validateEmail } from '../_helpers/utils';
```suggestion
import { validateEmail } from '@/_helpers/utils';
```

2022-12-16 12:00 UTC, kavinvenkatachalam commented on frontend/src/OnBoardingForm/ContinueButtonSelfHost.jsx
> +    else setActiveCondition(!companySize);
Can we use `switch` instead of multiple `else if`?

2022-12-16 12:00 UTC, kavinvenkatachalam commented on frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
> +
```suggestion
```

2022-12-16 12:00 UTC, kavinvenkatachalam commented on frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
> +
```suggestion
```

2022-12-16 12:00 UTC, kavinvenkatachalam commented on frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
> +
```suggestion
```

2022-12-16 12:00 UTC, kavinvenkatachalam commented on frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
> +
```suggestion
```

2022-12-20 08:17 UTC, kavinvenkatachalam submitted a review, later dismissed
LGTM

2022-12-20 08:41 UTC, shah21 commented on frontend/src/OnBoardingForm/ContinueButton.jsx
> +        setPage((currPage) => currPage + 1);
What if the user presses the key when he is on page 2? IMO. its better to do it like this 
         `page != 2 && setPage((currPage) => currPage + 1);`

2022-12-20 08:57 UTC, shah21 commented on frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
> +  };
You can use this function as a helper function on both 
`frontend/src/OnBoardingForm/OnbboardingFromSH.jsx` and `frontend/src/OnBoardingForm/OnBoardingForm.jsx` pages

2022-12-20 09:40 UTC, shah21 commented on frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
> +  const ON_BOARDING_ROLES = [
If its the same for Self host and normal onboarding process you can reuse this as well

2022-12-20 09:43 UTC, shah21 requested changes
I have put some comments above, apart from those LGTM

2022-12-20 14:20 UTC, shah21 approved these changes
LGTM

2022-12-20 18:43 UTC, merged