Make encrypted fields editable
ToolJet/ToolJet pull request #5008
Opened 2022-12-19 04:46 UTC by vjaris42

2022-12-19 18:28 UTC, gsmithun4 requested changes
On create hide edit toggle switch
Click on edit and keep the field empty is not resetting the value

2022-12-20 03:25 UTC, kavinvenkatachalam requested changes
@vjaris42 Few suggestions,

- Placement of the toggle seems different. Instead of setting it below, we can place to the right of the label. Check with Jaseem, he might help with the right placement
<img width="718" alt="image" src="https://user-images.githubusercontent.com/50441969/208573771-a518130f-0eb5-4a49-8812-56afac51d0d5.png">

- When I try to toggle the switch for the first time, it is not selecting/unselecting the value. It works only after the second selection. Attaching the GIF,

![Dec-20-2022 08-53-55](https://user-images.githubusercontent.com/50441969/208574225-955354aa-a0c2-4860-9c20-b1ba92131d12.gif)

2022-12-20 11:07 UTC, kavinvenkatachalam submitted a review, later dismissed

2022-12-20 14:01 UTC, shubh22 commented
Task linked: [CU-85zrgm4y6 Make encrypted fields editable](https://app.clickup.com/t/85zrgm4y6)

2022-12-21 07:03 UTC, merged