[v2-beta] Improvement - Editor
ToolJet/ToolJet pull request #5038
Opened 2022-12-22 14:08 UTC by gsmithun4

2022-12-23 03:26 UTC, kavinvenkatachalam requested changes
@gsmithun4 Suggested a minor changes

2022-12-23 03:26 UTC, kavinvenkatachalam commented on frontend/src/_components/SearchBox.jsx
> +    } else {
`useMounted` hook can be used here.

2022-12-23 03:26 UTC, kavinvenkatachalam commented on frontend/src/AppLoader/AppLoader.jsx
> +              )}{' '}
```suggestion
              )}
```

2022-12-29 09:35 UTC, sherfin94 requested changes
Hey @gsmithun4 , when a version is released, the app automatically switches to the home page instead of staying in the current page. Please check.

2022-12-30 09:10 UTC, sherfin94 approved these changes

2022-12-30 09:17 UTC, kavinvenkatachalam approved these changes
LGTM

2022-12-30 09:26 UTC, merged