[Tooljet db]improvements to pagination
ToolJet/ToolJet pull request #5053
Opened 2022-12-26 12:32 UTC by arpitnath

2022-12-26 20:45 UTC, shubh22 commented
Task linked: [CU-85zrgx679 Improvement to Pagination](https://app.clickup.com/t/85zrgx679)

2022-12-27 05:08 UTC, gondar00 requested changes

2022-12-27 05:08 UTC, gondar00 commented on frontend/src/TooljetDatabase/TooljetDatabasePage/index.jsx
> -          postgrestQueryBuilder.current.filterQuery[operator](column, value);
Lets use postgrestQueryBuilder to build the query

2022-12-27 05:08 UTC, gondar00 commented on frontend/src/TooljetDatabase/Table/Footer.jsx
> +            fetchTableData(`?limit=${pageSize}&offset=0`, pageSize, 1, filters);
`limit` and `offset` need to be set in the constructor of `postgrestQueryBuilder`

2022-12-27 05:09 UTC, gondar00 commented
@arpitnath most of the items we discussed yesterday are fixed, have found a few other points that I am listing below

```
1. Filter + sort combination is broken
2. Need to make use of PostgrestQueryBuilder
3. Switching tables doesn't clear earlier applied filter/sort values
4. Pagination query params get reset (to default limit and offset) upon delete row operation
5. Total number of records don't change upon add row operation
```

2022-12-29 07:20 UTC, gondar00 commented on frontend/src/TooljetDatabase/Sort/index.jsx
> +    }
Can this be in an if-else block?

2022-12-29 07:20 UTC, gondar00 commented on frontend/src/TooljetDatabase/Sort/index.jsx
> +        // if (!show) onClose(filters);
Can remove this line

2022-12-29 07:20 UTC, gondar00 commented on frontend/src/TooljetDatabase/Table/index.jsx
> +          tableDataLength={tableData.length}
Can we please directly derive these values from the `useContext` inside `TableFooter`

2022-12-29 07:20 UTC, gondar00 commented on frontend/src/TooljetDatabase/usePostgrestQueryBuilder.jsx
> +          }
This can be removed as there might be a case of filtering on multiple columns 
ex: id equals 9 && id not equals 10 return all rows that match

2022-12-29 08:18 UTC, gondar00 approved these changes

2022-12-29 08:18 UTC, merged