[ Bug fixed ]: Should be workspace instead of organization
ToolJet/ToolJet pull request #5095
Opened 2022-12-29 07:37 UTC by manishkushare

Resolves : 

Replace  Add new organization with Add new workspace
<img width="240" alt="Screenshot 2022-12-23 at 4 13 27 PM" src="https://user-images.githubusercontent.com/37823141/209918586-1de6358c-edfd-496d-9f27-3e215014c2a9.png">

Replace Organization-settings with Workspace-settings
<img width="642" alt="Screenshot 2022-12-23 at 4 17 57 PM" src="https://user-images.githubusercontent.com/37823141/209918600-4be05b6f-0855-40dd-b127-2309065d2361.png">

2022-12-29 07:37 UTC, shubh22 commented
Task linked: [CU-85zrgt4d1 should be workspace instead of organization](https://app.clickup.com/t/85zrgt4d1)

2022-12-30 04:09 UTC, kavinvenkatachalam requested changes
@manishkushare Can you remove the unwanted code?

2022-12-30 04:09 UTC, kavinvenkatachalam commented on frontend/src/_components/OrganizationManager/CustomSelect.jsx
> +          </svg>{' '}
```suggestion
          </svg>
```

2023-01-02 12:09 UTC, sherfin94 approved these changes

2023-01-02 12:11 UTC, merged