[ Bug fixed ] : UI is not consistent when query name is large in query panel header
ToolJet/ToolJet pull request #5098
Opened 2022-12-29 09:26 UTC by manishkushare

Resolves :
In the query panel header, when the query name is too long, it overlaps with buttons present in the query panel header

![Screenshot - 2022-12-28T112709 641](https://user-images.githubusercontent.com/37823141/209931320-97862504-2de5-476d-9975-e190c2064533.png)

2022-12-29 09:27 UTC, shubh22 commented
Task linked: [CU-85zrgzcdm UI is not consistent when query name is large.](https://app.clickup.com/t/85zrgzcdm)

2022-12-30 03:49 UTC, kavinvenkatachalam requested changes
@manishkushare Instead of substring we can do it in a simple CSS as follows: 

`width: 100px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;`

Adjust the width as per your need

2023-01-03 03:08 UTC, kavinvenkatachalam requested changes
`Input` field is not looking good. Please take a look

<img width="116" alt="image" src="https://user-images.githubusercontent.com/50441969/210295440-9cbf2990-b8c8-4655-8d07-f10ed441ca48.png">

<img width="115" alt="image" src="https://user-images.githubusercontent.com/50441969/210295464-1fed7c3d-fcfb-44cb-b435-ff7d6decb2e4.png">

2023-01-03 09:34 UTC, kavinvenkatachalam approved these changes

2023-01-03 09:34 UTC, merged