[ Bug fixed ] : Edit version pop-up is not getting closed after clicking on x button
ToolJet/ToolJet pull request #5118
Opened 2022-12-30 07:22 UTC by manishkushare

Resolves : While editing the version name "X" is not working.

https://user-images.githubusercontent.com/37823141/210044977-d595240a-f973-4280-817c-b989d5b908cb.mp4

2022-12-30 07:23 UTC, shubh22 commented
Task linked: [CU-85zrh21cp While editing the version name "X" is not working.](https://app.clickup.com/t/85zrh21cp)

2023-01-02 02:46 UTC, kavinvenkatachalam requested changes
@manishkushare As we're closing the modal, let it be `false` always

2023-01-02 02:46 UTC, kavinvenkatachalam commented on frontend/src/Editor/AppVersionsManager/EditVersionModal.jsx
> +      closeModal={() => setShowEditAppVersion(!showEditAppVersion)}
```suggestion
      closeModal={() => setShowEditAppVersion(false)}
```

2023-01-03 03:00 UTC, kavinvenkatachalam approved these changes

2023-01-03 03:01 UTC, merged