[ Bug fixed ] : Popover content in left sidebar is not scrollable
ToolJet/ToolJet pull request #5195
Opened 2023-01-04 16:32 UTC by manishkushare

Resolves 
<img width="458" alt="Screenshot 2023-01-04 at 10 01 12 PM" src="https://user-images.githubusercontent.com/37823141/210603219-73f9aff5-37ce-488d-af18-8d2d337549d9.png">

<img width="458" alt="Screenshot 2023-01-04 at 10 01 25 PM" src="https://user-images.githubusercontent.com/37823141/210603253-11625e0e-8af7-4277-8cf6-3c916e26deb0.png">

<img width="782" alt="Screenshot 2023-01-04 at 10 01 42 PM" src="https://user-images.githubusercontent.com/37823141/210603318-32f7f298-e879-4885-ba80-290e1f413467.png">

2023-01-04 16:32 UTC, shubh22 commented
Task linked: [CU-85zrhe1va Popover content is not scrollable in left sidebar](https://app.clickup.com/t/85zrhe1va)

2023-01-05 06:02 UTC, kavinvenkatachalam requested changes
@manishkushare Requested small changes

2023-01-05 06:02 UTC, kavinvenkatachalam commented on frontend/src/_ui/Popover/index.jsx
> +    }
```suggestion
    } 
      return {}
```

No need else statement as we're returning in if

2023-01-05 06:02 UTC, kavinvenkatachalam commented on frontend/src/Editor/LeftSidebar/index.jsx
> +    setPopoverContentHeight(queryPanelHeight);
```suggestion
    popoverContentHeight !== queryPanelHeight && setPopoverContentHeight(queryPanelHeight);
```

Update the height only if both are not equal. It avoids unwanted renders

2023-01-05 09:17 UTC, kavinvenkatachalam approved these changes

2023-01-05 09:17 UTC, merged