Bugfix :: Onboarded data saved to telemetry
ToolJet/ToolJet pull request #5205
Opened 2023-01-05 07:22 UTC by stepinfwd

*onboarded data saving

2023-01-05 12:27 UTC, gsmithun4 requested changes

2023-01-05 12:27 UTC, gsmithun4 commented on frontend/src/_services/authentication.service.js
> -  window.location.href = loginPath + `?redirectTo=${window.location.pathname}`;
is it related to this PR?

2023-01-06 11:57 UTC, gsmithun4 requested changes

2023-01-06 11:57 UTC, gsmithun4 commented on server/src/services/auth.service.ts
> +    await this.metadataService.finishOnboarding(name, email, companyName, companySize, role);
what if this url `https://hub.tooljet.io/subscribe` is not reachable from the instance? should add a try catch for finish onboarding function
https://github.com/ToolJet/ToolJet/pull/5205/files#diff-61222a9e424956861d68b088bbb08a464f1fa5d8a8c8fa7a3cfa116ae1f8170fR42

2023-01-07 17:29 UTC, gsmithun4 commented on server/src/services/auth.service.ts
> +    await this.metadataService.finishOnboarding(name, email, companyName, companySize, role);
and can call this function asynchronously

2023-01-09 12:02 UTC, akshaysasidrn approved these changes

2023-01-09 12:03 UTC, merged