[ Feature added ] :  [Table widget ] adding CSA to un select the row
ToolJet/ToolJet pull request #5320
Opened 2023-01-12 11:39 UTC by manishkushare

Resolves #5318

2023-01-12 11:40 UTC, shubh22 commented
Task linked: [CU-85zrj01gc [Table widget] add csa to unselect the row](https://app.clickup.com/t/85zrj01gc)

2023-01-16 07:35 UTC, sherfin94 requested changes
Suggested a few changes. Please take a look.

2023-01-16 07:35 UTC, sherfin94 commented on frontend/src/Editor/Components/Table/Table.jsx
> +    'UnselectRow',
```suggestion
    'deselectRow',
```

2023-01-16 07:35 UTC, sherfin94 commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        handle: 'UnselectRow',
```suggestion
        handle: 'deselectRow',
```

2023-01-16 07:35 UTC, sherfin94 commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        displayName: 'UnSelect row',
```suggestion
        displayName: 'Deselect row',
```

2023-01-16 07:35 UTC, sherfin94 commented on frontend/src/Editor/Components/Table/Table.jsx
> +          fireEvent('onRowClicked');
There is no need to fire `onRowClicked`.

2023-01-16 07:35 UTC, sherfin94 commented on frontend/src/Editor/Components/Table/Table.jsx
> +        toast.error('The row with given key and value was not selected');
Lets not fire any toast

2023-01-23 15:05 UTC, sherfin94 approved these changes

2023-01-24 15:13 UTC, merged