Fixed default text widget bg color
ToolJet/ToolJet pull request #5343
Opened 2023-01-16 09:50 UTC by Aviroop-001

2023-01-16 09:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=5343) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=5343) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=5343) it.</sub>

2023-02-15 03:29 UTC, kavinvenkatachalam requested changes
@Aviroop-001 It add value to the property. We already have a `styles` key and `backgroundColor` inside it. The value of the backgroundColor is empty. You need to add the value `#fff00000` to it. Attaching the sceenshot,
cc: @arpitnath 
<img width="524" alt="image" src="https://user-images.githubusercontent.com/50441969/218920136-6f82fe03-35c6-40e0-844b-58a0799b9db4.png">

2023-04-10 03:37 UTC, kavinvenkatachalam requested changes
Hey @Aviroop-001,

Can you make the suggested changes?

2023-05-05 12:36 UTC, withshubh commented
Hey @Aviroop-001 - Please update the PR with the changes suggested.

2023-05-10 05:52 UTC, kavinvenkatachalam approved these changes

2023-05-15 19:36 UTC, merged