[ draft ] : Added column highlighting on search to table
ToolJet/ToolJet pull request #5413
Opened 2023-01-24 09:15 UTC by manishkushare

Resolves #2811

2023-01-26 13:09 UTC, shubh22 commented
Task linked: [CU-85zrk4d2z Feature request : column highlighting on search to table](https://app.clickup.com/t/85zrk4d2z)

2023-01-30 02:45 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Table/GenerateEachCellValue.jsx
> +      }}
@manishkushare Why do we need this?

2023-01-30 02:46 UTC, kavinvenkatachalam reviewed
@sherfin94 Can you check this PR?

2023-02-09 05:20 UTC, kavinvenkatachalam requested changes
@manishkushare Highlight is not working when I search with default data. Could you please check that?

2023-02-15 04:22 UTC, kavinvenkatachalam approved these changes

2023-02-17 05:25 UTC, kavinvenkatachalam approved these changes

2023-02-23 06:35 UTC, merged