[ Feature added ] : [ Table ] enable/disable action button
ToolJet/ToolJet pull request #5474
Opened 2023-02-03 07:08 UTC by manishkushare

Resolves #5405

2023-02-03 07:26 UTC, shubh22 commented
Task linked: [CU-85zrm1pe9 Add ability to dynamically enable/disable an action button](https://app.clickup.com/t/85zrm1pe9)

2023-02-08 08:56 UTC, kavinvenkatachalam requested changes
@manishkushare Please check the suggested code changes. Along with that noticed the following issues,

- Tried disabling with `Fx` seems to be not working properly for me. Can you test it out?
- When I turn on Fx, the UI is different. Can we make it consistent with the current FX?
- If possible, try to import with `@` instead of `../../`. It's better readable and consistent through out the codebase

2023-02-08 08:56 UTC, kavinvenkatachalam commented on frontend/src/Editor/Inspector/Components/Table/DisableActionButtonConponent.jsx
> +  const [forceCodeBox, setForceCodeBox] = React.useState(action.forceCodeBox ?? true);
```suggestion
  const [forceCodeBox, setForceCodeBox] = useState(action.forceCodeBox ?? true);
```

2023-02-08 08:56 UTC, kavinvenkatachalam commented on frontend/src/Editor/Inspector/Components/Table/DisableActionButtonConponent.jsx
> +import FxButton from '../../../CodeBuilder/Elements/FxButton';
```suggestion
import { CodeHinter } from '@/Editor/CodeBuilder/CodeHinter';
import FxButton from '@/Editor/CodeBuilder/Elements/FxButton';
```

2023-02-08 08:56 UTC, kavinvenkatachalam commented on frontend/src/Editor/Inspector/Components/Table/DisableActionButtonConponent.jsx
> +    <>
```suggestion
```

Fragment is not needed here

2023-02-08 08:56 UTC, kavinvenkatachalam commented on frontend/src/Editor/Inspector/Components/Table/DisableActionButtonConponent.jsx
> +              active={!forceCodeBox ? true : false}
```suggestion
              active={forceCodeBox ? false: true}
```

2023-02-15 05:12 UTC, kavinvenkatachalam approved these changes

2023-02-23 06:38 UTC, kavinvenkatachalam commented
@manishkushare Can you resolve the conflicts?

2023-03-01 07:04 UTC, kavinvenkatachalam commented
It causes slowness of the app as we need to pass complete currentState to the table column. So, adding this PR `On Hold`

2023-03-15 12:54 UTC, kavinvenkatachalam approved these changes

2023-03-21 11:34 UTC, kavinvenkatachalam approved these changes

2023-03-27 05:36 UTC, kavinvenkatachalam approved these changes

2023-03-27 08:38 UTC, merged