fixes cursor default to pointer
ToolJet/ToolJet pull request #5696
Opened 2023-03-03 11:42 UTC by shauryag2002

fixes #5066 
fixes cursor default to pointer
before fix:
https://user-images.githubusercontent.com/77102885/222711581-09ce0c1f-1b03-4172-b80a-a6d797513fdf.mp4

after fix:
https://user-images.githubusercontent.com/77102885/222711635-43f6f63a-969a-4795-b408-c1ced4adc29f.mp4

2023-03-03 11:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=5696) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=5696) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=5696) it.</sub>

2023-03-19 18:42 UTC, arunava6M commented on frontend/src/_styles/theme.scss
Hey, please correct me if am wrong.
The pointer should come only when onClick prop has been passed to the icon component. But it seems with this change, every time the cursor will be pointer even if no onClick is passed.
Can you make this dependent on the onClick prop ?

2023-04-06 05:57 UTC, kavinvenkatachalam requested changes
@shauryag2002 Thanks for the PR

The cursor should change to pointer only when the `icon` has `onClick` event. Can you please take a pull from latest develop before making changes.

2023-04-06 05:59 UTC, kavinvenkatachalam requested changes
Adding `cursor: pointer` to the `popover-header` is not needed in this case. Can you please remove it?

2023-04-06 05:59 UTC, kavinvenkatachalam commented on frontend/src/_styles/theme.scss
> +      cursor: pointer;
```suggestion
```

2023-04-28 08:50 UTC, kavinvenkatachalam approved these changes

2023-04-29 14:38 UTC, merged