Introduced global state management
ToolJet/ToolJet pull request #5980
Opened 2023-04-10 11:55 UTC by kavinvenkatachalam

Resolves #5979

2023-05-04 11:43 UTC, sherfin94 approved these changes

2023-05-04 12:13 UTC, sherfin94 submitted a review, later dismissed

2023-05-05 17:05 UTC, kavinvenkatachalam commented
@sherfin94 Figured out the following bugs and fixed it -

1. After deleting the last query, the query panel doesn't move the create state (It was still showing the last deleted query values).
2. Query in the inspector was not updated properly (currentState updation issue)
3. After deleting the query, the query needs to be selected by default or if selected query is different from the deleted query, then the selected query should be selected.

cc: @Nandinisaha13

2023-05-09 12:46 UTC, sherfin94 requested changes
Few issues that I've bumped into:

* If a query is renamed, all the run query events lose their connection
* When a query is renamed before Create is clicked, the name goes away after create is clicked.

Please check

2023-05-10 09:10 UTC, sherfin94 approved these changes

2023-05-10 10:13 UTC, sherfin94 approved these changes

2023-05-10 10:14 UTC, merged