Issue no. #5995 fixed
ToolJet/ToolJet pull request #6005
Opened 2023-04-11 16:02 UTC by LalitChauhan27

Fixed typo in app builder empty canvas text

2023-04-11 16:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6005) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6005) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=6005) it.</sub>

2023-04-12 07:22 UTC, kavinvenkatachalam commented on frontend/src/Editor/Container.jsx
> +  React.useEffect(() => { }, [selectedComponents]);
@LalitChauhan27 Can you revert this change? It might throw an error on lint
```suggestion
  React.useEffect(() => {}, [selectedComponents]);
```

2023-04-12 07:23 UTC, kavinvenkatachalam requested changes
@LalitChauhan27 Thanks for the PR.

Requested a minor change

2023-04-12 07:39 UTC, LalitChauhan27 commented
> @LalitChauhan27 Thanks for the PR.
> 
> Requested a minor change

Hey @kavinvenkatachalam, I've made the changes that you have mentioned. Can you please review it now?

2023-04-12 07:43 UTC, kavinvenkatachalam submitted a review, later dismissed

2023-04-12 09:37 UTC, LalitChauhan27 commented
https://github.com/ToolJet/ToolJet/issues/5995#issuecomment-1504827722

Hey @kavinvenkatachalam, I've fixed few more typos mentioned in the above attachment. Please review my latest commit and let me know if any more changes are required.
PFA

2023-04-12 10:30 UTC, kavinvenkatachalam approved these changes

2023-04-27 09:54 UTC, merged