Bugfix - handles plugins to move from gds to lds when importing app to different workspaces
ToolJet/ToolJet pull request #6268
Opened 2023-05-05 12:25 UTC by arpitnath

2023-05-05 12:27 UTC, vjaris42 submitted a review, later dismissed

2023-05-05 13:32 UTC, vjaris42 submitted a review, later dismissed

2023-05-29 18:53 UTC, gsmithun4 requested changes

2023-05-29 18:53 UTC, gsmithun4 commented on server/src/services/app_import_export.service.ts
> +          pluginId: source?.pluginId || null,
will it work for inter-instance imports?
the `source?.pluginId` of an instance won't be available with other

2023-06-15 08:22 UTC, gsmithun4 approved these changes

2023-06-15 12:02 UTC, gsmithun4 approved these changes

2023-06-15 12:02 UTC, merged