[docs]copilot
ToolJet/ToolJet pull request #6310
Opened 2023-05-09 12:37 UTC by withshubh

ref: https://github.com/ToolJet/ToolJet/pull/6074

2023-05-09 12:37 UTC, withshubh commented
**gif pending** @arpitnath

2023-05-11 09:23 UTC, arpitnath requested changes

2023-05-11 09:23 UTC, arpitnath commented on docs/docs/copilot.md
> +In order for Copilot to function, a plain English prompt must be provided within comments. Copilot is capable of manipulating and accessing components, as well as generating code for component specif
```suggestion
For Copilot to operate, it requires a plain English prompt. Copilot possesses the ability to interact with and access components, along with generating code for specific actions related to those components. This capability is made possible by Copilot's awareness of the application's current state.
```

2023-05-11 09:28 UTC, withshubh commented on docs/docs/copilot.md
> +Tooljet Copilot is currently available in public beta for organizations.
```suggestion
Tooljet Copilot is currently available in public beta for all the users.
```

2023-05-15 23:08 UTC, arpitnath requested changes

2023-05-15 23:08 UTC, arpitnath commented on docs/versioned_docs/version-2.5.0/copilot.md
> +To activate Copilot for a ToolJet workspace, the administrator must go to the **workspace settings**, then the **Copilot** section, and toggle on the "**Enable Copilot**" option. Once Copilot is enab
```suggestion
To activate Copilot for a ToolJet workspace, it is necessary to acquire an API key. Once the API key is obtained, Copilot can be enabled by the administrator via the workspace settings. Additionally, users with edit permissions for apps within the workspace can also utilize Copilot.
```

2023-05-15 23:08 UTC, arpitnath commented on docs/versioned_docs/version-2.5.0/copilot.md
> +- A **new API key** will be needed for each workspace, with *only one user (admin)* allowed per workspace.
can remove this

2023-05-16 09:23 UTC, arpitnath commented on docs/docs/copilot.md
> +Tooljet Copilot is currently available in public beta for all the users.
```suggestion
ToolJet Copilot is currently available in public beta for all the users.
```

2023-05-16 09:24 UTC, arpitnath commented on docs/docs/copilot.md
> +- Copilot can be used by users who have **permissions to edit** the app with a copilot setup.
```suggestion
- Copilot can be used by users who have **permissions to edit** the app with the copilot setup.
```

2023-05-16 10:13 UTC, arpitnath submitted a review, later dismissed

2023-05-17 06:29 UTC, tejakummarikuntla reviewed
Added some reviews to improve the delivery of the phrases, to keep it professional try to stick to a constant voice.

-- Teja, Grammarly, ChatGPT

2023-05-17 06:29 UTC, tejakummarikuntla commented on docs/docs/copilot.md
> +To access the Copilot, each user, including administrators, can sign up for the waitlist program individually. After signing up, each user will receive a unique API key associated with their account.
To gain access to Copilot, all users, including administrators, can individually sign up for the waitlist program. Upon successful sign up, each user will be issued a distinctive API key linked to their account. However, the exclusive authority to activate Copilot within the workspace settings lies solely with administrators. Administrators can proceed to the Copilot section in the workspace settings, where they can utilize their respective API key to set the "Enable Copilot" toggle option.

2023-05-17 06:29 UTC, tejakummarikuntla commented on docs/docs/copilot.md
> +For Copilot to operate, it requires a plain English prompt. Copilot possesses the ability to interact with and access components, along with generating code for specific actions related to those comp
Copilot's functionality relies on the provision of clear and concise plain English prompts. It possesses the capability to interact with and retrieve information from various components, enabling it to generate code specific to the desired actions associated with those components. This capability is facilitated by Copilot's comprehensive understanding of the application's present state.

2023-05-17 06:29 UTC, tejakummarikuntla commented on docs/docs/copilot.md
> +
Let's try to avoid statements starting with "Let us", "We will" in the documentation, please stick to a constant voice.

2023-05-17 06:46 UTC, withshubh commented on docs/docs/copilot.md
> +To access the Copilot, each user, including administrators, can sign up for the waitlist program individually. After signing up, each user will receive a unique API key associated with their account.
```suggestion
To gain access to Copilot, all users, including administrators, can individually sign up for the waitlist program. Upon successful sign up, each user will be issued a distinctive API key linked to their account. However, the exclusive authority to activate Copilot within the workspace settings lies solely with administrators. Administrators can proceed to the Copilot section in the workspace settings, where they can utilize their respective API key to set the "Enable Copilot" toggle option.
```

2023-05-17 06:47 UTC, withshubh commented on docs/versioned_docs/version-2.5.0/copilot.md
> +To access the Copilot, each user, including administrators, can sign up for the waitlist program individually. After signing up, each user will receive a unique API key associated with their account.
```suggestion
To gain access to Copilot, all users, including administrators, can individually sign up for the waitlist program. Upon successful sign up, each user will be issued a distinctive API key linked to their account. However, the exclusive authority to activate Copilot within the workspace settings lies solely with administrators. Administrators can proceed to the Copilot section in the workspace settings, where they can utilize their respective API key to set the "Enable Copilot" toggle option.
```

2023-05-17 06:48 UTC, withshubh commented on docs/docs/copilot.md
> +For Copilot to operate, it requires a plain English prompt. Copilot possesses the ability to interact with and access components, along with generating code for specific actions related to those comp
```suggestion
Copilot's functionality relies on the provision of clear and concise plain English prompts. It possesses the capability to interact with and retrieve information from various components, enabling it to generate code specific to the desired actions associated with those components. This capability is facilitated by Copilot's comprehensive understanding of the application's present state.
```

2023-05-17 06:49 UTC, withshubh commented on docs/versioned_docs/version-2.5.0/copilot.md
> +For Copilot to operate, it requires a plain English prompt. Copilot possesses the ability to interact with and access components, along with generating code for specific actions related to those comp
```suggestion
Copilot's functionality relies on the provision of clear and concise plain English prompts. It possesses the capability to interact with and retrieve information from various components, enabling it to generate code specific to the desired actions associated with those components. This capability is facilitated by Copilot's comprehensive understanding of the application's present state.
```

2023-05-17 06:50 UTC, withshubh commented on docs/docs/copilot.md
> +We will demonstrate the usage of copilot by generating a SQL query to fetch the order details from a PostgreSQL database based on the key provided in the REST API data.
```suggestion
This example demonstrates the usage of copilot by generating a SQL query to fetch the order details from a PostgreSQL database based on the key provided in the REST API data.
```

2023-05-17 06:50 UTC, withshubh commented on docs/docs/copilot.md
> +- Let's create a RESTAPI query using this mock api endpoint: https://fakestoreapi.com/users/1
```suggestion
- Create a RESTAPI query using this mock api endpoint: https://fakestoreapi.com/users/1
```

2023-05-17 06:51 UTC, withshubh commented on docs/versioned_docs/version-2.5.0/copilot.md
> +We will demonstrate the usage of copilot by generating a SQL query to fetch the order details from a PostgreSQL database based on the key provided in the REST API data.
```suggestion
This example demonstrates the usage of copilot by generating a SQL query to fetch the order details from a PostgreSQL database based on the key provided in the REST API data.
```

2023-05-17 06:52 UTC, withshubh commented on docs/versioned_docs/version-2.5.0/copilot.md
> +- Let's create a RESTAPI query using this mock api endpoint: https://fakestoreapi.com/users/1
```suggestion
- Create a RESTAPI query using this mock api endpoint: https://fakestoreapi.com/users/1
```

2023-05-17 06:54 UTC, tejakummarikuntla approved these changes

2023-05-17 07:48 UTC, merged