Modified the null placeholder in phonenumber field to +1 in both lightMode and darkMode pages
ToolJet/ToolJet pull request #6478
Opened 2023-05-19 14:39 UTC by FourAndHalf

Added default country code to the previously empty box
Fixes issue #6437

**Changed the values assigned as default from ' ' to '+1' on both pages** 
 
```jsx
  const [formData, setFormData] = useState({
    companyName: '',
    role: '',
    companySize: '',
```
```diff
- phoneNumber: ' ',
+ phoneNumber: '+1',
```
```jsx
   )};
```

The place for correction that was shared before in the earlier screenshot was actually on the page's form titles
```jsx
const FORM_TITLES = [
    `Where do you work ${userDetails?.name}?`,
    'What best describes your role?',
    'What is the size of your company?',
    'Enter your phone number',
    'Enter your phone number', //dummy for styling
  ];
```

I also looked up how to change the displayed flag, but it was set using a dependency library. I don't anything can be done about it by me. 
```jsx
import PhoneInput from 'react-phone-input-2';
import 'react-phone-input-2/lib/style.css';
```

2023-05-19 14:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6478) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6478) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=6478) it.</sub>

2023-05-29 14:15 UTC, iSatVeerSingh commented on frontend/src/OnBoardingForm/OnBoardingForm.jsx
> +    phoneNumber: '+1',
I tried it and this is not working. You should set a default county as "US" in phone input.

2023-05-29 14:15 UTC, iSatVeerSingh commented on frontend/src/OnBoardingForm/OnbboardingFromSH.jsx
> +    phoneNumber: '+1',
Also for this.

2023-05-29 14:19 UTC, iSatVeerSingh commented
Also update the line "Fixes issue https://github.com/ToolJet/ToolJet/issues/6437" to "Fixes #6437". So the issue can automatically close when PR get merge.

2023-05-30 09:27 UTC, johnsoncherian commented
@FourAndHalf this solution does not seem to be working. Try passing country directly in input field as mentioned in previous comments. Refer this documentation for better understanding:
https://www.npmjs.com/package/react-phone-input-2

2023-05-30 09:28 UTC, johnsoncherian requested changes
@FourAndHalf this solution does not seem to be working. Try passing country directly in input field as mentioned in previous comments. Refer this documentation for better understanding:
https://www.npmjs.com/package/react-phone-input-2

2023-05-31 05:49 UTC, closed without merging