Test PR for github secrets
ToolJet/ToolJet pull request #6592
Opened 2023-05-30 07:27 UTC by emidhun

2023-05-30 11:57 UTC, adishM98 approved these changes

2023-05-30 11:59 UTC, emidhun commented
@akshaysasidrn Please review and let me know If there is something we can improve.
Thank you.

2023-05-31 06:13 UTC, akshaysasidrn requested changes

2023-05-31 09:44 UTC, emidhun commented on .github/workflows/cypress.yml
> +          until curl --silent --fail https://tooljet-pr-${{ env.PR_NUMBER }}.onrender.com; do
Updated the timeout to 25 minutes and added the interval of 100sec.

2023-05-31 10:32 UTC, adishM98 approved these changes

2023-05-31 11:47 UTC, akshaysasidrn approved these changes

2023-05-31 11:48 UTC, merged