bug fixed : Changed the callout type from tip to warning
ToolJet/ToolJet pull request #6631
Opened 2023-06-03 05:23 UTC by gantanikhilraj

closes issue #6604

2023-06-03 05:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6631) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6631) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=6631) it.</sub>

2023-06-05 06:14 UTC, withshubh requested changes
- Please keep the `warning` text lowercase
- [All the versions](https://github.com/ToolJet/ToolJet/tree/develop/docs/versioned_docs?rgh-link-date=2023-05-30T10%3A43%3A10Z) from 1.x.x to 2.6.0 and the base [docs/docs](https://github.com/ToolJet/ToolJet/tree/develop/docs/docs?rgh-link-date=2023-05-30T10%3A43%3A10Z) needs this change, you have only updated the `1.x.x`

2023-06-05 09:29 UTC, gantanikhilraj commented
@withshubh , Updated, please let me know if there are any changes to make ?

2023-06-14 11:08 UTC, withshubh commented on docs/versioned_docs/version-1.x.x/contributing-guide/setup/docker.md
> +:::WARNING
I think you missed this, please make lowercase

2023-06-14 11:09 UTC, withshubh requested changes
Please make the change suggested!

2023-06-21 11:00 UTC, withshubh approved these changes
Thanks for contributing to ToolJet! 🚀

2023-06-21 11:34 UTC, merged