Enhancement/left side drawer ux
ToolJet/ToolJet pull request #6659
Opened 2023-06-06 10:58 UTC by johnsoncherian

2023-06-08 11:44 UTC, kavinvenkatachalam requested changes
@johnsoncherian Requested few code changes. If we're not using the `prevState` while setting the state we can use the value directly to set the state instead of using the callbacks.

2023-06-08 11:44 UTC, kavinvenkatachalam commented on frontend/src/Editor/LeftSidebar/SidebarDebugger.jsx
> +  const elemRef = useRef();
This can be removed if it's not used anywhere

2023-06-08 11:44 UTC, kavinvenkatachalam commented on frontend/src/Editor/LeftSidebar/index.jsx
> +  const [unReadErrorCount, setUnReadErrorCount] = React.useState({ read: 0, unread: 0 });
```suggestion
  const [errorLogs, setErrorLogs] = useState([]);
  const [errorHistory, setErrorHistory] = useState({ appLevel: [], pageLevel: [] });
  const [unReadErrorCount, setUnReadErrorCount] = useState({ read: 0, unread: 0 });
```

`useState` is already imported and we can use it directly. We can maintain the consistency

2023-06-08 11:44 UTC, kavinvenkatachalam commented on frontend/src/Editor/LeftSidebar/index.jsx
> +    setErrorHistory(() => ({ appLevel: [], pageLevel: [] }));
```suggestion
    setUnReadErrorCount({ read: 0, unread: 0 });

    setErrorLogs([]);
    setErrorHistory({ appLevel: [], pageLevel: [] });
```

2023-06-08 11:44 UTC, kavinvenkatachalam commented on frontend/src/Editor/LeftSidebar/index.jsx
> +  React.useEffect(() => {
```suggestion
 useEffect(() => {
```

2023-06-08 11:44 UTC, kavinvenkatachalam commented on frontend/src/Editor/LeftSidebar/index.jsx
> +  React.useEffect(() => {
```suggestion
 useEffect(() => {
```

2023-06-13 03:17 UTC, kavinvenkatachalam requested changes
@johnsoncherian Few suggestions,

1. `queryPanelHeight` can be removed from the state and it can be fetched directly from the store. This avoids one cycle of re-render and doesn't cause any issue on the UI
2. There is some miscalculation in the width. I can see the scrollbar without even opening the pages sidebar. Attaching the screenshot

<img width="1602" alt="image" src="https://github.com/ToolJet/ToolJet/assets/50441969/867f0014-d019-4ff7-b0cf-5d24545383c4">

2023-06-13 03:17 UTC, kavinvenkatachalam commented on frontend/src/Editor/Editor.jsx
> +    }
```suggestion
```

2023-06-13 03:17 UTC, kavinvenkatachalam commented on frontend/src/Editor/Editor.jsx
> +    return `calc(${100}% - ${Math.max(this.state.queryPanelHeight + 45, 85)}px)`;
```suggestion
    return `calc(${100}% - ${Math.max(useQueryPanelStore.getState().queryPanelHeight + 45, 85)}px)`;
```

2023-06-15 05:50 UTC, kavinvenkatachalam approved these changes

2023-06-15 07:17 UTC, withshubh commented
Documented: https://github.com/ToolJet/ToolJet/pull/6609

2023-06-15 07:28 UTC, merged