fix: Added onKeyDown function for input field
ToolJet/ToolJet pull request #6699
Opened 2023-06-12 14:05 UTC by coderSuren

Fixes #6653 

Added onkeyDown functionality for input field, which triggers create workspace button on pressing Enter key

2023-06-12 14:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6699) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6699) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=6699) it.</sub>

2023-06-14 12:11 UTC, kavinvenkatachalam requested changes
@coderSuren Thanks for the PR.

Requested few changes. Please take a look and update the PR

2023-06-14 12:11 UTC, kavinvenkatachalam commented on frontend/src/_components/OrganizationManager/CreateOrganization.jsx
> +import React, { useState, useRef } from 'react';
```suggestion
import React, { useState } from 'react';
```

2023-06-14 12:11 UTC, kavinvenkatachalam commented on frontend/src/_components/OrganizationManager/CreateOrganization.jsx
> +  const createButtonRef = useRef(null);
```suggestion
```

2023-06-14 12:11 UTC, kavinvenkatachalam commented on frontend/src/_components/OrganizationManager/CreateOrganization.jsx
> +            ref={createButtonRef}
```suggestion
```

2023-06-14 12:11 UTC, kavinvenkatachalam commented on frontend/src/_components/OrganizationManager/CreateOrganization.jsx
> +      createButtonRef.current.click();
```suggestion
      createOrganization()
```

2023-06-14 15:46 UTC, coderSuren commented
@kavinvenkatachalam Thanks for your review, made the requested changes.

2023-06-15 05:17 UTC, kavinvenkatachalam approved these changes

2023-06-15 08:02 UTC, merged