[Improvements] Environment changes
ToolJet/ToolJet pull request #6762
Opened 2023-06-16 13:18 UTC by shah21

This PR contains the code changes for multi-environment upcoming improvements

2023-06-19 10:09 UTC, gsmithun4 requested changes

2023-06-19 10:17 UTC, shah21 commented on server/src/services/apps.service.ts
> +          'SELECT app_environments.id, app_environments.default FROM app_environments INNER JOIN app_versions ON app_versions.current_environment_id = app_environments.id;'
No specific reason. should I change to Typeorm one?

2023-07-07 09:37 UTC, gsmithun4 approved these changes

2023-07-07 12:21 UTC, ajith-k-v commented
<h2>Cypress Results</h2>
<table><tr><th>Result</th><th>Passed :white_check_mark:</th><th>Failed :x:</th><th>Pending :hand:</th><th>Skipped :leftwards_arrow_with_hook:</th><th>Duration :clock8:</th></tr><tr><td>Failing :red_circle:</td><td>54</td><td>12</td><td>8</td><td>0</td><td>2379.768s</td></tr></table>
<a href="">

2023-07-10 05:07 UTC, kavinvenkatachalam requested changes
@shah21 Getting an error while trying to release an app. Attaching the screenshot

<img width="440" alt="image" src="https://github.com/ToolJet/ToolJet/assets/50441969/bd82dcde-31a3-489f-a7b5-b1d0295a4996">

2023-07-10 06:16 UTC, shah21 commented
> @shah21 Getting an error while trying to release an app. Attaching the screenshot
> 
> <img alt="image" width="440" src="https://user-images.githubusercontent.com/50441969/252228168-bd82dcde-31a3-489f-a7b5-b1d0295a4996.png">

@kavinvenkatachalam  Did you run migration ? or reset the db? if not, please do it

2023-07-11 04:38 UTC, kavinvenkatachalam approved these changes

2023-07-11 04:40 UTC, merged