Feature :: Form widget with JSON input
ToolJet/ToolJet pull request #6787
Opened 2023-06-20 06:04 UTC by stepinfwd

closes #5821

2023-06-22 06:05 UTC, kavinvenkatachalam requested changes
@stepinfwd Can you test all the components once? Seems like it's not working properly (Tried with `DatePicker` & `CheckBox`)

2023-06-23 12:28 UTC, sherfin94 commented
Hey @stepinfwd , when I tried out, it seemed to crash the existing form widgets, see if you're bumping into the same issue.

To reproduce, goto develop, add a form widget, switch to your branch.

2023-06-26 09:58 UTC, sherfin94 commented
Hey @stepinfwd , lets call this `Use custom schema` instead of `Advanced`: 
<img width="217" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20333972/7bb69557-45b0-41f3-8e7b-23696cb2ed92">

2023-06-26 10:01 UTC, sherfin94 commented
Also @stepinfwd , adding a ` ` after the starting `{{` seems to highlight the entire default schema well, lets do that also: 
<img width="217" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20333972/907cf813-678f-48c9-8c39-2309bb51ba79">

2023-06-27 11:48 UTC, kavinvenkatachalam requested changes
@stepinfwd If I try to delete any style then it is vreaking the form. We can make the styles as optional. Please take a look.

And remove the single quote from the value key to differentiate between the value and key

2023-06-27 11:48 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Form/Form.jsx
> +    return true;
`every` method can be used here

2023-06-27 11:48 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Form/Form.jsx
> +        fireEvent('onInvalid');
Can we have a common function instead of repeating the logic?

2023-06-27 11:48 UTC, kavinvenkatachalam commented on frontend/src/Editor/Components/Form/Form.jsx
> +    setUIComponents(generateUIComponents(JSONSchema, advanced, componentTypes));
```suggestion
    setUIComponents(generateUIComponents(JSONSchema, advanced));
```

`componentTypes` can be imported directly in the utils file

2023-06-29 08:10 UTC, kavinvenkatachalam requested changes
@stepinfwd Few minor suggestions,

1. Please remove the console statement in `Form.jsx`
2. Seems like the background color on canvas is changed in this PR. Please look into it

2023-06-29 08:22 UTC, kavinvenkatachalam approved these changes

2023-07-03 06:16 UTC, kavinvenkatachalam requested changes
@stepinfwd Can we have a common function to test the visibility?

2023-07-03 07:40 UTC, kavinvenkatachalam approved these changes

2023-07-03 10:49 UTC, merged