Feature :: Restrict certain components from being added onto certain container-components
ToolJet/ToolJet pull request #6903
Opened 2023-07-04 07:24 UTC by stepinfwd

closes #6834  
`appbuilder-1.2`

2023-07-11 03:06 UTC, kavinvenkatachalam requested changes
@stepinfwd Instead of passing `restrictedKey` to every component can we maintain the componentType as a key in the `restrictedWidgetsObj`?

2023-07-12 05:37 UTC, kavinvenkatachalam requested changes
@stepinfwd Implementation wise it looks good! One suggestion in the UI - the error message is should be use `break-word` instead of `break-all` in this case

<img width="333" alt="image" src="https://github.com/ToolJet/ToolJet/assets/50441969/63f24bfc-6357-4c37-8fac-45ab01c3dcd0">

2023-07-12 08:53 UTC, kavinvenkatachalam approved these changes

2023-07-19 06:07 UTC, sherfin94 commented
Hey @stepinfwd , adding table to kanban - card is freezing the app, please restrict table also in that.

cc: @kavinvenkatachalam

2023-07-20 08:21 UTC, merged