changed placeholder to be consistent with labels
ToolJet/ToolJet pull request #6959
Opened 2023-07-07 14:14 UTC by JunedKhan101

change enterName value in en.json just in case if it's used somewhere else.

2023-07-07 14:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6959) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=6959) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=6959) it.</sub>

2023-07-17 07:05 UTC, stepinfwd requested changes

2023-07-17 07:05 UTC, stepinfwd commented on frontend/src/ManageOrgUsers/InviteUsersForm.jsx
> +                        placeholder={t('header.organization.menus.manageUsers.enterFulltName', 'Enter full name')}
There is a typo here  and if `organization.menus.manageUsers.enterFullName` is not available add it in `en.json`

2023-07-17 07:10 UTC, stepinfwd commented on frontend/assets/translations/en.json
> +                        "enterName": "Enter Group Name",
change this to `Enter group name`

2023-07-17 07:59 UTC, JunedKhan101 commented on frontend/assets/translations/en.json
> +                        "enterName": "Enter Group Name",
Implemented the change

2023-07-20 11:54 UTC, stepinfwd commented
Hi @JunedKhan101 requested couple for changes

2023-07-21 03:39 UTC, JunedKhan101 commented
@stepinfwd What are the requested changes? I can't see them on my PR. I have resolved changes you mentioned earlier so if you are referring to that I am just letting you know that I have resolved and pushed my new changes.

2023-07-21 06:45 UTC, stepinfwd requested changes

2023-07-22 02:47 UTC, JunedKhan101 commented on frontend/src/ManageGroupPermissions/ManageGroupPermissions.jsx
> +                          'Enter Group Name'
Resolved

2023-07-22 02:47 UTC, JunedKhan101 commented on frontend/assets/translations/en.json
>                      "enterFulltName": "Enter full name",
Removed

2023-07-22 02:47 UTC, JunedKhan101 commented
@stepinfwd Resolved PR comments please verify.

2023-07-24 05:10 UTC, JunedKhan101 commented
@stepinfwd The PR is updated Please check.

2023-07-27 06:35 UTC, stepinfwd approved these changes

2023-08-10 11:19 UTC, kavinvenkatachalam approved these changes

2023-08-10 11:20 UTC, merged