Feature added  to introduce Link column type in table
ToolJet/ToolJet pull request #6961
Opened 2023-07-07 15:34 UTC by manishkushare

Resolves #6848

2023-07-11 04:54 UTC, kavinvenkatachalam requested changes
@manishkushare Few issues/suggestions,

1. When I try to click on the link without changing the link target (default - `New window`) but it still opens in the same page
2. I'm not able to link the tableData with the `Link` type. Like every column, the key should be picked from the table data.
3. When I try to filter it with the link label, it seems to be not working
4. Downloading the table data with link type seems to be not working with label entered

cc: @sherfin94

2023-07-13 08:59 UTC, kavinvenkatachalam approved these changes

2023-07-19 06:31 UTC, sherfin94 requested changes
Hey @manishkushare , let us remove the `Href` property also, it is not needed.

cc: @kavinvenkatachalam

2023-07-19 10:51 UTC, kavinvenkatachalam approved these changes

2023-07-20 09:27 UTC, merged