Fix [Dark Mode] UI inconsistancy
ToolJet/ToolJet pull request #7005
Opened 2023-07-12 09:20 UTC by Dvinod1

2023-07-12 09:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7005) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7005) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=7005) it.</sub>

2023-07-17 06:57 UTC, stepinfwd requested changes
Please revert changes on `package-lock` , `tabler.scss`, `package.json`

2023-07-17 09:11 UTC, Dvinod1 commented
> 

Can I get any help about this, I can't able to solve, I am a little bit confused.

2023-07-17 10:42 UTC, stepinfwd commented
> > 
> 
> Can I get any help about this, I can't able to solve, I am a little bit confused.

we only need changes related to this PR that would be only in `theme.scss` revert all other changes we dont want to make changes in package.json and package lock etc so try to copy paste these files from develop  and check if its resolved

2023-07-20 11:55 UTC, stepinfwd commented on frontend/package.json
> -}
please remove space this too @Dvinod1

2023-07-22 17:16 UTC, Dvinod1 commented on frontend/package.json
> -}
I am not understanding, Please help me?

2023-07-27 07:03 UTC, stepinfwd commented
https://github.com/ToolJet/ToolJet/assets/31006028/cfe46cdb-ff21-4d47-9643-b90652a55d62

Hi @Dvinod1 , you can see a flash while hovering on suggested list please try to remove this

2023-07-28 13:08 UTC, Dvinod1 reviewed
solved the flash problem while hovering

2023-08-09 04:06 UTC, kavinvenkatachalam commented
@Dvinod1 Can you revert the `package.json` changes from the PR?

2023-08-12 14:23 UTC, Dvinod1 commented
> @Dvinod1 Can you revert the `package.json` changes from the PR?

I am not understanding how to do it, can you help me ? Please.

2023-08-17 19:42 UTC, stepinfwd commented
> > @Dvinod1 Can you revert the `package.json` changes from the PR?
> > @kavinvenkatachalam
> > I am not understanding how to do it, can you help me ? Please.

There is only an extra space in package.json just remove that 

> > @Dvinod1 Can you revert the `package.json` changes from the PR?
> > @kavinvenkatachalam
> > I am not understanding how to do it, can you help me ? Please.

There is some extra space in package.json file just remove that ,  finally in this PR there should be change only in theme.scss

2023-08-20 10:33 UTC, Dvinod1 reviewed
I have removed the changes in package.json

2023-09-13 12:54 UTC, stepinfwd submitted a review, later dismissed

2023-09-14 12:38 UTC, stepinfwd commented
@Dvinod1  please resolve conflicts

2023-09-26 05:47 UTC, stepinfwd commented
@Dvinod1  Please resolve the conflicts we want to get this PR merged

2023-09-26 14:43 UTC, Dvinod1 commented
I have resolved the conflict , please check

2023-09-29 04:52 UTC, kavinvenkatachalam approved these changes

2023-09-29 04:52 UTC, merged

2023-09-29 14:28 UTC, Dvinod1 commented
Wow, Finally my First PR got merged feeling good, 
Thanks to all and many more to come, learned a lot.