runjs arguments support
ToolJet/ToolJet pull request #7033
Opened 2023-07-14 09:47 UTC by johnsoncherian

2023-07-19 04:39 UTC, kavinvenkatachalam requested changes
Hey @johnsoncherian - Found few issues,

1) Able to create params with the same name
2) Getting the unsaved popup without making any changes on runJS

2023-07-19 04:39 UTC, kavinvenkatachalam commented on frontend/src/Editor/Inspector/ActionConfigurationPanels/RunjsParamters.jsx
> +import { CodeHinter } from '../../CodeBuilder/CodeHinter';
```suggestion
import { CodeHinter } from '@/Editor/CodeBuilder/CodeHinter';
```

2023-07-19 04:39 UTC, kavinvenkatachalam commented on frontend/src/Editor/QueryManager/QueryEditors/Runjs/ParameterForm.jsx
> +    console.log(otherParams, name);
```suggestion
```

2023-07-19 04:39 UTC, kavinvenkatachalam commented on frontend/src/_helpers/appUtils.js
> +            (k) => (resolvedParams[k] = resolveReferences(params[k], _ref.state.currentState, undefined))
Instead of `k`, can we have something like `param`

2023-07-19 04:39 UTC, kavinvenkatachalam commented on frontend/src/_helpers/appUtils.js
> +export function previewQuery(_ref, query, calledFromQuery = false, parameters, hasParamSupport) {
Can we add some default value to the newly added params?

2023-07-19 04:39 UTC, kavinvenkatachalam commented on frontend/src/_helpers/appUtils.js
> +export function runQuery(_ref, queryId, queryName, confirmed = undefined, mode = 'edit', parameters) {
Can we add some default value to the newly added params?

2023-07-19 06:34 UTC, kavinvenkatachalam approved these changes

2023-07-19 12:36 UTC, arpitnath requested changes

2023-07-19 12:51 UTC, johnsoncherian commented on frontend/src/Editor/QueryManager/QueryEditors/Runjs/ParameterForm.jsx
> +    if (!isValidVariableName(name)) {
Added check added in page submission level.

2023-07-20 07:25 UTC, arpitnath approved these changes

2023-07-20 11:05 UTC, merged