bug:fixed / PasswordInput Component Not Adapting to Dark Mode
ToolJet/ToolJet pull request #7035
Opened 2023-07-14 17:18 UTC by rahul5522

Fixes : #6880

2023-07-14 17:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7035) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7035) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=7035) it.</sub>

2023-07-27 07:23 UTC, stepinfwd requested changes

2023-07-27 07:23 UTC, stepinfwd commented on frontend/src/Editor/Components/PasswordInput.jsx
> +    backgroundColor: darkMode && '#232e3c',
When background color is changed from styles tab in widget inspector it wont be applied here , you can take reference from `TextInput.jsx` to resolve this

2023-08-02 14:14 UTC, tejakummarikuntla commented
Hey @rahul5522 , were you able to progress with the shared reviews? Kindly address the requested changes to progress the PR.

2023-08-05 18:51 UTC, rahul5522 commented
Hey @tejakummarikuntla , sorry for delayed response was busy with different task. I have committed the changes please review them.

2023-08-10 08:02 UTC, stepinfwd approved these changes

2023-08-11 05:10 UTC, merged