fixed toast for multiple components selection
ToolJet/ToolJet pull request #7239
Opened 2023-08-09 20:10 UTC by ChaitanyaKharya2003

Fixed Issue #7226

2023-08-10 11:56 UTC, tejakummarikuntla commented
Hey @ChaitanyaKharya2003 , thanks for the PR. Please sign the CLA to progress.

2023-08-15 16:45 UTC, Ckbhatia commented on frontend/src/_helpers/appUtils.js
> +    if (newComponentObj.newComponents.length > 1) {
```suggestion
    const successMessage = newComponentObj.newComponents.length > 1 ? "Components copied successfully" : "Component copied successfully";
    toast.success(successMessage);
```

2023-08-19 07:33 UTC, Ckbhatia commented on frontend/src/_helpers/appUtils.js
>        toast.success("Components copied succesfully");
You can remove this and else statement with code as you don't need anymore

2023-08-28 18:21 UTC, stepinfwd requested changes
Remove code from 1354 to 1357 @ChaitanyaKharya2003 we dont need else case and additional toast

2023-09-14 04:27 UTC, nakulnagargade commented
> Remove code from 1354 to 1357 @ChaitanyaKharya2003 we dont need else case and additional toast

@ChaitanyaKharya2003 Please resolve this active comment. Else looks fine.

2023-09-25 10:28 UTC, tejakummarikuntla commented
Hey @ChaitanyaKharya2003, could you please address the reviews? We would not be able to progress it to merge without the suggested changes.

2023-09-27 10:06 UTC, kavinvenkatachalam approved these changes

2023-09-27 11:40 UTC, stepinfwd approved these changes

2023-09-28 10:07 UTC, merged