refactor/ issue #7227:Updated the text on the File picker component.
ToolJet/ToolJet pull request #7292
Opened 2023-08-19 06:49 UTC by divyansshu

Updated the description text on the "File Picker" component from this  "Drag and Drop some files here, or click to select files" 
 to this "Drag and drop files here or click to select files".
 fixes#7227

2023-08-19 06:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7292) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7292) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=7292) it.</sub>

2023-09-14 05:43 UTC, kavinvenkatachalam requested changes
@divyansshu Can you please revert the changes from the files `server/data-migrations/1653472569828-addedInstructionTextPropInFilePickerWidget.ts` and `server/templates/gcs-file-explorer/definition.json`? Rest looks good

2023-09-14 06:33 UTC, divyansshu commented
> @divyansshu Can you please revert the changes from the files `server/data-migrations/1653472569828-addedInstructionTextPropInFilePickerWidget.ts` and `server/templates/gcs-file-explorer/definition.json`? Rest looks good

Hi @kavinvenkatachalam, I have successfully reverted the changes... Thank you

2023-09-21 03:42 UTC, kavinvenkatachalam approved these changes

2023-09-29 04:54 UTC, merged