fix: striped table when element selected is text
ToolJet/ToolJet pull request #740
Opened 2021-09-13 12:40 UTC by gondar00

This PR fixes the table design when combination of a field text + table style striped

Before: 
![image](https://user-images.githubusercontent.com/12490590/133085139-fac7d1b8-d1f5-4947-b499-2bb80150319c.png)

After:
![image](https://user-images.githubusercontent.com/12490590/133084141-4accdc6e-a98c-4fc5-9641-64556236d0c2.png)

2021-09-13 17:42 UTC, Navaneeth-pk commented
![image](https://user-images.githubusercontent.com/7828962/133131192-3c4f4691-1faa-4ff1-9c29-b9d3ba495966.png)

Steps to reproduce: 
a) drag and drop a table widget 
b) set the `email` column as editable 

Can you please take a look? @gondar00

2021-09-14 04:41 UTC, gondar00 commented
I think the above image would've been on a diff. branch

On this branch it looks like the below: 
![image](https://user-images.githubusercontent.com/12490590/133196049-b17cfe3d-94ac-4e07-b462-1ef8c724cfb4.png)

2021-09-14 13:57 UTC, gondar00 commented
1. Making a column editable
2. Making a column type as dropdown 

These I am working on currently

2021-09-15 04:42 UTC, gondar00 commented
Making a column editable is fixed, 

pending is making a column type as datepicker

2021-09-15 05:56 UTC, gondar00 commented
Datepicker fix is done

2021-09-15 08:07 UTC, sherfin94 commented
Looks like we didn't cover action buttons

https://www.loom.com/share/7340770dfe304a9db8c8cbbdac98effc

2021-09-15 10:24 UTC, gondar00 commented
@sherfin94 yeah added fix for action button 👍

2021-09-17 09:28 UTC, sherfin94 commented
There seems to be a strange issue with drop-down, multiselect, badge etc on this branch:
https://www.loom.com/share/3f660dddd2114bb3a508a23a18432e10

A similar issue seems to be there with datepicker also, though its certainly better than what we already have with datepicker :grimacing: .
![image](https://user-images.githubusercontent.com/20333972/133759998-eee802be-c761-4cac-b6ac-0490a9d556bf.png)

2021-09-17 12:26 UTC, gondar00 commented
![image](https://user-images.githubusercontent.com/12490590/133782233-3ea085c0-22f1-4581-a1ef-5187a93e7a10.png)

```

  td {
    min-height: 35px;
    overflow-x: initial; // so due to overflow being initial the content overflows from the box in case of many fields
    margin: auto;
    ....
}
```

2021-09-17 12:28 UTC, gondar00 commented
![image](https://user-images.githubusercontent.com/12490590/133782439-4aeba41b-d390-4958-afc2-78a3f92541fe.png)
```

  td {
    min-height: 35px;
    overflow-x: auto; // i added auto here so that a scrollbar comes, but that has broken select/dropdown 
    margin: auto;
    ....
}
```

2021-09-17 12:37 UTC, gondar00 commented
I'll change it back to `initial` for now

2021-09-26 17:38 UTC, sherfin94 commented
Went through the code, looks nice!.
There is this one last problem I missed: It also has to support proper stripes when validation text is present
![image](https://user-images.githubusercontent.com/20333972/134817746-4a35c831-9341-4e96-a29f-bed141aff8e8.png)

Once that's fixed, could you also merge the latest `develop` to this?

2021-09-26 17:39 UTC, sherfin94 requested changes

2021-09-26 17:39 UTC, sherfin94 commented on frontend/src/Editor/Components/Table/Table.jsx
> +                  <div class="invalid-feedback">{validationError}</div>
```suggestion
                  <div className="invalid-feedback">{validationError}</div>
```

2021-09-27 12:53 UTC, sherfin94 approved these changes

2021-09-27 12:57 UTC, merged