Number/input/field/issue
ToolJet/ToolJet pull request #7415
Opened 2023-09-11 15:10 UTC by S-Abdul-Rahman

Fixed Number Input Field Issue #7414

2023-09-13 08:02 UTC, Ckbhatia commented on frontend/src/Editor/Components/NumberInput.jsx
> +    setValue(Number(parseFloat(e.target.value ? e.target.value : 0).toFixed(properties.decimalPlaces)));
What was the issue with any number?

2023-09-21 06:36 UTC, kavinvenkatachalam requested changes
@S-Abdul-Rahman Can you resolve the conflicts?

2023-09-25 06:07 UTC, S-Abdul-Rahman commented
> @S-Abdul-Rahman Can you resolve the conflicts?

@kavinvenkatachalam yes, resolved the conflicts.

2023-09-26 03:51 UTC, kavinvenkatachalam approved these changes

2023-11-30 08:44 UTC, Nandinisaha13 commented
@S-Abdul-Rahman Can you please check why can't we show 0 value from number input, attaching a video for reference. 

Uploading Screen Recording 2023-11-30 at 12.02.34 PM.mov…

2023-12-11 09:47 UTC, merged