Fixed undo app name issue
ToolJet/ToolJet pull request #7451
Opened 2023-09-18 06:36 UTC by S-Abdul-Rahman

Fixed #7192

2023-09-21 05:37 UTC, johnsoncherian approved these changes

2023-09-21 10:59 UTC, Ckbhatia commented on frontend/src/Editor/Header/EditAppName.jsx
> +    const handleKeyDown = (e) => {
You can move this function outside of this component

2023-09-26 09:22 UTC, kavinvenkatachalam approved these changes

2023-09-26 09:23 UTC, kavinvenkatachalam requested changes
@S-Abdul-Rahman We can call the function inside the useEffect and we need to remove the event listener when the component is unmounted

2023-09-26 10:53 UTC, kavinvenkatachalam commented
@arpitnath Will it be fixed in your PR?

2023-09-26 19:04 UTC, S-Abdul-Rahman commented
> @S-Abdul-Rahman We can call the function inside the useEffect and we need to remove the event listener when the component is unmounted

@kavinvenkatachalam  So, are you suggesting that these changes need to be reverted back to the previous ones? In the previous code, I added this function inside useEffect and I removed the event listener when the component unmounted.

2023-09-27 09:30 UTC, kavinvenkatachalam approved these changes

2023-09-30 15:58 UTC, arpitnath commented
https://github.com/ToolJet/ToolJet/pull/7451#issuecomment-1735297159
@kavinvenkatachalam Yes

2023-12-11 09:44 UTC, merged