Chetan branch
ToolJet/ToolJet pull request #7555
Opened 2023-09-30 18:31 UTC by Chetax

# Fixes Issue #7527  

# 👨‍💻 Changes proposed(What did you do ?)
Updated the  descriptions(tooltips) for kanban board, color picker and tree select components.

# ✔️ Check List (Check all the applicable boxes)

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.

2023-09-30 18:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7555) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7555) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=7555) it.</sub>

2023-10-04 07:50 UTC, tejakummarikuntla requested changes
Hey! Thanks for the PR.
For the component `Kanban`, you've made changes to the object "KanbanBoard".
Additionally, you'll need to make the same changes for the object "Kanban" which is missed. Could you please address these required changes?

![image](https://github.com/ToolJet/ToolJet/assets/34749692/b1419f0a-ebe3-4a11-b185-9beea9d77200)

2023-10-04 09:46 UTC, Chetax commented
@tejakummarikuntla  can you please review once again.

2023-10-11 19:17 UTC, tejakummarikuntla requested changes
Hey @Chetax, Thanks for addressing the changes, there's one more change needed, please take a look into the comment.

2023-10-11 19:17 UTC, tejakummarikuntla commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +    displayName: 'Kanban Board',
Hey @Chetax , please revert this change; the `displayName` value should not be altered. It should be back to 'Kanban'. You can keep the changes in the `description` value.

2023-10-20 09:16 UTC, merged