Update the Baserow Docs
ToolJet/ToolJet pull request #7612
Opened 2023-10-04 17:47 UTC by AniruddhaGawali

as per the issue assigned to me #7595 

I have update the docs of current version , v2.19.0, v2.18.0
added new instructions in docs as per given in issue
i was an great experience to work on this project and i try to add more contribution on it

2023-10-04 17:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7612) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7612) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=7612) it.</sub>

2023-10-05 13:58 UTC, AniruddhaGawali commented
@tejakummarikuntla  can you please check and merge PR

2023-10-06 11:40 UTC, withshubh requested changes
The changes looks good.

Could you please add the following line above the `## Connection`:
```
ToolJet can connect to your Baserow account to read and write data.

## Connection
```

2023-10-07 14:24 UTC, AniruddhaGawali commented
@withshubh  i have updated all the docs as per request can you check and merge it

2023-10-09 09:30 UTC, withshubh approved these changes

2023-10-20 09:20 UTC, merged