Update azureblob.md
ToolJet/ToolJet pull request #7615
Opened 2023-10-04 18:41 UTC by mangnez

- Replaced 'global datasource' with 'data source' or 'data sources' in the doc.
- Made all the headings in the doc to Title Case.

2023-10-04 18:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7615) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7615) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=7615) it.</sub>

2023-10-09 09:24 UTC, withshubh requested changes
Hey @mangnez 
You have only made the change in the file in `docs/docs`,
Please make the same changes here:
- `docs/versioned_docs/version-2.19.0`
- `docs/versioned_docs/version-2.18.0`

2023-10-11 09:38 UTC, mangnez commented
@withshubh, thanks for letting me know
I've made the required changes now,
- version-2.19.0 -> 16317d73d23a8ac4904ebb1222c599cbc4be768f
- version-2.18.0 ->  bc329d7735d9fc47cdab62c2f7aa32e0bc8670fe

2023-10-16 10:17 UTC, withshubh approved these changes

2023-10-20 09:18 UTC, merged