Fixes CurrentUser & Mode not present in globals in inspector.
ToolJet/ToolJet pull request #7812
Opened 2023-10-11 17:14 UTC by nakulnagargade

2023-10-14 11:22 UTC, arpitnath commented
@nakulnagargade 
revert the commit for page switch fix on creating a new change.
I dont think so we should introduce one more state and an useEffect to update the app slug.
Have fixed it here : https://github.com/ToolJet/ToolJet/pull/7873
cc: @emidhun

2023-10-14 11:23 UTC, arpitnath requested changes

2023-10-14 11:23 UTC, arpitnath commented on frontend/src/Editor/EditorFunc.jsx
> +    if (newPageId) {
Lets not introduce a useEffect if we can avoid it

2023-10-16 06:56 UTC, nakulnagargade commented
> @nakulnagargade Could you please revert the commit related to the page switch fix when creating a new change? I believe there's no need to introduce an additional state and a useEffect to update the app slug. The issue has been resolved here : #7873 cc: @emidhun

Commit is reverted.

2023-10-16 10:06 UTC, merged