solved labels to sentence case
ToolJet/ToolJet pull request #7843
Opened 2023-10-12 21:01 UTC by ronisarkarexe

Issue
closed #7799

Solved inconsistency in the text casing, changed labels to sentence case for Form component

2023-10-12 21:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7843) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7843) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=7843) it.</sub>

2023-10-16 18:15 UTC, tejakummarikuntla requested changes
Hey @ronisarkarexe, I request you to revisit the issue description https://github.com/ToolJet/ToolJet/issues/7799 and be sure to update the PR with changes that are only requested in the table. 

Kindly revert all the other changes which are not relevant to the form component and which are not mentioned in the issue. Kindly update the PR to progress it for further reviews.

2023-10-23 18:19 UTC, tejakummarikuntla commented
Hey @ronisarkarexe, were you able to look into the suggested changes?

2023-10-30 12:32 UTC, withshubh requested changes
You have to make changes only for the form component.
Search for `component: 'Form',` in the file
or go to line number 5672

2023-10-31 12:49 UTC, ronisarkarexe commented
> Hey @ronisarkarexe, were you able to look into the suggested changes?

Could you please verify if this is correct?

2023-11-01 10:26 UTC, tejakummarikuntla requested changes
Hey @ronisarkarexe, kindly address the suggested changes.

2023-11-01 10:26 UTC, tejakummarikuntla commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        displayName: 'Loading State',
@ronisarkarexe, please revert this change.

2023-12-28 11:45 UTC, withshubh commented
Closing this pull request due to inactivity.

2023-12-28 11:45 UTC, closed without merging