Change labels to sentence case for PDF component
ToolJet/ToolJet pull request #7869
Opened 2023-10-13 19:00 UTC by imsoumik03

issue #7792 
### Description

_I have changed the values of the followings of the PDF component ->_

2023-10-17 16:05 UTC, tejakummarikuntla requested changes
Hey @imsoumik03, kindly look into the comments and update the changes.

2023-10-17 16:05 UTC, tejakummarikuntla commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +    displayName: 'Pdf',
Please revert this change.

2023-10-17 16:05 UTC, tejakummarikuntla commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +    description: 'Embed pdf documents',
Please revert this change.

2023-10-17 16:05 UTC, tejakummarikuntla commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +      url: { type: 'code', displayName: 'File url', validation: { schema: { type: 'string' } } },
Please revert this change.

2023-10-23 18:15 UTC, tejakummarikuntla commented
Hey @imsoumik03, kindly address the suggested changes to progress the PR.

2023-10-29 11:21 UTC, karan-rathod-316 commented
Hi @imsoumik03, reassigning this to someone else as we are not getting any response from you.

2023-10-29 11:21 UTC, closed without merging