chore: Correct casing in File Picker component labels
ToolJet/ToolJet pull request #7962
Opened 2023-10-18 19:01 UTC by amarnathgupta

Addresses issue #7756 

In this commit, I have resolved the issue by correcting the casing of specific labels in the File Picker component. The following changes were made in the `widgetConfig.js` file under the File Picker component object:

- Updated label: 'Instruction Text' to 'Instruction text'
- Updated label: 'Use Drop Zone' to 'Use drop zone'
- Updated label: 'Use File Picker' to 'Use file picker'
- Updated label: 'Border Radius' to 'Border radius'

These changes align the labels with the recommended sentence case format as specified in the issue. The commit resolves the inconsistency reported in issue #7756

2023-10-18 19:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7962) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7962) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=7962) it.</sub>

2023-10-19 02:23 UTC, amarnathgupta commented
Hi sir/ma'am, please let me know if anything more required and thank you to hold these issue for the new comers I appreciate it, take care.

2023-10-19 12:01 UTC, tejakummarikuntla requested changes
Hey @amarnathgupta, please address the requested changes.

2023-10-19 12:01 UTC, tejakummarikuntla commented on frontend/src/Editor/WidgetManager/widgetConfig.js
> +        displayName: 'Border radius',
Please revert this change.

2023-10-19 12:03 UTC, tejakummarikuntla commented
I'm sorry @amarnathgupta, the issue is not assigned to you.
Please refrain from raising Pull Requests for issues that have not been assigned to you. Thank you.

2023-10-19 12:03 UTC, closed without merging