Fix: changed labels in buttonGroup component
ToolJet/ToolJet pull request #7979
Opened 2023-10-20 11:42 UTC by Aysha-py

2023-10-20 11:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7979) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=7979) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=7979) it.</sub>

2023-10-23 18:53 UTC, tejakummarikuntla requested changes
Hey @ .
The changes are needed only for the components mentioned in the issue. In your case, it is `ButtonGroup`; you will need to revert all the changes that are not in the `ButtonGroup` component object.
![Screenshot 2023-10-24 at 12 23 14 AM](https://github.com/ToolJet/ToolJet/assets/34749692/f99bb429-a6b7-4645-abf8-98a83487fff8)

Also, be sure to make changes to the labels that are mentioned in the issue description table alone. Kindly do not make changes to anything outside the table information.

Please address this to progress your PR.

2023-10-30 12:18 UTC, withshubh requested changes
Please make the changes only to `button group` component. The changes are made randomly to several components.

2023-11-01 09:55 UTC, closed without merging

2023-11-01 09:55 UTC, tejakummarikuntla commented
Closing the PR due to inactivity.