[docs] git sync
ToolJet/ToolJet pull request #8078
Opened 2023-10-31 05:40 UTC by withshubh

#### changs
- adds documenation for git sync feature

2023-11-17 08:37 UTC, thehacklady requested changes

2023-11-17 08:37 UTC, thehacklady commented on docs/docs/gitsync.md
> +
The last statement is incorrect, we are just deleting data in db. We should define the delete behaviour properly. Can you please take a look once?

2023-12-07 10:51 UTC, thehacklady submitted a review, later dismissed

2023-12-13 10:56 UTC, gsmithun4 approved these changes

2023-12-13 10:57 UTC, merged