Feature - New dropdown revamp
ToolJet/ToolJet pull request #8160
Opened 2023-11-15 14:42 UTC by nakulnagargade

2024-01-24 12:24 UTC, sherfin94 requested changes
Hey @nakulnagargade , there are conflicts. Also, something seem to be wrong with the commit history, changing base from github seem to have affected the commit history.

2024-01-24 13:34 UTC, sherfin94 requested changes
Hi @nakulnagargade , few issues:

1. Existing dropdown break out of the selector: 
<img width="231" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20333972/5b5625ff-73a3-4171-abde-57542adf4128">

2. Search text is not visible in dark mode:
<img width="231" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20333972/ab763d38-c0bc-4dab-8ba7-50b4f22b6c1b">

3. `Background`:
<img width="168" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20333972/f1da9aa2-4b92-4704-a114-94fd1a45187c">

2024-01-30 06:13 UTC, nakulnagargade commented
@sherfin94 Code comments are resolved.

2024-01-31 06:33 UTC, sherfin94 approved these changes

2024-02-08 04:00 UTC, kavinvenkatachalam approved these changes

2024-02-08 04:00 UTC, merged