Fix-create-new-application-button-#8225
ToolJet/ToolJet pull request #8311
Opened 2023-12-14 19:04 UTC by Himanshuch8055

### What is the issue
The "create new application" button on the dashboard page is not aligned properly.
For better visual consistency, align the "Create New Application" button with other elements adjacent to the "Welcome to your new ToolJet workspace" text.

fixes: #8225

2023-12-14 19:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=8311) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=8311) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=8311) it.</sub>

2023-12-28 12:52 UTC, kavinvenkatachalam requested changes
@Himanshuch8055 Changing `tabler.scss` is not recommended. Please revert the change and make the changes on `theme.scss`

2023-12-28 13:22 UTC, Himanshuch8055 commented
Ok I will see. @kavinvenkatachalam

2024-04-18 14:33 UTC, karan-rathod-316 commented
Closing this due to inactivity.

2024-04-18 14:33 UTC, closed without merging