Automation: Deletion of component from inspector
ToolJet/ToolJet pull request #8346
Opened 2023-12-19 10:40 UTC by Nandinisaha13

fixes: #8345

2023-12-28 06:14 UTC, emidhun commented on cypress-tests/cypress/e2e/editor/inspectorHappypath.cy.js
> +
- I think we need to add assertion to verify the deletion of component and the toast message, after the deletion.
- Let's create one more version and verify that the components is not exist on canvas.

2023-12-28 06:16 UTC, emidhun commented on cypress-tests/cypress/support/utils/inspector.js
> +  cy.get(cy.get('[style="height: 13px; width: 13px;"] > img').click());
I think we can only use `cy.get('[style="height: 13px; width: 13px;"] > img').click()` here.

2023-12-28 06:17 UTC, emidhun requested changes
@Nandinisaha13 I have added few changes, Please add the cases and let me know if you need any help.

2024-01-04 08:55 UTC, Nandinisaha13 commented
@emidhun please take a look have fixed the comments.

2024-01-05 06:33 UTC, emidhun commented
@Nandinisaha13  Could you please add the delete functionality from the right side panel as well?
I think Only this case is pending on deletion.
Please let me know if it is possible.
Rest everything is looking good.

2024-01-15 09:51 UTC, emidhun approved these changes
LGTM

2024-01-15 09:52 UTC, merged