Feature/query parameters for all queries
ToolJet/ToolJet pull request #8347
Opened 2023-12-19 11:05 UTC by sherfin94

2024-01-04 12:11 UTC, sherfin94 commented
Hey @stepinfwd , the `(0)` after the parameter label might confuse builders, lets avoid it.

2024-01-30 05:42 UTC, kavinvenkatachalam requested changes
@sherfin94 Added few suggestions,

Other than that in UI, the parameter text and pills seems to be very close. Check with Jaseem once. Attaching the screenshot

<img width="308" alt="image" src="https://github.com/ToolJet/ToolJet/assets/50441969/7215f470-c3ab-46ea-b90d-ead636ed1608">

2024-01-30 05:42 UTC, kavinvenkatachalam commented on frontend/src/_styles/components.scss
> +  // width: 215px !important;
```suggestion
```

2024-01-30 05:42 UTC, kavinvenkatachalam commented on frontend/src/Editor/QueryManager/QueryManager.jsx
> +import { resolveReferences } from '../../_helpers/utils';
```suggestion
import { resolveReferences } from '@/_helpers/utils';
```

2024-01-30 05:42 UTC, kavinvenkatachalam commented on frontend/src/Editor/CodeBuilder/CodeHinter.jsx
> +import { useCurrentStateStore } from '@/_stores/currentStateStore';
Can we import only the state instead of complete store? It might expose the setting currentState actions as well

2024-02-01 03:37 UTC, kavinvenkatachalam approved these changes

2024-02-06 08:32 UTC, merged