Feat:: Button component revamp
ToolJet/ToolJet pull request #8361
Opened 2023-12-20 14:32 UTC by stepinfwd

2024-01-15 20:47 UTC, sherfin94 approved these changes

2024-02-19 09:38 UTC, kavinvenkatachalam requested changes
@stepinfwd Please resolve the conflicts and cross check with the design

2024-05-08 20:17 UTC, johnsoncherian commented on server/data-migrations/1707466537651-MoveVisibilityDisabledStatesToProperties.ts
> +    const componentTypes = ['TextInput', 'NumberInput', 'PasswordInput', 'Text', 'Button'];
Will this work for when someon upgrades a version.? Dont we need a new migration here?

2024-05-10 07:23 UTC, johnsoncherian approved these changes

2024-05-10 07:23 UTC, johnsoncherian commented on server/data-migrations/1707466537651-MoveVisibilityDisabledStatesToProperties.ts
> +    const componentTypes = ['TextInput', 'NumberInput', 'PasswordInput', 'Text', 'Button'];
Handled in https://github.com/ToolJet/ToolJet/pull/9665/files

2024-05-24 14:59 UTC, merged