Change Image Component label to sentence case
ToolJet/ToolJet pull request #8412
Opened 2023-12-27 06:21 UTC by Just-A-Pixel

This PR aims to resolve issue #7773.

The issue occurred due to the namespace in en.json

2023-12-27 06:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=8412) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=8412) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=8412) it.</sub>

2023-12-28 11:43 UTC, withshubh requested changes
Hey @Just-A-Pixel 
1. There are two properties that need to be fixed.
2. The following file needs to be edited `frontend/src/Editor/WidgetManager/widgetConfig.js`

Please go through the issue description carefully #7773

2023-12-31 16:48 UTC, Just-A-Pixel commented
Hello @withshubh!
It looks like the additional information I wrote while editing the PR did not update due to network issues. Apologies!

I have tried the methods mentioned in the issue, but that did not resolve it. 
Upon checking ```frontend/src/Editor/WidgetManager/widgetConfig.js``` , the values 'Loading state' and 'Background color' were already in sentence case. The snippet is below:
```
{
    name: 'Image',
    displayName: 'Image',
    description: 'Show image files',
    .
    .  // other keys
    .
    properties: {
      .
      .  // other keys
      .
      loadingState: {
        type: 'toggle',
        displayName: 'Loading state',    
        validation: {
          schema: { type: 'boolean' },
        },
      },
   }
  styles: {
      .
      .  // other keys
      .
      backgroundColor: {
        type: 'color',
        displayName: 'Background color',
        validation: {
          schema: { type: 'string' },
        },
      },
  }
```

Loading state is displayed in sentence case, but background color is not. I have narrowed the cause to the translation function:
```label={t(widget.commonProperties.${camelCase(paramLabel)}, paramLabel)}``` in ```frontend/src/Editor/CodeBuilder/CodeHinter.jsx```

After going through the translation files, the issue was found to be occurred due to the namespace in en.json, for which the PR has been raised.

2024-01-02 09:33 UTC, karan-rathod-316 approved these changes
LGTM

2024-01-02 09:43 UTC, withshubh approved these changes

2024-01-02 10:00 UTC, merged