feat :: Checkbox + Toggle revamp
ToolJet/ToolJet pull request #8519
Opened 2024-01-08 06:20 UTC by stepinfwd

2024-01-15 20:36 UTC, sherfin94 requested changes
Hey @stepinfwd , the `onChange` event is not available in the checkbox. Also, for the toggle switch, the two of the styles say 'Checked color' and 'Unchecked color', this should be something like 'color when turned on', 'color when turned off', speak to PM on this.

2024-01-18 20:09 UTC, sherfin94 requested changes
Hey @stepinfwd , the `onChange` event does not seem to working when I tried checking and unchecking.

2024-01-24 13:40 UTC, sherfin94 requested changes
Hey @stepinfwd ,

I set the `onChange` to show the value of the checkbox, but it is giving showing `false` when it should be `true` and giving `true` when it should be `false`.

<img width="460" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20333972/f6ba4959-e84f-4bed-8921-f5e7daddded6">


<img width="460" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20333972/c721dcf8-1655-4245-a9b0-b800300ba2a4">


<img width="460" alt="image" src="https://github.com/ToolJet/ToolJet/assets/20333972/cb854ebd-284b-4080-b6e9-750c351053ea">

2024-02-19 09:43 UTC, kavinvenkatachalam requested changes
@stepinfwd Please resolve the conflicts and check with the design. There might be some changes

2024-05-10 12:11 UTC, johnsoncherian commented on frontend/assets/images/icons/widgets/index.jsx
> +import ToggleSwitchNew from './toggleswitchV2.jsx';
Lets Keep filename and component name same wherever possible

2024-05-13 10:05 UTC, johnsoncherian approved these changes

2024-05-24 15:10 UTC, merged