AWS Redshift plugin
ToolJet/ToolJet pull request #8839
Opened 2024-02-17 10:38 UTC by ShazanRizvi

This PR closes the issue #5725

2024-02-19 09:26 UTC, akshaysasidrn commented on marketplace/plugins/awsredshift/lib/index.ts
> +        // ],
Can remove unused code

2024-02-26 13:02 UTC, akshaysasidrn commented on marketplace/plugins/harperdb/lib/query_operations.ts
This is not related right? Can we remove this?

2024-02-27 10:32 UTC, akshaysasidrn commented on marketplace/plugins/awsredshift/lib/types.ts
> +  secretARN: string;
since we don't support it currently, can be reoved

2024-02-28 07:07 UTC, akshaysasidrn requested changes

2024-02-28 07:07 UTC, akshaysasidrn commented on marketplace/plugins/awsredshift/lib/index.ts
> +        while (status !== 'FINISHED') {
Do add a timeout for polling to break out of the while loop.
We can add a 30s timeout.

2024-02-28 15:14 UTC, akshaysasidrn approved these changes

2024-03-04 15:30 UTC, ShazanRizvi commented
Documentation PR: #8984

2024-03-07 06:03 UTC, merged