Import higher version fix
ToolJet/ToolJet pull request #8922
Opened 2024-02-27 02:49 UTC by kriks7iitk

1. Handling error when import export

2024-02-27 02:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=8922) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=8922) before we can accept your contribution.<br/><hr/>**Kritagya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=8922) it.</sub>

2024-02-27 08:44 UTC, gsmithun4 requested changes

2024-02-27 08:44 UTC, gsmithun4 commented on frontend/src/HomePage/HomePage.jsx
> +        toast.error(APP_ERROR_TYPE.IMPORT_EXPORT_SERVICE.UNSUPPORTED_VERSION_ERROR);
```suggestion
        toast.error(error?.error || APP_ERROR_TYPE.IMPORT_EXPORT_SERVICE.UNSUPPORTED_VERSION_ERROR);
```

2024-02-27 08:44 UTC, akshaysasidrn approved these changes

2024-03-21 06:30 UTC, gsmithun4 approved these changes

2024-03-21 06:30 UTC, gsmithun4 approved these changes

2024-03-21 06:31 UTC, merged