Edited the label for the workspace constants button
ToolJet/ToolJet pull request #9171
Opened 2024-03-22 22:15 UTC by joelali5

Changed the workspace variables button for issue [https://github.com/ToolJet/ToolJet/issues/9156](url) 
<img width="1440" alt="Screenshot 2024-03-22 at 22 08 45" src="https://github.com/ToolJet/ToolJet/assets/42684254/948aed8d-d8bc-482d-b6f5-8ae42dce666d">

2024-03-22 22:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=9171) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ToolJet/ToolJet?pullRequest=9171) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ToolJet/ToolJet?pullRequest=9171) it.</sub>

2024-03-27 10:02 UTC, gsmithun4 requested changes
Please revert the package-lock.json file changes

2024-03-27 21:59 UTC, closed without merging

2024-03-27 22:06 UTC, joelali5 commented
Hi @gsmithun4 I have removed the package lock file. Here [Changed a label related to workspace](https://github.com/ToolJet/ToolJet/pull/9218)

2024-03-27 22:26 UTC, joelali5 commented
I had difficulties reverting the package lock file, so I had to delete the remote branch and push new changes to the new file again, which is the reason for the new PR.