feat : Primary key feature in ToolJet database
ToolJet/ToolJet pull request #9279
Opened 2024-04-03 15:18 UTC by S-Abdul-Rahman

Primary key feature in create an edit table and create and edit row and edit column
Issues : 
#9034 
#9040
#9043
#9036

2024-04-04 17:40 UTC, akshaysasidrn requested changes

2024-04-04 17:40 UTC, akshaysasidrn commented on frontend/src/TooljetDatabase/Forms/ColumnForm.jsx
> +              dataType?.value !== 'serial' && isNotNull === true && defaultValue.length <= 0 && rows.length > 0
can we define these conditions in a const variable and reuse them?

```js
const defaultValueRequired = dataType.value !== 'serial' && isNotNull && isEmpty(defaultValue) && !isEmpty(rows) 
```

Also let us always start to stick with to use `cx` from classnames when we are handling condition for CSS classes

2024-04-04 17:40 UTC, akshaysasidrn commented on frontend/src/TooljetDatabase/Forms/TableSchema.jsx
> +      columns[columnSelection.index]?.column_default?.includes('nextval(') &&
can we also add `::regclass` being present in the default value as well?

We can use a regex like: `/^nextval\(".*"::regclass\)$/`

2024-04-04 17:40 UTC, akshaysasidrn commented on frontend/src/_components/ConfirmDialog.jsx
> +      <Modal.Footer className={`${footerStyle?.marginTop ? '' : 'mt-3'}`} style={footerStyle}>
use `cx`

2024-04-04 18:54 UTC, akshaysasidrn commented
Also don't forget that we would have to add `is_unique` key for [handling imports](https://github.com/ToolJet/ToolJet/blob/feature/tjdb-create-primarykey/server/src/helpers/tjdb_dto_transforms.ts#L12) from older versions.

2024-04-08 07:03 UTC, ganesh8056 commented on server/src/services/tooljet_db.service.ts
> +                    ? this.addQuotesIfString(newColumn?.column_default)
If we remove **addQuotesIfString** method ORM is considering string as expression. So it would be needed

2024-04-30 09:17 UTC, merged