feat : Foreign key feature in ToolJet database
ToolJet/ToolJet pull request #9544
Opened 2024-04-29 18:26 UTC by S-Abdul-Rahman

2024-05-01 21:46 UTC, akshaysasidrn requested changes

2024-05-01 21:46 UTC, akshaysasidrn commented on server/src/services/tooljet_db.service.ts
> +      return { statusCode: 200, message: 'Foreign key relation created successfully!' };
Will advise to have request-response specific context only at the controller. It is better to return a boolean, check the result at the service (business logic) and give apt response code and message (request-response logic) at the controller.

2024-05-01 21:46 UTC, akshaysasidrn commented on frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/DropDownSelect.jsx
> +            setPageNumber={setPageNumber}
I'm concerned about the number of props piling up, can we group them based on context to have better readability?

```js
pagination={{
  pageNumber,
  setPageNumber,
  totalRecords,
  setTotalRecords
}}

foreignKeyProps={{
  foreignKeyAccess,
  foreignKeyAccessInRowForm,
  foreignKeys,
  setReferencedColumnDetails,
  shouldShowForeignKeyIcon,
  isInitialForeignKeyDataLoaded,
  setIsInitialForeignKeyDataLoaded
}}

```

2024-05-01 21:46 UTC, akshaysasidrn commented on frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/JoinConstraint.jsx
> +  function autoFillColumnIfForeignKeyExists(tableId, isChoosingLHStable) {
nicely done!

2024-05-01 21:46 UTC, akshaysasidrn commented on frontend/src/Editor/QueryManager/QueryEditors/TooljetDatabase/SelectBox.jsx
> +  scrollEventForColumnValus,
Values*

2024-05-07 19:35 UTC, ganesh8056 commented on server/src/services/tooljet_db.service.ts
> +  column_names: Array<string>;
Yes, but it can support Composite Foreign key by design. So we have kept it as array for column_names and referenced_column_names

2024-05-08 08:17 UTC, merged