Masking workspace constants on frontend
ToolJet/ToolJet pull request #9596
Opened 2024-05-02 19:40 UTC by AnantshreeChandola

1. Backend Resolution of Workspace-Constants Values:
  All workspace-constants values are resolved entirely on the backend. This centralized handling ensures consistency and 
  security across all points of access.
2. Transmission of Encrypted Values:
 Except on the 'Mange workspace constants' page, values are not sent to the frontend. This is done to  
 ensure that the constants' values are not exposed during transmission or in client-side environments.
3. Permission Checks on API Access for workspace constants handling:
 The GET APIs for workspace constants include a step to resolve the user's permissions to create, update, or delete 
 workspace constants along with a query param 'decryptValue' to ensure that only authorized users can access the 
 decrypted values of the constants and only on the 'Manage workspace constants' page.
 4. Added logic to verify constants keys used in codehinter.

Resolves https://github.com/ToolJet/ToolJet/issues/9412

2024-05-07 11:07 UTC, gsmithun4 requested changes

2024-05-07 11:07 UTC, gsmithun4 commented on server/src/controllers/organization_constants.controller.ts
> +  async get(@User() user, @Req() req) {
@Query('decryptValue') decryptValue

2024-05-07 11:07 UTC, gsmithun4 commented on server/src/controllers/organization_constants.controller.ts
> +  async getConstantsFromApp(@App() app, @User() user, @Req() req) {
@query('decryptValue') decryptValue

2024-05-07 11:07 UTC, gsmithun4 commented on server/src/controllers/organization_constants.controller.ts
> +  async getConstantsFromEnvironment(@User() user, @Param('environmentId') environmentId, @Req() req) {
@query('decryptValue') decryptValue

2024-05-07 11:07 UTC, gsmithun4 commented on server/src/controllers/organization_constants.controller.ts
> +    const ability = await this.organizationConstantsAbilityFactory.organizationConstantActions(user, null);
This route is used for getting data for public apps, do we need `decryptValue` here?

2024-05-07 11:07 UTC, gsmithun4 commented on frontend/src/Editor/Editor.jsx
>          const constantValue = constant.values.find((value) => value.environmentName === 'production')['value'];
`constantValue` is not used, can remove

2024-05-08 15:45 UTC, shah21 submitted a review, later dismissed

2024-05-14 10:19 UTC, gsmithun4 approved these changes

2024-05-14 10:19 UTC, merged