4577 bugfix
ToolJet/ToolJet pull request #9602
Opened 2024-05-03 10:30 UTC by rudeUltra

Fixing "<>&" naming errors

2024-05-14 07:10 UTC, rudeUltra commented
Fixes #4577

2024-05-14 09:14 UTC, gsmithun4 requested changes

2024-05-14 09:14 UTC, gsmithun4 commented on frontend/ee/components/UsersPage/UsersTable.jsx
> +function decodeEntities(encodedString) {
Move this function to `_helpers/utils.js` and reuse

2024-05-15 09:07 UTC, gsmithun4 requested changes

2024-05-15 09:07 UTC, gsmithun4 commented on frontend/src/_helpers/utils.js
> +  return encodedString.replace(/&lt;/gi, '<').replace(/&gt;/gi, '>').replace(/&amp;/gi, '&');
```suggestion
  return encodedString?.replace(/&lt;/gi, '<')?.replace(/&gt;/gi, '>')?.replace(/&amp;/gi, '&');
```

2024-05-15 09:26 UTC, gsmithun4 approved these changes

2024-05-15 09:27 UTC, merged