Move disabled, visibility, tooltip and box shadow to properties
ToolJet/ToolJet pull request #9665
Opened 2024-05-09 10:54 UTC by nakulnagargade

This PR migrates:

- Disabled state from styles to properties
- Visibility from styles to properties
- Tooltip from general to properties
- Box shadow from general styles to properties

2024-05-10 07:01 UTC, arpitnath requested changes

2024-05-10 07:01 UTC, arpitnath commented on server/data-migrations/1715248567720-MoveCheckboxToggleDisabledToProperties.ts
> +  public async down(queryRunner: QueryRunner): Promise<void> {}
We need to create a rollback function for database migrations.

2024-05-10 19:09 UTC, arpitnath approved these changes

2024-05-13 06:27 UTC, johnsoncherian approved these changes

2024-05-29 05:53 UTC, johnsoncherian approved these changes

2024-05-29 06:10 UTC, johnsoncherian approved these changes

2024-05-29 06:11 UTC, johnsoncherian approved these changes

2024-05-29 06:11 UTC, merged