Feat/drawer shortcut keys
ToolJet/ToolJet pull request #9791
Opened 2024-05-20 17:01 UTC by shaurya-sharma064

2024-05-22 11:18 UTC, akshaysasidrn requested changes

2024-05-22 11:18 UTC, akshaysasidrn commented on frontend/src/TooljetDatabase/Forms/RowForm.jsx
> +  const defaultDataValues = () => {
nit: let's stick with never-nester mentality for readability

```js
const defaultDataValues = () => {
  return rowColumns.reduce((result, column) => {
    const { dataType, column_default, accessor } = column;

    if (dataType === 'serial') {
      return result;
    }

    if (dataType === 'boolean') {
      result[accessor] = column_default !== undefined ? column_default : false;
      return result;
    }

    result[accessor] = column_default !== undefined ? column_default : '';
    return result;
  }, {});
};
```

2024-05-22 11:18 UTC, akshaysasidrn commented on frontend/src/TooljetDatabase/Forms/RowForm.jsx
> +      }
same thing here

2024-05-22 11:18 UTC, akshaysasidrn commented on frontend/src/TooljetDatabase/Forms/RowForm.jsx
> +                    isSerialDataTypeColumn && !darkMode
Use `cx` from `classnames` package, when revising existing className. It is a tech debt, we can fix them slowly when we change the class names

2024-05-22 19:11 UTC, shaurya-sharma064 commented on frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
> +  const [fnCaller, setFnCaller] = useState(0);
Using it as a number to avoid running it the first time and then executing it everytime afterward.

2024-05-22 19:24 UTC, shaurya-sharma064 commented on frontend/src/TooljetDatabase/Drawers/CreateRowDrawer/index.jsx
> +          onCreate={(bypass) => {
kept it as shouldKeepDrawerOpen based on code context

2024-05-22 19:43 UTC, shaurya-sharma064 commented on frontend/src/TooljetDatabase/Forms/EditRowForm.jsx
> +  useEffect(() => {
Fixed no need for optional chaining

2024-05-23 10:04 UTC, akshaysasidrn commented on frontend/src/TooljetDatabase/constants.js
> +export const postgresErrorCode = {
Nice!!

2024-05-23 10:04 UTC, akshaysasidrn approved these changes

2024-05-28 15:40 UTC, akshaysasidrn submitted a review, later dismissed

2024-06-03 15:36 UTC, akshaysasidrn approved these changes

2024-06-03 15:36 UTC, merged