Feature: Allow filtering or result using a formula
ToolJet/ToolJet pull request #9796
Opened 2024-05-21 06:27 UTC by parthy007

Closes: [#9715](https://github.com/ToolJet/ToolJet/issues/9715)

2024-06-11 17:15 UTC, akshaysasidrn submitted a review, later dismissed

2024-06-17 10:08 UTC, akshaysasidrn commented
/review

2024-06-17 11:27 UTC, akshaysasidrn requested changes

2024-06-17 11:27 UTC, akshaysasidrn commented on plugins/packages/airtable/lib/index.ts
> +            const parsedFields = JSON.parse(fields);
@parthy007 please check the case where invalid fields is passed, it is handled properly or not

2024-06-17 11:27 UTC, akshaysasidrn commented on plugins/packages/airtable/lib/index.ts
> +            requestBody.filterByFormula = filterFormula;
Can skip

2024-06-17 11:48 UTC, akshaysasidrn commented
/review

2024-06-18 01:12 UTC, parthy007 commented
/review

2024-07-23 11:26 UTC, closed without merging